/**
 * AUTO-GENERATED — do not edit by hand.
 * Regenerate: python3 scripts/hive/sync-grok-roster-agent-roles.py
 */

export const GROK_ROSTER_AGENT_PROFILE: Record<string, string> = {
  "grok-biz-proofcheck-gtm": "gtm",
  "grok-biz-sentinel-gtm": "gtm",
  "grok-biz-clipengine-gtm": "gtm",
  "grok-biz-trendspotter-gtm": "gtm",
  "grok-biz-growth-seo-lead": "gtm",
  "grok-biz-funnel-optimizer": "content",
  "grok-biz-distribution-ops": "content",
  "grok-biz-lead-ops": "lead_gen",
  "grok-biz-sales-copy-ops": "content",
  "grok-biz-pipeline-analyst": "finance_read",
  "grok-biz-revenue-intel": "revenue_intel",
  "grok-biz-market-scout": "research",
  "grok-biz-finance-ops": "finance_read",
  "grok-biz-scoreboard-keeper": "knowledge",
  "grok-biz-client-delivery-lead": "content",
  "grok-craft-full-stack-builder": "builder",
  "grok-craft-quality-engineer": "builder",
  "grok-craft-platform-engineer": "builder",
  "grok-craft-web-studio": "builder",
  "grok-craft-web-ops": "builder",
  "grok-craft-video-studio": "creative",
  "grok-craft-motion-finish": "creative",
  "grok-craft-godot-engineer": "creative",
  "grok-craft-game-studio": "creative",
  "grok-craft-animation-studio": "creative",
  "grok-craft-visual-design": "creative",
  "grok-craft-media-producer": "content",
  "grok-craft-mac-automation-engineer": "builder",
  "grok-craft-data-analyst": "knowledge",
  "grok-craft-ai-learning": "research",
  "grok-craft-web-intelligence-hunter": "research",
  "grok-biz-client-enablement-partner": "content",
  "grok-biz-ai-audit-partner": "research",
  "grok-biz-day-planner": "content"
}

export const GROK_ROSTER_ROLE_LINES: Record<string, string> = {
  "grok-biz-proofcheck-gtm": "Grok roster biz \u2014 ProofCheck GTM (gtm)",
  "grok-biz-sentinel-gtm": "Grok roster biz \u2014 SENTINEL GTM (gtm)",
  "grok-biz-clipengine-gtm": "Grok roster biz \u2014 ClipEngine GTM (gtm)",
  "grok-biz-trendspotter-gtm": "Grok roster biz \u2014 TrendSpotter GTM (gtm)",
  "grok-biz-growth-seo-lead": "Grok roster biz \u2014 Growth & SEO Lead (marketing)",
  "grok-biz-funnel-optimizer": "Grok roster biz \u2014 Funnel Optimizer (marketing)",
  "grok-biz-distribution-ops": "Grok roster biz \u2014 Distribution Ops (marketing)",
  "grok-biz-lead-ops": "Grok roster biz \u2014 Lead Ops (sales)",
  "grok-biz-sales-copy-ops": "Grok roster biz \u2014 Sales Copy Ops (sales)",
  "grok-biz-pipeline-analyst": "Grok roster biz \u2014 Pipeline Analyst (sales)",
  "grok-biz-revenue-intel": "Grok roster biz \u2014 Revenue Intel (revenue)",
  "grok-biz-market-scout": "Grok roster biz \u2014 Market Scout (revenue)",
  "grok-biz-finance-ops": "Grok roster biz \u2014 Finance Ops (finance)",
  "grok-biz-scoreboard-keeper": "Grok roster biz \u2014 Scoreboard Keeper (finance)",
  "grok-biz-client-delivery-lead": "Grok roster biz \u2014 Client Delivery Lead (delivery)",
  "grok-craft-full-stack-builder": "Grok roster craft \u2014 Full Stack Builder (engineering)",
  "grok-craft-quality-engineer": "Grok roster craft \u2014 Quality Engineer (engineering)",
  "grok-craft-platform-engineer": "Grok roster craft \u2014 Platform Engineer (engineering)",
  "grok-craft-web-studio": "Grok roster craft \u2014 Web Studio (web)",
  "grok-craft-web-ops": "Grok roster craft \u2014 Web Ops (web)",
  "grok-craft-video-studio": "Grok roster craft \u2014 Video Studio (video)",
  "grok-craft-motion-finish": "Grok roster craft \u2014 Motion & Finish (video)",
  "grok-craft-godot-engineer": "Grok roster craft \u2014 Godot Engineer (gaming)",
  "grok-craft-game-studio": "Grok roster craft \u2014 Game Studio (gaming)",
  "grok-craft-animation-studio": "Grok roster craft \u2014 Animation Studio (animation)",
  "grok-craft-visual-design": "Grok roster craft \u2014 Visual Design (creative)",
  "grok-craft-media-producer": "Grok roster craft \u2014 Media Producer (creative)",
  "grok-craft-mac-automation-engineer": "Grok roster craft \u2014 Mac Automation Engineer (creative)",
  "grok-craft-data-analyst": "Grok roster craft \u2014 Data Analyst (creative)",
  "grok-craft-ai-learning": "Grok roster craft \u2014 AI & Learning (creative)",
  "grok-craft-web-intelligence-hunter": "Grok roster craft \u2014 Web Intelligence Hunter (research)",
  "grok-biz-client-enablement-partner": "Grok roster biz \u2014 Client Enablement Partner (consulting)",
  "grok-biz-ai-audit-partner": "Grok roster biz \u2014 AI Audit Partner (consulting)",
  "grok-biz-day-planner": "Grok roster biz \u2014 Day Planner (ops)"
}
