#!/bin/bash
echo "🔄 n8n Workflow Recovery Script"
echo "================================"
echo ""
echo "Your workflows found:"
echo "✅ AI SaaS Master Scaffold"
echo "✅ AI Content Empire"
echo "✅ AI Research Agent"
echo "✅ Master Orchestration System"
echo "✅ GPT5 Support Agent"
echo "✅ And many more in subdirectories..."
echo ""
echo "📁 All workflow files are located in:"
echo "   ~/n8n-cursor/workflows/"
echo ""
echo "🚀 To restore your workflows:"
echo "1. Complete the n8n setup (create owner account)"
echo "2. Log into n8n"
echo "3. Go to Import and select these files one by one:"
echo ""
ls -1 ~/n8n-cursor/workflows/*.json | while read file; do
  echo "   📄 $(basename "$file")"
done
echo ""
echo "4. Or use the API to bulk import (after setup)"
echo ""
echo "🎯 Your data is 100% safe and ready to restore!"
