// ---- Core tool contract (uniform across all tools) - Tool Layer v2

export type ToolOK<T = unknown> = {
  ok: true;
  data: T;
  error?: undefined;
  meta?: {
    provider?: string;
    took_ms?: number;
    retries?: number;
    source?: string;
    [k: string]: unknown;
  };
};

export type ToolERR = {
  ok: false;
  data?: undefined;
  error: {
    code: string;
    message: string;
    details?: any;
  };
  meta?: {
    provider?: string;
    took_ms?: number;
    retries?: number;
    code?: string | number;
    [k: string]: unknown;
  };
};

export type ToolResult<T = unknown> = ToolOK<T> | ToolERR;

export type ToolInvokeArgs = {
  callId: string;                 // generated by executor
  conversationId: string;
  userId?: string;
  // raw args passed by plan step
  args: Record<string, unknown>;
  // deadline / timeouts / retries
  timeout_ms?: number;
  attempt?: number;
};

// ---- Tool Layer v2: Metadata and Tags

export type ToolName =
  | 'research.run'
  | 'kb.search'
  | 'workflows.trigger'
  | 'logs.tail'
  | 'agent.deploy'
  | 'system.health'
  | 'project.analyze'
  | 'backup.create'
  | 'code.readFile'
  | 'llm.train'
  | 'llm.evaluate'
  | 'files.recent'
  | 'knowledge.list'
  | 'agents.list'
  | 'workflows.list'
  | 'stats.get'
  | 'notifications.post'
  | 'notifications.list'
  | 'project.status'
  | 'operations.list'
  | 'workflows.get'
  | 'agents.get'
  | 'knowledge.get'
  | 'settings.get'
  | 'ontology.search'
  | 'research.start'
  | 'llm.experiments.list'
  | 'llm.models.compare'
  | 'ocr.extract';

export type ToolTags =
  | 'research'
  | 'kb'
  | 'ops'
  | 'system'
  | 'logs'
  | 'llm'
  | 'files'
  | 'browser'
  | 'heavy'
  | 'light'
  | 'safe-only'
  | 'media'
  | 'design'
  | 'math'
  | 'other';

export type ToolMetadata = {
  name: ToolName;
  description: string;
  tags: ToolTags[];
  timeoutMs: number;
  maxRetries: number;
  enabledInLiteMode: boolean;
};

// ---- Conversation scratchpad (executor memory for this turn)

export type ScratchpadEntry = {
  callId: string;
  tool: string;
  timestamp: number;
  result: ToolResult<any>;
};

export type Scratchpad = {
  conversationId: string;
  entries: ScratchpadEntry[];
  put: (e: ScratchpadEntry) => void;
  last: () => ScratchpadEntry | undefined;
};

// Thin in-memory default (swap with Redis if you want)
export function createScratchpad(conversationId: string): Scratchpad {
  const entries: ScratchpadEntry[] = [];
  return {
    conversationId,
    entries,
    put: (e) => entries.push(e),
    last: () => entries[entries.length - 1],
  };
}

