#!/bin/bash
set -Eeuo pipefail

# SSH Hardening Script for n8n-cursor VPS
# Run this script to secure your SSH access and basic firewall

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source common utilities
source "$PROJECT_ROOT/scripts/utils/lib.sh"

# Configuration
SSH_PORT=22
HTTP_PORT=80
HTTPS_PORT=443
SSH_CONFIG="/etc/ssh/sshd_config"
SSH_CONFIG_BACKUP="/etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }

# Check if running as root
check_root() {
  if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
  fi
}

# Backup SSH config
backup_ssh_config() {
  log_info "Backing up SSH configuration..."
  if [[ -f "$SSH_CONFIG" ]]; then
    cp "$SSH_CONFIG" "$SSH_CONFIG_BACKUP"
    log_success "SSH config backed up to $SSH_CONFIG_BACKUP"
  else
    log_error "SSH config file not found at $SSH_CONFIG"
    exit 1
  fi
}

# Harden SSH configuration
harden_ssh() {
  log_info "Hardening SSH configuration..."

  # Create hardened SSH config
  cat >"$SSH_CONFIG" <<'EOF'
# SSH Hardened Configuration for n8n-cursor VPS
# Generated by scripts/ops/harden-ssh.sh

# Basic SSH settings
Port 22
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Security settings
PermitRootLogin no
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
AllowTcpForwarding no
GatewayPorts no
PermitTunnel no
MaxAuthTries 3
MaxSessions 5
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# Key-based authentication only
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Logging
SyslogFacility AUTH
LogLevel INFO

# Allow specific users (modify as needed)
AllowUsers evens

# Additional security
PermitEmptyPasswords no
PermitUserEnvironment no
StrictModes yes
EOF

  log_success "SSH configuration hardened"
}

# Configure UFW firewall
configure_ufw() {
  log_info "Configuring UFW firewall..."

  # Install UFW if not present
  if ! command -v ufw &>/dev/null; then
    log_info "Installing UFW..."
    apt-get update
    apt-get install -y ufw
  fi

  # Reset UFW rules
  ufw --force reset

  # Set default policies
  ufw default deny incoming
  ufw default allow outgoing

  # Allow SSH (critical - don't change port without testing!)
  ufw allow $SSH_PORT/tcp comment "SSH access"

  # Allow HTTP/HTTPS
  ufw allow $HTTP_PORT/tcp comment "HTTP"
  ufw allow $HTTPS_PORT/tcp comment "HTTPS"

  # Allow n8n ports if different from standard
  # ufw allow 5678/tcp comment "n8n application"

  # Enable UFW
  ufw --force enable

  log_success "UFW firewall configured and enabled"
}

# Install and configure fail2ban
configure_fail2ban() {
  log_info "Installing and configuring fail2ban..."

  # Install fail2ban
  if ! command -v fail2ban-client &>/dev/null; then
    apt-get update
    apt-get install -y fail2ban
  fi

  # Create fail2ban config
  cat >/etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = auto

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600

[nginx-http-auth]
enabled = true
filter = nginx-http-auth
port = http,https
logpath = /var/log/nginx/error.log
maxretry = 3
bantime = 3600
EOF

  # Restart fail2ban
  systemctl restart fail2ban
  systemctl enable fail2ban

  log_success "fail2ban configured and enabled"
}

# Create security monitoring script
create_security_monitor() {
  log_info "Creating security monitoring script..."

  cat >"$PROJECT_ROOT/scripts/ops/security-monitor.sh" <<'EOF'
#!/bin/bash
# Security monitoring script for n8n-cursor VPS
# Run this periodically to check security status

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$PROJECT_ROOT/scripts/utils/lib.sh"

log_info "Running security health check..."

# Check SSH status
echo "=== SSH Security Status ==="
echo "SSH service: $(systemctl is-active ssh)"
echo "SSH config permissions: $(ls -la /etc/ssh/sshd_config | awk '{print $1, $3, $4}')"
echo "Root login allowed: $(grep -i "PermitRootLogin" /etc/ssh/sshd_config | grep -v "^#" | awk '{print $2}')"
echo "Password auth: $(grep -i "PasswordAuthentication" /etc/ssh/sshd_config | grep -v "^#" | awk '{print $2}')"

# Check UFW status
echo -e "\n=== Firewall Status ==="
ufw status verbose

# Check fail2ban status
echo -e "\n=== Fail2ban Status ==="
fail2ban-client status

# Check for suspicious activity
echo -e "\n=== Recent SSH Attempts ==="
grep "sshd" /var/log/auth.log | tail -10

# Check disk space
echo -e "\n=== Disk Space ==="
df -h /

# Check running services
echo -e "\n=== Running Services ==="
systemctl list-units --type=service --state=running | grep -E "(ssh|nginx|docker|fail2ban)"

log_success "Security check completed"
EOF

  chmod +x "$PROJECT_ROOT/scripts/ops/security-monitor.sh"
  log_success "Security monitoring script created"
}

# Main execution
main() {
  log_info "Starting SSH hardening and security setup..."

  check_root
  backup_ssh_config
  harden_ssh
  configure_ufw
  configure_fail2ban
  create_security_monitor

  log_success "SSH hardening completed successfully!"
  log_warn "IMPORTANT: Test SSH connection in another terminal before closing this one!"
  log_info "Run: ssh -v your-user@your-server to test"
  log_info "If connection fails, restore backup: cp $SSH_CONFIG_BACKUP $SSH_CONFIG"

  echo ""
  echo "Next steps:"
  echo "1. Test SSH connection in another terminal"
  echo "2. Run: $PROJECT_ROOT/scripts/ops/security-monitor.sh"
  echo "3. Add to crontab: 0 */6 * * * $PROJECT_ROOT/scripts/ops/security-monitor.sh"
  echo "4. Review logs: tail -f /var/log/auth.log"
}

# Run main function
main "$@"
