// LightningFlow AI Contracts - Feature Flag Types
// Generated from contracts/flags.schema.json by packages/contracts/scripts/generate-flags.js
// Do not edit by hand.

export type FlagValue = boolean | number | string | string[];

export type FlagType = 'boolean' | 'integer' | 'string' | 'array';

export interface FlagConfig {
  type: FlagType;
  default: FlagValue;
  description: string;
  environments?: {
    int?: FlagValue;
    staging?: FlagValue;
    prod?: FlagValue;
  };
  sunsetOn?: string;
}

export interface FeatureFlags {
  NEW_DASHBOARD: boolean;
  BITCOIN_LIGHTNING_INTEGRATION: boolean;
  LNbits_WEBHOOK_VALIDATION: boolean;
  AGENT_AUTO_SCALING: boolean;
  MAX_CONCURRENT_AGENTS: number;
  AGENT_TIMEOUT_MS: number;
  ENABLE_METRICS_COLLECTION: boolean;
  METRICS_RETENTION_DAYS: number;
  ENABLE_DEBUG_LOGGING: boolean;
  LOG_LEVEL: 'debug' | 'info' | 'warn' | 'error';
  ENABLE_RATE_LIMITING: boolean;
  RATE_LIMIT_REQUESTS_PER_MINUTE: number;
  ENABLE_CORS: boolean;
  CORS_ORIGINS: string[];
  ENABLE_WEBHOOK_RETRY: boolean;
  WEBHOOK_MAX_RETRIES: number;
  WEBHOOK_RETRY_DELAY_MS: number;
  ENABLE_DATABASE_POOLING: boolean;
  DATABASE_POOL_SIZE: number;
  ENABLE_REDIS_CACHING: boolean;
  REDIS_CACHE_TTL_SECONDS: number;
  ENABLE_SECURITY_HEADERS: boolean;
  ENABLE_CSRF_PROTECTION: boolean;
  ENABLE_SQL_INJECTION_PROTECTION: boolean;
  ENABLE_XSS_PROTECTION: boolean;
  ENABLE_CONTENT_SECURITY_POLICY: boolean;
  ENABLE_STRICT_TRANSPORT_SECURITY: boolean;
  ENABLE_AGENT_MONITORING: boolean;
  AGENT_HEALTH_CHECK_INTERVAL_MS: number;
  ENABLE_AGENT_AUTO_RECOVERY: boolean;
  AGENT_MAX_FAILURES: number;
  ENABLE_BITCOIN_PRICE_TRACKING: boolean;
  BITCOIN_PRICE_UPDATE_INTERVAL_MS: number;
  ENABLE_LIGHTNING_NETWORK_MONITORING: boolean;
  LIGHTNING_NETWORK_CHECK_INTERVAL_MS: number;
  ENABLE_WORKFLOWS: boolean;
  MAX_CONCURRENT_WORKFLOWS: number;
  WORKFLOW_TIMEOUT_MS: number;
  WORKFLOW_QUEUE_BACKPRESSURE_LIMIT: number;
}

export const flagDefaults: FeatureFlags = {
  NEW_DASHBOARD: false,
  BITCOIN_LIGHTNING_INTEGRATION: true,
  LNbits_WEBHOOK_VALIDATION: true,
  AGENT_AUTO_SCALING: false,
  MAX_CONCURRENT_AGENTS: 10,
  AGENT_TIMEOUT_MS: 30000,
  ENABLE_METRICS_COLLECTION: true,
  METRICS_RETENTION_DAYS: 30,
  ENABLE_DEBUG_LOGGING: false,
  LOG_LEVEL: 'info',
  ENABLE_RATE_LIMITING: true,
  RATE_LIMIT_REQUESTS_PER_MINUTE: 100,
  ENABLE_CORS: true,
  CORS_ORIGINS: ['https://lightningflow.online'],
  ENABLE_WEBHOOK_RETRY: true,
  WEBHOOK_MAX_RETRIES: 3,
  WEBHOOK_RETRY_DELAY_MS: 5000,
  ENABLE_DATABASE_POOLING: true,
  DATABASE_POOL_SIZE: 10,
  ENABLE_REDIS_CACHING: true,
  REDIS_CACHE_TTL_SECONDS: 3600,
  ENABLE_SECURITY_HEADERS: true,
  ENABLE_CSRF_PROTECTION: true,
  ENABLE_SQL_INJECTION_PROTECTION: true,
  ENABLE_XSS_PROTECTION: true,
  ENABLE_CONTENT_SECURITY_POLICY: true,
  ENABLE_STRICT_TRANSPORT_SECURITY: true,
  ENABLE_AGENT_MONITORING: true,
  AGENT_HEALTH_CHECK_INTERVAL_MS: 30000,
  ENABLE_AGENT_AUTO_RECOVERY: true,
  AGENT_MAX_FAILURES: 5,
  ENABLE_BITCOIN_PRICE_TRACKING: true,
  BITCOIN_PRICE_UPDATE_INTERVAL_MS: 60000,
  ENABLE_LIGHTNING_NETWORK_MONITORING: true,
  LIGHTNING_NETWORK_CHECK_INTERVAL_MS: 30000,
  ENABLE_WORKFLOWS: true,
  MAX_CONCURRENT_WORKFLOWS: 6,
  WORKFLOW_TIMEOUT_MS: 300000,
  WORKFLOW_QUEUE_BACKPRESSURE_LIMIT: 3000,
};
