// LightningFlow AI OpenAPI Types
// Generated from contracts/openapi.yaml

// This file will be generated by openapi-typescript
// For now, we'll define the essential types manually

export interface User {
  id: string;
  email: string;
  full_name?: string;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  subscription_tier: 'free' | 'pro' | 'enterprise';
  node_pubkey?: string;
  node_alias?: string;
  timezone: string;
  theme: 'light' | 'dark' | 'auto';
}

export interface Payment {
  id: string;
  amount_sats: number;
  description: string;
  status: 'pending' | 'completed' | 'failed' | 'cancelled';
  created_at: string;
  updated_at: string;
  completed_at?: string;
  payment_hash?: string;
  recipient?: string;
  metadata?: Record<string, any>;
}

export interface LNbitsWebhook {
  type: 'payment_received' | 'payment_sent' | 'invoice_created' | 'invoice_paid';
  data: {
    payment_hash: string;
    amount: number;
    description?: string;
    timestamp: string;
    wallet_id: string;
    user_id: string;
  };
}

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
  has_next: boolean;
  has_prev: boolean;
}

export interface Error {
  code: string;
  message: string;
  details?: Record<string, any>;
  timestamp: string;
}

// API Response types
export interface HealthCheckResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  timestamp: string;
  version: string;
  services: Record<string, {
    status: 'healthy' | 'degraded' | 'unhealthy';
    response_time_ms: number;
  }>;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  user: User;
}

export interface UpdateUserRequest {
  full_name?: string;
  avatar_url?: string;
  timezone?: string;
  theme?: 'light' | 'dark' | 'auto';
}

export interface ListPaymentsRequest {
  page?: number;
  limit?: number;
  status?: 'pending' | 'completed' | 'failed' | 'cancelled';
  from_date?: string;
  to_date?: string;
}

export interface ListPaymentsResponse {
  data: Payment[];
  pagination: Pagination;
}

export interface CreatePaymentRequest {
  amount_sats: number;
  description: string;
  recipient?: string;
  metadata?: Record<string, any>;
}

export interface WebhookResponse {
  status: 'processed' | 'ignored';
  message: string;
}

// HTTP Status codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
} as const;

// API endpoints
export const API_ENDPOINTS = {
  HEALTH: '/healthz',
  LOGIN: '/auth/login',
  USER_ME: '/users/me',
  PAYMENTS: '/payments',
  PAYMENT_BY_ID: (id: string) => `/payments/${id}`,
  WEBHOOK_LNBITS: '/webhooks/lnbits'
} as const;

// API versions
export const API_VERSION = 'v1' as const;

// Base URL configuration
export interface ApiConfig {
  baseUrl: string;
  version: string;
  timeout: number;
}

export const defaultApiConfig: ApiConfig = {
  baseUrl: 'https://evenslouis.ca/lightningflow/api',
  version: API_VERSION,
  timeout: 30000
};

// Request/Response helpers
export interface ApiRequest<T = any> {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  path: string;
  headers?: Record<string, string>;
  body?: T;
  query?: Record<string, string | number | boolean>;
}

export interface ApiResponse<T = any> {
  data?: T;
  error?: Error;
  status: number;
  headers: Record<string, string>;
}

// Validation helpers
export function validateUser(user: any): user is User {
  return (
    typeof user === 'object' &&
    typeof user.id === 'string' &&
    typeof user.email === 'string' &&
    typeof user.created_at === 'string' &&
    typeof user.updated_at === 'string' &&
    ['free', 'pro', 'enterprise'].includes(user.subscription_tier) &&
    ['light', 'dark', 'auto'].includes(user.theme)
  );
}

export function validatePayment(payment: any): payment is Payment {
  return (
    typeof payment === 'object' &&
    typeof payment.id === 'string' &&
    typeof payment.amount_sats === 'number' &&
    typeof payment.description === 'string' &&
    ['pending', 'completed', 'failed', 'cancelled'].includes(payment.status) &&
    typeof payment.created_at === 'string' &&
    typeof payment.updated_at === 'string'
  );
}

export function validatePagination(pagination: any): pagination is Pagination {
  return (
    typeof pagination === 'object' &&
    typeof pagination.page === 'number' &&
    typeof pagination.limit === 'number' &&
    typeof pagination.total === 'number' &&
    typeof pagination.total_pages === 'number' &&
    typeof pagination.has_next === 'boolean' &&
    typeof pagination.has_prev === 'boolean'
  );
}

// Type guards
export function isErrorResponse(response: any): response is { error: Error } {
  return response && typeof response.error === 'object' && typeof response.error.code === 'string';
}

export function isSuccessResponse<T>(response: any): response is { data: T } {
  return response && typeof response.data !== 'undefined' && !response.error;
}

// Export all types
export type {
  User,
  Payment,
  LNbitsWebhook,
  Pagination,
  Error,
  HealthCheckResponse,
  LoginRequest,
  LoginResponse,
  UpdateUserRequest,
  ListPaymentsRequest,
  ListPaymentsResponse,
  CreatePaymentRequest,
  WebhookResponse,
  ApiConfig,
  ApiRequest,
  ApiResponse
};








