name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: ["evenslouis"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: e.g. 1.0.0

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Local Development
        - Integration
        - Testing
        - Staging
        - Production
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include any relevant log snippets and/or screenshots
      placeholder: Paste logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: Any other details...
