#!/bin/bash

# test_agent_factory.sh
# This script runs tests to verify the Agent Factory system is working correctly

# Display banner
echo "================================================="
echo "           AGENT FACTORY TEST SUITE              "
echo "================================================="
echo "Running tests for Agent Factory..."
echo ""

# Set working directory to project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

# Check if .env file exists and load it
if [ ! -f .env ]; then
    echo "Error: .env file not found. Please run ./scripts/start-all.sh first."
    exit 1
fi

# Source environment variables
set -a
source .env
set +a

# Check if n8n is running
echo "Checking if n8n is running..."
if ! curl -s "$N8N_URL" > /dev/null; then
    echo "Error: n8n is not running at $N8N_URL"
    echo "Please run ./scripts/start-all.sh first."
    exit 1
fi
echo "✓ n8n is running at $N8N_URL"

# Check if agent output directory exists
echo "Checking if agent output directory exists..."
if [ ! -d "$AGENT_OUTPUT_DIR" ]; then
    echo "Creating agent output directory: $AGENT_OUTPUT_DIR"
    mkdir -p "$AGENT_OUTPUT_DIR"
fi
echo "✓ Agent output directory exists: $AGENT_OUTPUT_DIR"

# Check if workflow files exist
echo "Checking if workflow files exist..."
if [ ! -d "n8n-workflows" ] || [ ! "$(ls -A n8n-workflows)" ]; then
    echo "Error: No workflow files found in n8n-workflows directory."
    exit 1
fi
echo "✓ Workflow files found in n8n-workflows directory"

# Check if template files exist
echo "Checking if template files exist..."
if [ ! -d "templates" ] || [ ! "$(ls -A templates)" ]; then
    echo "Error: No template files found in templates directory."
    exit 1
fi
echo "✓ Template files found in templates directory"

# Create a simple test agent
echo "Testing agent generation..."
TEST_AGENT_NAME="test_agent_$(date +%s)"
TEST_AGENT_FILE="$AGENT_OUTPUT_DIR/$TEST_AGENT_NAME.py"

# Check if we can write to the output directory
if ! touch "$TEST_AGENT_FILE" 2>/dev/null; then
    echo "Error: Cannot write to $AGENT_OUTPUT_DIR"
    exit 1
fi

# Write a simple test agent
cat > "$TEST_AGENT_FILE" << EOF
# This is a test agent generated by test_agent_factory.sh
import os
import sys

def main():
    print("Test agent is working!")
    print(f"Agent name: $TEST_AGENT_NAME")
    return True

if __name__ == "__main__":
    main()
EOF

echo "✓ Successfully created test agent: $TEST_AGENT_FILE"

# Test if the agent is executable
echo "Testing if the agent is executable..."
if ! python "$TEST_AGENT_FILE"; then
    echo "Error: Test agent failed to execute."
    exit 1
fi
echo "✓ Test agent executed successfully"

# Clean up test agent
echo "Cleaning up test agent..."
rm "$TEST_AGENT_FILE"
echo "✓ Test agent removed"

# All tests passed
echo ""
echo "✓ All tests passed! The Agent Factory system is working correctly."
echo "=================================================" 