#!/bin/bash

# Lightning AI Platform - Codex Hardening Pack v1
# Implements senior-level improvements and generates GitHub issues

set -e

PACK_VERSION="v1.0.0"
GITHUB_REPO="lightning-platform"
ISSUES_DIR="docs/github-issues"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${BLUE}🚀 Lightning AI Platform - Codex Hardening Pack ${PACK_VERSION}${NC}"
echo "=================================================================="

# Create issues directory
mkdir -p "$ISSUES_DIR"

# Function to create GitHub issue
create_github_issue() {
    local title="$1"
    local body="$2"
    local labels="$3"
    local priority="$4"
    
    local filename="${ISSUES_DIR}/$(echo "$title" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g').md"
    
    cat > "$filename" << EOF
---
title: "$title"
labels: [$labels]
priority: $priority
created: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
pack_version: $PACK_VERSION
---

# $title

$body

## Acceptance Criteria

- [ ] Implementation complete
- [ ] Tests added
- [ ] Documentation updated
- [ ] Code review passed

## Related Files

<!-- List relevant files here -->

## Implementation Notes

<!-- Add implementation details here -->

---
*Generated by Codex Hardening Pack $PACK_VERSION*
EOF

    echo -e "${GREEN}✅ Created issue: $title${NC}"
}

# 1. COLD BASE HARDENING
echo -e "\n${PURPLE}🧊 1. COLD BASE HARDENING${NC}"
echo "----------------------------------------"

# TypeScript Strict Mode
create_github_issue \
    "Enforce TypeScript Strict Mode" \
    "## Description
Enable strict TypeScript compilation to catch more errors at build time.

## Tasks
- [ ] Update tsconfig.json with strict: true
- [ ] Enable noImplicitAny
- [ ] Enable exactOptionalPropertyTypes
- [ ] Fix all resulting TypeScript errors
- [ ] Add type checking to CI/CD pipeline

## Benefits
- Catch more bugs at compile time
- Improve code quality and maintainability
- Better IDE support and autocomplete" \
    "enhancement, typescript, infrastructure" \
    "high"

# Mock Isolation
create_github_issue \
    "Isolate Mock Logic from Production" \
    "## Description
Ensure mock logic never deploys to production by wrapping in environment checks.

## Tasks
- [ ] Wrap all mock logic in process.env.NODE_ENV === 'development' checks
- [ ] Remove runtime mock switches
- [ ] Add build-time validation to prevent mock code in production
- [ ] Update deployment scripts to verify no mock code

## Implementation
\`\`\`typescript
// Good
if (process.env.NODE_ENV === 'development' && useMock) {
  return mockLightningService();
}

// Bad
if (useMock) {
  return mockLightningService();
}
\`\`\`" \
    "security, infrastructure, mock" \
    "high"

# Agent Execution Validation
create_github_issue \
    "Add Schema Validation for Agent Execution" \
    "## Description
All signAndExecute() calls must validate payload and executor schemas.

## Tasks
- [ ] Create Zod schemas for all agent payloads
- [ ] Add schema validation to signAndExecute function
- [ ] Implement fail-fast validation
- [ ] Add validation tests
- [ ] Update agent documentation

## Schema Example
\`\`\`typescript
const PaymentAgentSchema = z.object({
  amount: z.number().positive(),
  destination: z.string().min(1),
  memo: z.string().optional()
});
\`\`\`" \
    "security, validation, agents" \
    "high"

# 2. UI & UX IMPROVEMENTS
echo -e "\n${PURPLE}🧭 2. UI & UX IMPROVEMENTS${NC}"
echo "----------------------------------------"

# Onboarding Animation
create_github_issue \
    "Implement Animated Onboarding Flow" \
    "## Description
Create seamless first-run onboarding with framer-motion animations.

## Tasks
- [ ] Design onboarding flow wireframes
- [ ] Implement step-by-step animations
- [ ] Add progress indicators
- [ ] Create smooth transitions between steps
- [ ] Add skip/back navigation
- [ ] Test on mobile devices

## Steps
1. Welcome & account creation
2. Workspace naming
3. Node setup (mock/live)
4. First test invoice
5. Lightning method setup
6. Earning preferences

## Animation Requirements
- Smooth page transitions (300ms)
- Progress bar animation
- Card flip animations for steps
- Celebration animation on completion" \
    "enhancement, ui/ux, onboarding" \
    "medium"

# Button Feedback System
create_github_issue \
    "Implement Universal Button Feedback System" \
    "## Description
Every button needs tooltip, confirmation feedback, and state management.

## Tasks
- [ ] Update all buttons to use SignedButton component
- [ ] Add tooltips to all interactive elements
- [ ] Implement confirmation feedback (✅ Sent, ⚠️ Retry, 🔐 Signed)
- [ ] Add loading states with progress indicators
- [ ] Create button state management hook

## Button States
- Idle: Default state with tooltip
- Loading: Spinner with progress bar
- Success: Green checkmark with animation
- Error: Red X with error message
- Confirmation: Lock icon with confirmation dialog" \
    "enhancement, ui/ux, components" \
    "medium"

# Contextual Sidebar
create_github_issue \
    "Create Contextual Collapsible Sidebar" \
    "## Description
Sidebar should adapt based on user role and workspace context.

## Tasks
- [ ] Design contextual navigation system
- [ ] Implement collapsible sidebar with animations
- [ ] Add workspace switcher
- [ ] Create role-based navigation
- [ ] Add keyboard shortcuts
- [ ] Implement mobile-responsive design

## Context Types
- Solo user: Basic navigation
- Agent owner: Agent management tools
- Developer: Debug and testing tools
- Team admin: Team management options" \
    "enhancement, ui/ux, navigation" \
    "medium"

# 3. SECURITY & TRUST
echo -e "\n${PURPLE}🔐 3. SECURITY & TRUST${NC}"
echo "----------------------------------------"

# Multi-signature Support
create_github_issue \
    "Implement Multi-signature for High-Value Actions" \
    "## Description
Add multi-signature support for large payments and critical operations.

## Tasks
- [ ] Design multi-sig workflow
- [ ] Implement signature collection system
- [ ] Add threshold configuration
- [ ] Create approval interface
- [ ] Add notification system for pending signatures
- [ ] Implement timeout handling

## Thresholds
- Payments > 1 BTC: Require 2/3 signatures
- Channel operations: Require 2/2 signatures
- System config changes: Require 3/5 signatures" \
    "security, cryptography, payments" \
    "high"

# Signature Expiration
create_github_issue \
    "Add Signature Expiration Windows" \
    "## Description
Implement time-based signature expiration for security.

## Tasks
- [ ] Add timestamp validation to signatures
- [ ] Implement configurable expiration windows
- [ ] Add automatic cleanup of expired signatures
- [ ] Create renewal mechanism for long-running operations
- [ ] Add expiration warnings in UI

## Expiration Times
- Payment signatures: 5 minutes
- Agent execution: 1 hour
- System config: 24 hours" \
    "security, cryptography, validation" \
    "high"

# Hardware Wallet Integration
create_github_issue \
    "Integrate Hardware Wallets for Cold Signing" \
    "## Description
Support hardware wallets for signing high-value actions.

## Tasks
- [ ] Research hardware wallet APIs (Ledger, Trezor)
- [ ] Implement WebUSB/WebHID integration
- [ ] Create hardware wallet detection
- [ ] Add cold signing workflow
- [ ] Implement fallback mechanisms
- [ ] Add hardware wallet setup guide

## Supported Devices
- Ledger Nano S/X
- Trezor Model T
- BitBox02" \
    "security, hardware, integration" \
    "low"

# 4. TESTING & OBSERVABILITY
echo -e "\n${PURPLE}🧪 4. TESTING & OBSERVABILITY${NC}"
echo "----------------------------------------"

# Comprehensive E2E Tests
create_github_issue \
    "Expand E2E Test Coverage" \
    "## Description
Create comprehensive end-to-end tests for all critical flows.

## Tasks
- [ ] Add onboarding flow tests
- [ ] Test payment creation and execution
- [ ] Add agent installation and execution tests
- [ ] Test multi-user scenarios
- [ ] Add mobile device testing
- [ ] Implement visual regression testing

## Test Scenarios
- New user onboarding
- Payment flows (send/receive)
- Agent marketplace
- Team collaboration
- Error handling
- Performance under load" \
    "testing, e2e, quality" \
    "high"

# Logging System
create_github_issue \
    "Implement Structured Logging with Logflare" \
    "## Description
Add comprehensive logging for debugging and monitoring.

## Tasks
- [ ] Install and configure Logflare
- [ ] Implement structured logging with pino
- [ ] Add log levels and filtering
- [ ] Create log aggregation dashboard
- [ ] Add error tracking and alerting
- [ ] Implement log retention policies

## Log Categories
- User actions
- Payment operations
- Agent executions
- System errors
- Performance metrics" \
    "observability, logging, monitoring" \
    "medium"

# Bundle Analysis
create_github_issue \
    "Implement Bundle Size Monitoring" \
    "## Description
Monitor and optimize bundle sizes for performance.

## Tasks
- [ ] Add bundle analyzer to build process
- [ ] Set up bundle size monitoring
- [ ] Create size budgets and alerts
- [ ] Implement code splitting strategies
- [ ] Add performance monitoring
- [ ] Create optimization guidelines

## Size Targets
- Initial bundle: < 200KB gzipped
- Route chunks: < 50KB gzipped
- Vendor chunks: < 100KB gzipped" \
    "performance, optimization, monitoring" \
    "medium"

# 5. BUSINESS & MONETIZATION
echo -e "\n${PURPLE}💰 5. BUSINESS & MONETIZATION${NC}"
echo "----------------------------------------"

# Usage-based Pricing
create_github_issue \
    "Implement Usage-based Pricing Tiers" \
    "## Description
Add flexible pricing based on usage metrics.

## Tasks
- [ ] Design usage tracking system
- [ ] Implement API credit system
- [ ] Add automation time tracking
- [ ] Create billing integration
- [ ] Add usage dashboards
- [ ] Implement upgrade flows

## Pricing Tiers
- Free: 100 API calls/month
- Starter: $19/month, 10K API calls
- Pro: $99/month, 100K API calls
- Enterprise: Custom pricing" \
    "business, pricing, billing" \
    "medium"

# Enterprise Features
create_github_issue \
    "Develop Enterprise & Government Features" \
    "## Description
Create enterprise-grade features for large organizations.

## Tasks
- [ ] Add encrypted audit trail exports
- [ ] Implement offline mode
- [ ] Create team management system
- [ ] Add SSO integration
- [ ] Implement compliance reporting
- [ ] Create enterprise onboarding

## Features
- Audit trail exports (CSV, JSON)
- Offline operation mode
- Team seat management
- SSO (SAML, OAuth)
- Compliance dashboards" \
    "business, enterprise, compliance" \
    "low"

# 6. DEVELOPER EXPERIENCE
echo -e "\n${PURPLE}🛠️ 6. DEVELOPER EXPERIENCE${NC}"
echo "----------------------------------------"

# Agent SDK
create_github_issue \
    "Create Agent Development SDK" \
    "## Description
Provide tools for third-party agent development.

## Tasks
- [ ] Design agent API specification
- [ ] Create agent scaffolding CLI
- [ ] Implement MCP schema validation
- [ ] Add agent testing framework
- [ ] Create documentation and examples
- [ ] Implement agent marketplace

## CLI Commands
- \`lightning-agent create <name>\`
- \`lightning-agent test\`
- \`lightning-agent publish\`
- \`lightning-agent validate\`" \
    "developer-experience, sdk, agents" \
    "medium"

# CI/CD Pipeline
create_github_issue \
    "Implement Comprehensive CI/CD Pipeline" \
    "## Description
Create automated testing and deployment pipeline.

## Tasks
- [ ] Set up GitHub Actions workflows
- [ ] Add automated testing (unit, integration, e2e)
- [ ] Implement code quality checks
- [ ] Add security scanning
- [ ] Create deployment automation
- [ ] Add rollback mechanisms

## Pipeline Stages
1. Code quality (lint, format, type check)
2. Unit tests
3. Integration tests
4. E2E tests
5. Security scan
6. Build and deploy" \
    "infrastructure, ci/cd, automation" \
    "high"

# Summary
echo -e "\n${BLUE}📋 Hardening Pack Summary${NC}"
echo "=================================================================="

issue_count=$(find "$ISSUES_DIR" -name "*.md" | wc -l)
echo -e "${GREEN}✅ Generated $issue_count GitHub issues${NC}"
echo -e "${CYAN}📁 Issues saved to: $ISSUES_DIR${NC}"

echo -e "\n${YELLOW}🎯 Priority Implementation Order:${NC}"
echo "1. 🔐 Security hardening (TypeScript strict, mock isolation)"
echo "2. 🧪 Testing infrastructure (E2E tests, logging)"
echo "3. 🧭 UX improvements (onboarding, button feedback)"
echo "4. 💰 Business features (pricing, enterprise)"
echo "5. 🛠️ Developer tools (SDK, CI/CD)"

echo -e "\n${BLUE}🚀 Next Steps:${NC}"
echo "1. Review generated issues in $ISSUES_DIR"
echo "2. Import issues to GitHub repository"
echo "3. Prioritize based on business needs"
echo "4. Start implementation with security hardening"

echo -e "\n${GREEN}🎉 Codex Hardening Pack $PACK_VERSION complete!${NC}"
echo -e "${GREEN}Your Lightning AI Platform is ready for enterprise scale!${NC}" 