import { NextRequest, NextResponse } from 'next/server';
import { getRAGStore } from '@/lib/shared-stores';
import { withErrorHandling, createSuccessResponse, createErrorResponse, ApiErrorCode, validateRequest } from '@/lib/api-error-handler';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

const bundleSchema = z.object({
  bundleId: z.string(),
  title: z.string(),
  itemIds: z.array(z.string()).min(1)
});

/**
 * POST /api/knowledge/bundle - Generate a PDF bundle from knowledge items
 * Returns HTML content that can be converted to PDF
 */
export const POST = withErrorHandling(async (request: NextRequest) => {
  const validation = await validateRequest(request, bundleSchema);
  if (!validation.success) {
    return validation.error;
  }
  
  const { bundleId, title, itemIds } = validation.data;
  
  try {
    const store = await getRAGStore();
    const allKnowledge = store.getAllKnowledge();
    
    // Get all items in the bundle
    const bundleItems = itemIds
      .map(id => allKnowledge.find(k => k.id === id))
      .filter(Boolean) as typeof allKnowledge;
    
    if (bundleItems.length === 0) {
      return createErrorResponse(
        ApiErrorCode.NOT_FOUND,
        'No knowledge items found for bundle',
        undefined,
        404
      );
    }
    
    // Generate HTML content for the bundle
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
      border-bottom: 2px solid #ecf0f1;
      padding-bottom: 5px;
    }
    .item {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .metadata {
      font-size: 0.9em;
      color: #7f8c8d;
      margin-bottom: 10px;
    }
    .content {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      border-left: 4px solid #3498db;
    }
    pre {
      background: #2c3e50;
      color: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
    }
    code {
      font-family: 'Courier New', monospace;
    }
    @media print {
      body { margin: 0; padding: 10px; }
      .item { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p><em>Generated on ${new Date().toLocaleString()}</em></p>
  <p><em>${bundleItems.length} knowledge item(s)</em></p>
  
  ${bundleItems.map((item, idx) => `
    <div class="item">
      <h2>${idx + 1}. ${item.title || item.id}</h2>
      <div class="metadata">
        <strong>Source:</strong> ${item.source || 'Unknown'}<br>
        <strong>Type:</strong> ${item.type || 'Unknown'}<br>
        <strong>Category:</strong> ${item.category || 'Unknown'}<br>
        ${item.extractedAt ? `<strong>Extracted:</strong> ${new Date(item.extractedAt).toLocaleString()}<br>` : ''}
      </div>
      <div class="content">
        ${item.description ? `<p>${item.description.replace(/\n/g, '</p><p>')}</p>` : ''}
        ${(item as any).codeSnippets && (item as any).codeSnippets.length > 0 ? `
          <h3>Code Snippets:</h3>
          ${(item as any).codeSnippets.map((snippet: any) => `
            <div style="margin-bottom: 20px;">
              <strong>File:</strong> ${snippet.file}<br>
              <strong>Language:</strong> ${snippet.language}<br>
              ${snippet.explanation ? `<p><em>${snippet.explanation}</em></p>` : ''}
              <pre><code>${snippet.code}</code></pre>
            </div>
          `).join('')}
        ` : ''}
      </div>
    </div>
  `).join('')}
  
  <hr style="margin-top: 40px;">
  <p style="text-align: center; color: #7f8c8d; font-size: 0.9em;">
    Generated by Scorpion Knowledge Base
  </p>
</body>
</html>
    `.trim();
    
    return createSuccessResponse({
      bundleId,
      title,
      itemCount: bundleItems.length,
      htmlContent,
      // Also provide markdown version for alternative export
      markdownContent: `# ${title}\n\n*Generated on ${new Date().toLocaleString()}*\n\n*${bundleItems.length} knowledge item(s)*\n\n${bundleItems.map((item, idx) => `
## ${idx + 1}. ${item.title || item.id}

**Source:** ${item.source || 'Unknown'}  
**Type:** ${item.type || 'Unknown'}  
**Category:** ${item.category || 'Unknown'}  
${item.extractedAt ? `**Extracted:** ${new Date(item.extractedAt).toLocaleString()}\n` : ''}

${item.description || ''}

${(item as any).codeSnippets && (item as any).codeSnippets.length > 0 ? `
### Code Snippets

${(item as any).codeSnippets.map((snippet: any) => `
**File:** \`${snippet.file}\`  
**Language:** ${snippet.language}  
${snippet.explanation ? `*${snippet.explanation}*\n` : ''}

\`\`\`${snippet.language}
${snippet.code}
\`\`\`
`).join('\n')}
` : ''}
`).join('\n\n---\n\n')}
      `
    });
  } catch (error: any) {
    console.error('[Knowledge Bundle API] Failed to generate bundle:', error);
    return createErrorResponse(
      ApiErrorCode.INTERNAL_ERROR,
      `Failed to generate bundle: ${error.message}`,
      undefined,
      500
    );
  }
});

