#!/usr/bin/env python3
"""Persona wrap: Sir, no blame, no waiting-for, no invented again."""
from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent / "persona.py"


def _load():
    spec = importlib.util.spec_from_file_location("agent_stack_persona", SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {SCRIPT}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


MOD = _load()


class PersonaWrapTest(unittest.TestCase):
    def test_wrap_addresses_sir_then_payload(self) -> None:
        out = MOD.wrap("Vault and hive are on the table.", verb="converse", utterance="what's going on")
        self.assertTrue(out.startswith("Sir."))
        self.assertIn("Vault and hive are on the table.", out)
        self.assertNotIn("waiting for", out.lower())

    def test_failure_never_takes_blame(self) -> None:
        out = MOD.wrap("UNKNOWN. Cursor harness returned no reply.", verb="converse")
        self.assertIn("Naturally, it isn't my fault, sir", out)
        self.assertIn("UNKNOWN. Cursor harness returned no reply.", out)
        self.assertNotIn("I'm sorry", out)
        self.assertNotIn("I failed", out)
        self.assertNotIn("waiting for", out.lower())

    def test_strips_waiting_for_and_blame(self) -> None:
        raw = "I am sorry. Waiting for the harness. The repo has three apps."
        out = MOD.wrap(raw, verb="cursor", utterance="check my repo")
        self.assertTrue(out.startswith("Sir."))
        self.assertIn("The repo has three apps.", out)
        self.assertNotIn("waiting for", out.lower())
        self.assertNotIn("I am sorry", out)
        self.assertNotIn("I'm sorry", out)

    def test_safari_wrap_is_conversation_not_router(self) -> None:
        out = MOD.wrap(
            "You asked to open YouTube. Safari opened https://www.youtube.com.",
            verb="safari",
            utterance="Hi Jarvis open YouTube",
        )
        self.assertTrue(out.startswith("Sir."))
        self.assertIn("The tab, not the face.", out)
        self.assertIn("You asked to open YouTube", out)
        self.assertIn("https://www.youtube.com", out)
        self.assertNotIn("as requested", out.lower())
        self.assertNotIn("127.0.0.1:4018", out)

    def test_no_again_without_history(self) -> None:
        out = MOD.wrap("Clicked Login in Safari.", verb="safari", utterance="click Login")
        self.assertNotIn("again", out.lower())
        self.assertTrue(MOD.wrap("Found 1 local file.", verb="files", utterance="search my computer") )
        self.assertFalse(MOD.proven_repeat("click Login", turns=[], store_lines=[], scars=[]))

    def test_repeat_only_when_sitting_proves_it(self) -> None:
        turns = [{"user": "click Login", "jarvis": "Clicked Login in Safari."}]
        out = MOD.wrap(
            "Clicked Login in Safari.",
            verb="safari",
            utterance="click Login",
            turns=turns,
        )
        self.assertIn("again", out.lower())
        self.assertIn("Clicked Login in Safari.", out)
        fresh = MOD.wrap("Clicked Login in Safari.", verb="safari", utterance="click Login")
        self.assertNotIn("again", fresh.lower())

    def test_does_not_double_wrap(self) -> None:
        once = MOD.wrap("Standing by.", verb="greet")
        twice = MOD.wrap(once, verb="greet")
        self.assertEqual(once.count("Sir."), 1)
        self.assertEqual(twice, once)

    def test_dump_is_not_spoken_as_ask_log(self) -> None:
        dump = (
            "%%generated by scripts/hive/os/ask-log.py — do not hand-edit%% "
            "> [!abstract] Ask log > **709 asks** · 14 sessions"
        )
        out = MOD.wrap(dump, verb="converse", utterance="That's not what I said")
        self.assertNotIn("ask-log.py", out)
        self.assertNotIn("709 asks", out)
        self.assertNotIn("do not hand-edit", out.lower())
        self.assertIn("isn't my fault, sir", out)
        self.assertIn("file dump", out.lower())

    def test_stream_delta_wraps_once_then_payload(self) -> None:
        first = MOD.stream_delta("The mix is segment, then price.", first=True, verb="pro")
        second = MOD.stream_delta("Sir. Do not invent a KPI.", first=False, verb="pro")
        third = MOD.stream_delta(first, first=True, verb="pro")
        self.assertTrue(first.startswith("Sir."))
        self.assertEqual(first.count("Sir."), 1)
        self.assertNotIn("Sir.", second)
        self.assertIn("Do not invent a KPI.", second)
        self.assertEqual(third, first)
        self.assertNotIn("Sir. Sir.", first)

    def test_factory_leaks_are_stripped(self) -> None:
        raw = (
            "path=cgevent safari_act as requested. "
            "CGEvent page keys and Apple Events failed. "
            "Cited CONTENT/os/ASKS.md. Scar cursor-auth-dark already saved. "
            "Screen saved at /tmp/see.jpg. PR #200 PID 4018."
        )
        out = MOD.wrap(raw, verb="safari", utterance="scroll")
        low = out.lower()
        self.assertTrue(out.startswith("Sir."))
        self.assertNotIn("cgevent", low)
        self.assertNotIn("as requested", low)
        self.assertNotIn("safari_act", low)
        self.assertNotIn("apple events", low)
        self.assertNotIn("ask-log", low)
        self.assertNotIn("asks.md", low)
        self.assertNotIn("cursor-auth-dark", low)
        self.assertNotIn("/tmp/see.jpg", low)
        self.assertNotIn("pr #200", low)
        self.assertNotIn("pid 4018", low)

    def test_wire_inspect_keeps_path_when_asked(self) -> None:
        out = MOD.wrap("Last hand: safari. path=cgevent. CGEvent page key dark", verb="wire")
        self.assertTrue(out.startswith("Sir."))
        self.assertIn("path=cgevent", out)
        self.assertIn("CGEvent", out)

    def test_pack_and_asks_are_not_spoken(self) -> None:
        raw = (
            "I heard you: He's Jarvis. Before that you said: stop. "
            "- 22:48 — If you don't know how to build your own agentic OS. "
            "Vault: adopted path missing The store is still on disk."
        )
        out = MOD.wrap(raw, verb="status", utterance="He's Jarvis")
        low = out.lower()
        self.assertNotIn("adopted path missing", low)
        self.assertNotIn("22:48", out)
        self.assertNotIn("agentic os", low)
        self.assertNotIn("i heard you", low)
        self.assertNotIn("before that you said", low)


if __name__ == "__main__":
    unittest.main()
