import { NextRequest, NextResponse } from 'next/server';
import { runCouncil } from '@/server/council';
import { extractDomainTags } from '@/server/council/runCouncil';
import type { CouncilInput, CouncilResult } from '@/server/types/council';

export const dynamic = 'force-dynamic';

type LanguageStyle = 'dev' | 'gamer' | 'spy' | 'normal';
type Period = 'daily' | 'weekly' | 'monthly';

interface ConsolidatedReportRequest {
  period: Period;
  style: LanguageStyle;
  workflows: Array<{
    workflowName: string;
    status: 'success' | 'failure' | 'cancelled';
    branch: string;
    commitSha: string;
    commitMessage: string;
    timestamp: string;
    changedFiles?: string[];
    errorMessages?: string[];
  }>;
}

const LANGUAGE_STYLES: Record<LanguageStyle, {
  greeting: (period: string) => string;
  statusGood: string;
  statusBad: string;
  critical: string;
  high: string;
  medium: string;
  low: string;
  footer: string;
}> = {
  dev: {
    greeting: (p) => `🦂 Consolidated Build Report - ${p.toUpperCase()}\n\nStatus: Analyzing ${p} build performance...`,
    statusGood: '✅ All systems operational. No critical issues detected.',
    statusBad: '⚠️ Issues detected. Review required.',
    critical: '🚨 CRITICAL',
    high: '🔴 HIGH',
    medium: '🟡 MEDIUM',
    low: '🟢 LOW',
    footer: '\n---\nGenerated by Scorpion Council | Review full details in GitHub Actions',
  },
  gamer: {
    greeting: (p) => `🎮 ${p.toUpperCase()} BUILD REPORT - MISSION STATUS\n\nAnalyzing your codebase performance...`,
    statusGood: '🏆 MISSION SUCCESS! All checks passed. Your codebase is in top form!',
    statusBad: '⚠️ MISSION CRITICAL! Issues detected. Time to level up your code!',
    critical: '💀 CRITICAL BOSS',
    high: '⚔️ HIGH THREAT',
    medium: '🛡️ MEDIUM RISK',
    low: '✨ MINOR ISSUE',
    footer: '\n---\n🎯 Keep grinding! - Scorpion Council',
  },
  spy: {
    greeting: (p) => `🕵️ CLASSIFIED: ${p.toUpperCase()} INTELLIGENCE REPORT\n\nAgent Scorpion analyzing target codebase...`,
    statusGood: '✅ TARGET SECURE. No anomalies detected. Operation status: NORMAL.',
    statusBad: '⚠️ ALERT: Anomalies detected. Immediate review required.',
    critical: '🔴 CRITICAL THREAT',
    high: '🟠 HIGH PRIORITY',
    medium: '🟡 MEDIUM RISK',
    low: '🟢 LOW PRIORITY',
    footer: '\n---\nThis message will self-destruct... - Agent Scorpion',
  },
  normal: {
    greeting: (p) => `Build Report - ${p.charAt(0).toUpperCase() + p.slice(1)} Summary\n\n`,
    statusGood: 'All builds passed successfully. No issues to report.',
    statusBad: 'Some issues were detected. Please review the details below.',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    footer: '\n---\nThank you for using Scorpion Council.',
  },
};

function formatConsolidatedContext(
  workflows: ConsolidatedReportRequest['workflows'],
  period: Period
): string {
  const totalWorkflows = workflows.length;
  const successCount = workflows.filter(w => w.status === 'success').length;
  const failCount = workflows.filter(w => w.status === 'failure').length;
  const cancelledCount = workflows.filter(w => w.status === 'cancelled').length;

  const allErrorMessages = workflows.flatMap(w => w.errorMessages || []);
  const allChangedFiles = workflows.flatMap(w => w.changedFiles || []);
  const allText = workflows.map(w => 
    `${w.workflowName} ${w.status} ${w.commitMessage} ${(w.errorMessages || []).join(' ')}`
  ).join(' ').toLowerCase();

  return `
CONSOLIDATED BUILD ANALYSIS - ${period.toUpperCase()} PERIOD

Period Summary:
- Total Workflows: ${totalWorkflows}
- ✅ Successful: ${successCount}
- ❌ Failed: ${failCount}
- ⏸️ Cancelled: ${cancelledCount}
- Success Rate: ${totalWorkflows > 0 ? ((successCount / totalWorkflows) * 100).toFixed(1) : 0}%

Workflows Analyzed:
${workflows.map(w => `  - ${w.workflowName} (${w.status}) - ${w.branch} - ${w.commitSha.substring(0, 7)}`).join('\n')}

Security Analysis:
- Changed files with security concerns: ${allChangedFiles.filter(f => 
    f.includes('.env') || f.includes('secret') || f.includes('auth') || f.includes('api')
  ).length}
- Errors mentioning secrets/auth: ${allErrorMessages.filter(e => 
    /secret|key|token|auth|password|credential/i.test(e)
  ).length}
- SQL/database operations: ${/sql|query|database/i.test(allText) ? 'detected' : 'none'}

Performance Analysis:
- Total failures: ${failCount}
- Error patterns: ${allErrorMessages.length} unique errors
- File changes: ${allChangedFiles.length} files modified
- Build patterns: ${/cache|redis|memoize/i.test(allText) ? 'caching detected' : 'no caching patterns'}
- Blocking operations: ${/synchronous|blocking|sleep|wait/i.test(allText) ? 'detected' : 'none'}

Architecture Analysis:
- Workflow files changed: ${allChangedFiles.filter(f => 
    f.includes('.github/workflows') || f.includes('docker') || f.includes('compose')
  ).length}
- Infrastructure changes: ${/infra|docker|k8s|deploy/i.test(allText) ? 'detected' : 'none'}
- Modular patterns: ${/orchestrator|planner|executor|council/i.test(allText) ? 'mentioned' : 'not mentioned'}

Integration Analysis:
- API/endpoint changes: ${allChangedFiles.filter(f => 
    f.includes('api') || f.includes('route') || f.includes('endpoint')
  ).length}
- n8n workflow changes: ${/n8n|workflow|automation/i.test(allText) ? 'detected' : 'none'}
- Integration patterns: ${/integrate|webhook|service/i.test(allText) ? 'detected' : 'none'}

Error Summary (${allErrorMessages.length} total):
${allErrorMessages.slice(0, 20).map(e => `  - ${e}`).join('\n')}
${allErrorMessages.length > 20 ? `  ... and ${allErrorMessages.length - 20} more errors` : ''}

Key Changed Files:
${allChangedFiles.slice(0, 30).map(f => `  - ${f}`).join('\n')}
${allChangedFiles.length > 30 ? `  ... and ${allChangedFiles.length - 30} more files` : ''}
`.trim();
}

function formatReport(
  councilResult: CouncilResult,
  period: string,
  style: LanguageStyle,
  workflows: ConsolidatedReportRequest['workflows'] = []
): string {
  const lang = LANGUAGE_STYLES[style];
  const summary = councilResult.allIssues?.reduce((acc, issue) => {
    if (issue.severity >= 5) acc.critical++;
    else if (issue.severity >= 4) acc.high++;
    else if (issue.severity >= 3) acc.medium++;
    else acc.low++;
    return acc;
  }, { critical: 0, high: 0, medium: 0, low: 0 }) || { critical: 0, high: 0, medium: 0, low: 0 };

  const totalIssues = councilResult.allIssues?.length || 0;
  const status = totalIssues === 0 ? lang.statusGood : lang.statusBad;

  let report = `${lang.greeting(period)}\n\n`;
  report += `${status}\n\n`;

  if (workflows.length > 0) {
    report += `Workflows Analyzed: ${workflows.length}\n`;
    const successCount = workflows.filter(w => w.status === 'success').length;
    const failCount = workflows.filter(w => w.status === 'failure').length;
    report += `✅ Success: ${successCount} | ❌ Failed: ${failCount}\n\n`;
  }

  if (totalIssues > 0) {
    report += `Issue Breakdown:\n`;
    if (summary.critical > 0) report += `  ${lang.critical}: ${summary.critical}\n`;
    if (summary.high > 0) report += `  ${lang.high}: ${summary.high}\n`;
    if (summary.medium > 0) report += `  ${lang.medium}: ${summary.medium}\n`;
    if (summary.low > 0) report += `  ${lang.low}: ${summary.low}\n`;
    report += `\n`;
  }

  if (councilResult.councillorOutputs) {
    const topMembers = councilResult.councillorOutputs
      .filter(co => co.issues && (co.issues as any[]).length > 0)
      .sort((a, b) => (b.issues as any[]).length - (a.issues as any[]).length)
      .slice(0, 5);

    if (topMembers.length > 0) {
      report += `Key Findings:\n`;
      for (const member of topMembers) {
        const issues = member.issues as any[];
        const topIssue = issues.sort((a, b) => (b.severity || 0) - (a.severity || 0))[0];
        if (topIssue) {
          report += `  • ${member.councillorName}: ${topIssue.message}\n`;
        }
      }
      report += `\n`;
    }
  }

  report += `${lang.footer}\n`;
  return report;
}

export async function POST(req: NextRequest) {
  try {
    const body: ConsolidatedReportRequest = await req.json();
    
    if (!body.period || !body.style || !body.workflows) {
      return NextResponse.json(
        { error: 'Missing required fields: period, style, workflows' },
        { status: 400 }
      );
    }

    // Format consolidated context for council
    const consolidatedContext = formatConsolidatedContext(body.workflows, body.period);

    // Create council input
    const councilInput: CouncilInput = {
      goalDescription: `Consolidated ${body.period} build analysis report`,
      planSummary: consolidatedContext,
      draftAnswer: `Consolidated report for ${body.period} period covering ${body.workflows.length} workflows`,
      domainTags: extractDomainTags(
        `Consolidated ${body.period} report`,
        consolidatedContext
      ).concat(['consolidated-report', body.period, 'build-analysis']),
      toolsUsed: [],
      planSteps: body.workflows.slice(0, 10).map(w => ({
        description: `${w.workflowName} (${w.status})`,
      })),
      userId: 'github-actions',
      conversationId: `consolidated-${body.period}-${Date.now()}`,
      missionId: `consolidated-report-${body.period}-${Date.now()}`,
    };

    // Run council analysis
    const councilResult: CouncilResult = await runCouncil(councilInput);

    // Format report with language style
    const formattedReport = formatReport(councilResult, body.period, body.style, body.workflows);

    return NextResponse.json({
      period: body.period,
      style: body.style,
      report: formattedReport,
      summary: {
        totalIssues: councilResult.allIssues?.length || 0,
        criticalIssues: councilResult.allIssues?.filter(i => i.severity >= 5).length || 0,
        highIssues: councilResult.allIssues?.filter(i => i.severity >= 4).length || 0,
        mediumIssues: councilResult.allIssues?.filter(i => i.severity === 3).length || 0,
        lowIssues: councilResult.allIssues?.filter(i => i.severity <= 2).length || 0,
        overallApproval: councilResult.approved,
      },
      workflowsAnalyzed: body.workflows.length,
      timestamp: new Date().toISOString(),
    }, { status: 200 });
  } catch (error: any) {
    console.error('[Consolidated Report] Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate consolidated report' },
      { status: 500 }
    );
  }
}

