#!/usr/bin/env python3
"""Batch 2: remaining shorts already fully read."""
from _hitl_dvl_writer import write_one

def src(claim, why, mech, ev, act, **kw):
    return {"concept": kw.pop("concept"), "claim": claim, "why": why, "mech": mech, "ev": ev, "act": act, **kw}

def ex(sit, act, why, out, les, name="On-tape run"):
    return {"name": name, "sit": sit, "act": act, "why": why, "out": out, "les": les}

TAKES = {}

TAKES["nQtogLs_dlg"] = {
    "title": "Build ANYTHING with Sonnet 4.5 and n8n AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 450,
    "A": [
        "Sonnet 4.5 released 2025-09-29. Haiku cheap/fast, Sonnet balance, Opus max reasoning. Price same as Sonnet 4 (on-tape).",
        "SWE-Bench 77–82% UNVERIFIED. Finance/medicine/law/STEM: Sonnet 4.5 on top of Claude family (on-tape chart).",
        "Demo: research voice agents via Perplexity, call contact agent, pass to email agent, send to Michael Scott.",
        "He opens the sent email: NLP/TTS/apps/benefits/sign-off from Nate.",
        "CTA to full cut `X80ljdCPM_U`.",
    ],
    "atoms": [src(
        "A multi-agent graph that can call an email agent will send.",
        "Benchmarks are the hook; the irreversible step is the Michael Scott send.",
        "Research agent → contact agent → email agent → sent mail.",
        "On-tape: 'it was able to send this to the correct email for Michael Scott.'",
        "Steal the handoff chain. Operate-never the send.",
        concept="Handoff to an email agent is a send",
        conf="low on benches — UNVERIFIED",
    )],
    "C": ["New model every day is noise; he still demos a send.", "Expert-level advice benches are why he trusts the research step — not a reason to auto-mail."],
    "D": ["Keep research + contact lookup. Strip the email-send tool.", "If a chain can 'pass to the email agent,' that agent is draft-only.", "Claude/Perplexity stay on-tape."],
    "E": [ex("Research voice agents and tell Michael Scott", "Perplexity + contact + email agents", "Show Sonnet 4.5 in a graph", "Email sent with Nate sign-off", "The send is the never")],
    "F": ["If an email agent exists on the canvas → send-removed.", "If benches are quoted → UNVERIFIED.", "If the contact is a real person → PII / send card."],
    "G": ["Field celebrates the send as the demo win. This desk treats the send as the fail."],
    "H": ["77–82% SWE, price parity, 'expert-level' — vendor claims UNVERIFIED.", "Michael Scott / Dunder Mifflin is a joke address — still a send."],
    "I": ["Was the inbox real? Tape shows an email UI.", "Did a human confirm before send? Not shown."],
    "J": ["Long: `X80ljdCPM_U`. MCP send: `mPflFTQUCGk`.", "SYSTEM SYNTHESIS → `send-removed`."],
    "K": ["Multi-agent research handoff without send. Unassigned."],
    "machines": [{
        "name": "Research → contact → draft (email agent has no Send)",
        "loop": "research → resolve contact → draft body → Evens sends → stop",
        "qs": "Who is the recipient? Is Send attached? Did Evens see the body?",
        "qf": "Passing to an 'email agent' is not passing to Evens.",
        "proc": "Delete send tool. Keep Perplexity-class research as on-tape how.",
        "ex": ex("Tell Michael Scott about voice agents", "Chain to email agent", "Show the model", "Mail sent", "Handoff stolen; send rejected"),
        "why": "He proves the chain works by opening the sent mail. That proof is the risk.",
        "never": "Auto-send. Quote SWE % as FACT. Install Sonnet as hive brain.",
        "hive": "`send-removed` · `ask-principal` · `info-gain-cite`",
    }],
    "L": "Any graph with an email agent is a send card. ACTION = REJECT send, keep research draft. Benches UNVERIFIED. Clients parked.",
}

TAKES["xsAOpqjebOo"] = {
    "title": "I Can Actually Watch My AI Agents Work Now",
    "speaker": "on-tape Claude Code operator (Nate-class)",
    "kind": "short",
    "words": 452,
    "A": [
        "Claude Code agents 'running my business' in a visual pane.",
        "Ask main agent to spin up two researchers (Google vs OpenAI) + a diagram. Three agents in parallel; main delegated.",
        "Second terminal: YouTube comment analysis last couple videos → notification → sub-agent needs approval.",
        "Visual idle/done. Diagram of strengths/weaknesses. Comment analysis: Claude API cost pain, first client with zero social proof.",
        "CTA. Claude Code on-tape.",
    ],
    "atoms": [src(
        "A sub-agent can block on approval. Visibility + notify + approve is the HITL surface.",
        "Delegation is allowed; silent world-actions are not what he shows on the comment job.",
        "Main delegates → parallel researchers → second chat needs approval → idle when done.",
        "On-tape: 'now it needs approval' + notification sound.",
        "Steal visible-delegate + approve. Claude Code is not our stack.",
        concept="Sub-agent waits for approval",
    )],
    "C": ["Watching is the product. Idle is the stop.", "Comment analysis can surface 'first client with zero social proof' — learn, do not hunt."],
    "D": ["If sub-agents exist, require an approval pause before outbound.", "Do not treat 'running my business' as auto-money.", "Cursor Task desks already analog this — do not install Claude Code."],
    "E": [ex("Need Google vs OpenAI diagram + comment analysis", "Two researchers + a second terminal", "Watch them", "Diagram done; comment job asked approval", "Approval is the steal")],
    "F": ["If a sub-agent can send/post → it must need approval.", "If a pane says 'running my business' → still no auto-send.", "Claude Code stays on-tape."],
    "G": ["Field wants headless loops. He wants to watch and approve."],
    "H": ["'Running my business' is rhetoric.", "Long: `62Rfe1w9NBc`."],
    "I": ["What was the approval for — a tool call? A send? Tape says 'needs approval.'", "Did anyone post the comment reply?"],
    "J": ["SYSTEM SYNTHESIS → `hive-spawn-desks` (visible desks, not Claude).", "SYSTEM SYNTHESIS → `ask-principal` · `input-required-gate`.", "Long: `62Rfe1w9NBc`."],
    "K": ["Visual idle/approve for Grok Bot later. Unassigned."],
    "machines": [{
        "name": "Delegate in parallel; approve before the world action",
        "loop": "main task → spawn researchers → watch → if approval needed, card → idle is the stop",
        "qs": "What tool is blocked? Is it send/post?",
        "qf": "Notification is not APPROVE. Evens is.",
        "proc": "Keep the pause. Do not install Claude Code. Do not auto-reply YouTube comments.",
        "ex": ex("Comment analysis sub-agent", "Needs approval", "Don't silent-run", "Paused", "Pause is HITL"),
        "why": "He shows the block. The block is the machine.",
        "never": "Claude Code as hive OS. Auto-approve notifications. Auto-reply comments. Hunt from 'zero social proof.'",
        "hive": "`ask-principal` · `input-required-gate` · `hive-spawn-desks`",
    }],
    "L": "Visible + needs-approval maps onto the five-field card. Do not import Claude Code. Comment pain is not a reason to unpark clients. Clients parked.",
}

TAKES["QrJhdTbK3TU"] = {
    "title": "Building n8n Agents Just Got So Much Easier with OpenAI",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 464,
    "A": [
        "Web search + file search via OpenAI Responses API toggle on the chat model.",
        "Web: context size low/medium/high; allowed domains (Google/LinkedIn/Wikipedia).",
        "Demo: who won the World Series — Dodgers 2025 over Blue Jays in seven; cites sites.",
        "File search: vector store ID + filter from platform.openai.com storage. Upload files / create stores. Copy ID as array.",
        "Demo: golf 'ball at rest moves' — answer depends on what caused the move.",
        "CTA.",
    ],
    "atoms": [src(
        "Domain-allowlisted web search plus a named vector store beat a raw browse.",
        "He toggles Responses API to get built-in tools (web, file, code interpreter).",
        "Enable Responses → set context size + allowlist → ask; or file-search with store ID.",
        "On-tape World Series + golf-rules answers with sources.",
        "Steal allowlist + cite. OpenAI is not our stack. Code interpreter not enabled here.",
        concept="Allowlisted search + named store",
    )],
    "C": ["Built-in tools on the model beat custom HTTP when they exist.", "Citations are part of the answer."],
    "D": ["If web search is on, set allowed domains. If file search, pin a store ID.", "Do not turn on code interpreter without a card.", "Do not paste API keys in chat."],
    "E": [ex("Who won the World Series", "Web search via Responses API", "Need current facts", "Dodgers 2025 + site cites", "Cite is the stop; do not treat sports $ as ours")],
    "F": ["If domains are not allowlisted → do not enable web search on a client agent.", "If vector store ID is wrong → refuse to answer.", "OpenAI stays on-tape."],
    "G": ["Field gives agents the whole web. He shows allowlisted domains."],
    "H": ["2025 World Series claim is on-tape / UNVERIFIED as hive fact.", "Code interpreter mentioned, not demoed."],
    "I": ["What does the filter field do? Named, not shown.", "Who pays the OpenAI bill?"],
    "J": ["Sibling file-search: `KVFfApQZhE4` Gemini. RAG: `Fu6vOfzFmcw`.", "SYSTEM SYNTHESIS → `info-gain-cite`."],
    "K": ["Allowlisted browse for Researcher later. Unassigned."],
    "machines": [{
        "name": "Allowlisted web + named file store",
        "loop": "need a fact → allowlist or store ID → ask → require cites → human checks → stop (no send)",
        "qs": "Which domains? Which store? Are cites present?",
        "qf": "No store ID, no answer.",
        "proc": "Do not enable code interpreter. Do not send the answer to a lead.",
        "ex": ex("Golf ball-at-rest", "File search on uploaded rules", "Need grounded answer", "Depends on cause", "Grounding stolen; OpenAI not installed"),
        "why": "He constrains search space. Constraint is the safety.",
        "never": "Open-web agent with Send. Install OpenAI as hive brain. Quote Series result as FACT.",
        "hive": "`info-gain-cite` · `wiki-ingest` · `ask-principal` if outbound",
    }],
    "L": "Allowlist + cite can sit on a research card. Send still REJECT. OpenAI not installed. Clients parked.",
}

TAKES["rXpHzWXjHrw"] = {
    "title": "Build Agents INSTANTLY with n8n's Native Text to Workflow Builder",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 475,
    "A": [
        "Text-to-workflow: 'newsletter every morning 7am using Tavily + Perplexity for top five AI/tech stories.' He specifies chat model and tools so it does not invent random HTTP.",
        "It searches nodes, proposes a structure, he can request changes; he approves the one-shot plan.",
        "Setup guide: email, Tavily, Perplexity, Anthropic, Gmail keys.",
        "HTTP body gets Tavily key; Perplexity connected; merge; newsletter writer. User msg: HTML from research, start with headers. System prompt short — he expected more detail.",
        "Run: research + write; he opens Gmail; looks cool; sources include YouTube + TechCrunch.",
        "CTA.",
    ],
    "atoms": [src(
        "Approve-the-plan is on tape. Then the graph can land in Gmail.",
        "Specifying tools in the prompt is how he avoids random HTTP.",
        "NL request → node search → plan → human approve → keys → run → Gmail.",
        "On-tape: 'I'm just going to go ahead and approve this plan' + Gmail check.",
        "Steal specify-tools + approve-plan. Operate-never auto-send the 7am letter.",
        concept="Text-to-workflow still needs plan approve + send gate",
    )],
    "C": ["One-shot is allowed after you named the tools.", "A short system prompt is a smell — he notices."],
    "D": ["Name the model and tools in the request. Read the plan. Approve only the build, not the send.", "If Gmail is in the setup guide, strip Send or hold the first run.", "Do not put API keys in HTTP bodies in a shared graph."],
    "E": [ex("7am AI newsletter", "Text-to-workflow, approve plan, run, open Gmail", "Instant build", "HTML with sources in Gmail", "Approve-plan stolen; Gmail send is the never")],
    "F": ["If the plan includes Gmail → two cards: build vs send.", "If the system prompt is thin → do not approve send.", "If Tavily key is in the HTTP body → secrets card."],
    "G": ["Field treats text-to-workflow as one click to live. He still approves a plan — then he still opens Gmail as success."],
    "H": ["7am cron + Gmail is a live send path.", "Keys in body is a leak pattern.", "Long: `TDHFkKSTJ30` / `a5sJNwfZ528`."],
    "I": ["Did he send to himself or a list?", "Was Gmail 'send' or draft?"],
    "J": ["SYSTEM SYNTHESIS → `session-bootstrap` · `send-removed`.", "Sibling pin: `0Ujdys4LqNs`."],
    "K": ["Text-to-workflow for internal drafts later. Unassigned."],
    "machines": [{
        "name": "NL → plan approve → draft newsletter (no 7am send)",
        "loop": "name tools → generate plan → Evens approves graph → run to draft → Evens sends → stop",
        "qs": "Which tools? Is Gmail Send on the canvas? Who is the To:?",
        "qf": "Approving the plan is not approving the 7am cron.",
        "proc": "Build. Pin. Draft. Strip Send. Keys not in HTTP body.",
        "ex": ex("7am top-five AI news", "Approve plan, run, Gmail looks cool", "Instant", "Sources in the letter", "Look is not a list-send"),
        "why": "He already has a plan gate. We add a second gate on Send.",
        "never": "Auto-send 7am. Keys in body. Approve-plan as send.",
        "hive": "`session-bootstrap` · `send-removed` · `ask-principal`",
    }],
    "L": "Two cards: (1) approve the generated graph, (2) first send. Cron that emails is REJECT until Evens. Clients parked.",
}

TAKES["hN58VkYLie4"] = {
    "title": "Claude Code + Trigger.dev: I'm Never Building Agents the Same Way",
    "speaker": "on-tape Claude Code operator",
    "kind": "short",
    "words": 478,
    "A": [
        "Claude Code turns plain English into a code project; Trigger.dev hosts it so it runs all the time (off the laptop).",
        "Example request: monitor YouTube for new AI videos, daily summary.",
        "ClickUp: new task 'Nvidia' → research polar starts → company researcher. Claude search-web ×2 then again for comprehensive report; read URL; ~45s; task marked complete with Nvidia brief.",
        "Follow-up in-task: '@UPAI how is their stock doing?' — must read context to know 'they.' Follow-up responder runs.",
        "CTA. Claude Code / Trigger.dev / ClickUp on-tape.",
    ],
    "atoms": [src(
        "Local agent code plus a cloud runner is how he gets 24/7. Follow-up needs thread context.",
        "A ClickUp task is the trigger; complete + brief in the task is the stop for that slice.",
        "Task created → researcher → web tools → write brief → mark complete → @mention follow-up.",
        "On-tape Nvidia brief + stock follow-up.",
        "Steal task-as-trigger + context-for-they. Operate-never 24/7 cloud that can send. Claude/Trigger.dev on-tape.",
        concept="Task in → brief in the same task",
    )],
    "C": ["24/7 means get it off the laptop — that is deploy.", "Pronouns require reading the task, not a new chat."],
    "D": ["Keep the job in one task thread. Write the brief there. Human asks follow-ups.", "Do not mark complete if the next step is a send/buy.", "Do not install Trigger.dev as hive cron."],
    "E": [ex("ClickUp task Nvidia", "Researcher searches thrice + read URL", "Comprehensive brief", "Complete + brief in task; stock follow-up works", "Thread context is the steal; cloud 24/7 is the never")],
    "F": ["If it must run when the laptop is closed → that is deploy → card.", "If 'they' is ambiguous → read the task, do not guess a new company.", "Stock answers are not trade advice / not a send."],
    "G": ["Field stays in chat. He puts the work in ClickUp so follow-ups have a home."],
    "H": ["45s / comprehensive — demo timing UNVERIFIED.", "UPAI @mention is his brand."],
    "I": ["Does Trigger.dev have send credentials?", "Who gets the daily YouTube summary — Slack/email?"],
    "J": ["SYSTEM SYNTHESIS → `inbox-to-task-routing` inverse (task-to-research).", "SYSTEM SYNTHESIS → `coverage-loop` (24/7 ≠ auto-money).", "Deploy: `ask-principal`."],
    "K": ["Task-thread researcher for hive later. Unassigned."],
    "machines": [{
        "name": "Task-triggered research brief (no 24/7 send)",
        "loop": "task named → research → write brief on the task → human follow-up in-thread → stop (no broker, no email blast)",
        "qs": "What is 'they'? Does the runner have Send? Is this deploy?",
        "qf": "Daily summary to a list is a send card.",
        "proc": "Local or Cursor Task. No Trigger.dev. No trade. No auto-complete that emails.",
        "ex": ex("Nvidia task", "Search + read + brief + complete", "Watch it work", "Follow-up stock uses context", "Context stolen; cloud runner not installed"),
        "why": "The useful machine is one thread that remembers 'they.' The dangerous machine is always-on cloud creds.",
        "never": "Trigger.dev / Claude Code as hive. Auto-deploy. Auto-email daily summaries. Trade on the stock line.",
        "hive": "`inbox-to-task-routing` · `coverage-loop` · `ask-principal`",
    }],
    "L": "Task-as-home is stealable. 24/7 cloud runner is deploy — REJECT this session. Stock line is not a trade. Clients parked.",
}

TAKES["glM8godEcic"] = {
    "title": "I Built an AI Voice Receptionist with Vapi and n8n MCP",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 484,
    "A": [
        "Vapi front end + n8n MCP back end. One tool per function: client lookup, new client CRM, check availability, book event, update, lookup, delete appointment.",
        "Live call to Kylie / Hercules Detailing. New caller. Collects email, full name, phone. Read-back confirm. Creates profile.",
        "Caller wants interior tomorrow. Agent lists taken slots (10:15–11:15, 2–3) and open hours. Caller picks 8am. Agent: you're all set, reserved.",
        "CTA to full template `y-cq_Qo4zVo`.",
    ],
    "atoms": [src(
        "One-function tools plus a read-back still end in an auto-book.",
        "MCP speed is the pitch; create-event is the payload.",
        "Lookup/create CRM → check availability → book event.",
        "On-tape: read-back of email/name/phone then 'you're all set' for 8am.",
        "Steal one-function tools + read-back. Operate-never book/delete/CRM-write without Evens.",
        concept="Read-back then auto-book",
    )],
    "C": ["Specific tools beat one god-tool. Specific includes delete.", "Confirming PII out loud is good; booking after confirm is the jump."],
    "D": ["Keep lookup + check availability + spoken read-back.", "Remove book / update / delete / new-CRM-write from the live assistant.", "Vapi not installed. PII not dumped to Slack."],
    "E": [ex("New caller Nate K", "Collect + read-back + 8am book", "Show MCP tools live vs calendar/CRM", "Reserved 8am", "Read-back stolen; reserve is never")],
    "F": ["If delete-appointment is a tool → it is Tier-3.", "If new-client CRM writes phone → PII card.", "If 'you're all set' fires without Evens → REJECT."],
    "G": ["Field wants the receptionist to close. Hive wants the receptionist to collect and stop."],
    "H": ["333-444-5678 / nate@acample.com demo PII.", "Long: `y-cq_Qo4zVo`."],
    "I": ["Did delete get demoed? Not on this short.", "Timezone / duration assumptions?"],
    "J": ["SYSTEM SYNTHESIS → `ask-principal` · `missed-call-book` · `private-book-install`.", "Sibling auto-book: `G9Ho8n4lD6I`."],
    "K": ["One-function MCP catalog as a design rule. Keep."],
    "machines": [{
        "name": "One-function voice tools + read-back (book stays HITL)",
        "loop": "call → lookup or collect → read-back → check availability → offer slots → write a card (not book) → Evens books",
        "qs": "Email? Name spelling? Phone? Which slot? Who presses book?",
        "qf": "New caller is OK. Auto-CRM-write is a card. Auto-book is never.",
        "proc": "Tools live: lookup + check availability. Tools dead: book, update, delete, new CRM.",
        "ex": ex("Kylie call, new caller", "Read-back then 8am reserve", "MCP seven tools", "All set", "Seven tools is the blast radius"),
        "why": "Read-back is real HITL. Book-event after read-back skips Evens.",
        "never": "Auto-book / auto-voice-book / delete appointment / Vapi stack / dump PII.",
        "hive": "`ask-principal` · `missed-call-book` · `send-removed`",
    }],
    "L": "Canonical receptionist tape. Steal read-back + one-function tools. ACTION = REJECT book/delete. RISK = 8am on a real calendar. Clients parked. No Vapi.",
}

TAKES["UCKLHU5AkEM"] = {
    "title": "Gemini 3.1 Flash Live Just Changed Voice Agents Forever",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 486,
    "A": [
        "Cold open: broken scissors; model explains they come apart for cleaning; rivet+slot; he reassembles. Then 'Hey Gemini' vision: gray walls, trophies, mic; identifies Shure MV7 + Rode arm correctly.",
        "Gemini 3.1 Flash Live: speech-to-speech (not STT→TTS), can see, 'biggest upgrade yet' (vendor).",
        "Benchmark: multi-step function calling +~19% vs 2.5 Flash UNVERIFIED.",
        "Roadside noisy demo: still asks registration plate + postcode. Alphanumeric accuracy. Interprets sarcasm/stress/frustration for support/sales bots.",
        "CTA to `Qt3zMBH-FNg`.",
    ],
    "atoms": [src(
        "Speech-to-speech + vision can collect plate/postcode in noise. That is PII capture, not a book.",
        "Affect (stress/sarcasm) is why he wants it on support/sales.",
        "See → speak → function-call (lookup by plate+postcode).",
        "On-tape scissors + mic ID + noisy plate ask.",
        "Steal vision-help + noisy capture. Operate-never voice-book / plate lookup as a live customer system. Gemini on-tape.",
        concept="Speech-to-speech can harvest PII in noise",
    )],
    "C": ["Human-like voice is a support feature and a social-engineering feature.", "Seeing the room is a demo flex and a privacy event."],
    "D": ["If vision is on, tell the human. If plate/postcode are collected, that is PII — card, no CRM auto-write.", "Do not attach book/pay tools to a speech-to-speech bot.", "Gemini not installed."],
    "E": [ex("Noisy roadside support", "Ask plate + postcode anyway", "Unfazed by horns", "Still collecting identifiers", "Noise-robust capture is the risk")],
    "F": ["If the model can see → treat as a camera on.", "If it asks plate/postcode → PII card.", "If +19% function-calling → UNVERIFIED, not a send permit."],
    "G": ["Field hears 'more human' as better bot. This desk hears 'better at extracting identifiers under stress.'"],
    "H": ["+19% / biggest upgrade UNVERIFIED.", "Shure/Rode ID could be trained prior — still a vision claim."],
    "I": ["Does speech-to-speech log raw audio?", "Can it place a book in the same turn? Long cut."],
    "J": ["Long: `Qt3zMBH-FNg`. Voice book never: `G9Ho8n4lD6I`.", "SYSTEM SYNTHESIS → PII / `ask-principal`."],
    "K": ["Vision-for-repair (scissors) as a QoL idea. Unassigned. Not a product."],
    "machines": [{
        "name": "Noisy capture stays a card (no lookup-to-book)",
        "loop": "voice in → if identifiers requested, read-back → write card → Evens looks up → stop",
        "qs": "Is a camera on? Plate/postcode? Book tool attached?",
        "qf": "Stress/sarcasm detection is not consent to close.",
        "proc": "No Gemini. No plate CRM. No voice-book.",
        "ex": ex("Horns + plate ask", "Still collects postcode", "Show robustness", "Unfazed", "Robust ≠ allowed"),
        "why": "The upgrade he names is function-calling + affect. Both make auto-close more likely.",
        "never": "Gemini voice as hive. Auto-book. Plate/postcode CRM write. Camera-on without telling Evens.",
        "hive": "`ask-principal` · `missed-call-book` (no auto-voice-book)",
    }],
    "L": "Vision + plate/postcode is a secrets/PII card. ACTION = REJECT live customer voice. Scissors demo is cute and not a SKU. Clients parked.",
}

TAKES["mPflFTQUCGk"] = {
    "title": "Unlock the Full Power of Your AI Agents with n8n Instance MCP",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 515,
    "A": [
        "Enable MCP access in n8n settings. Claude: add connector, n8n native, connect; first time paste server URL.",
        "Pitch: instead of copy-paste a drafted email, say 'send that off now' if an n8n send workflow exists.",
        "Demo: send to michael@dundermifflin.com. Claude searches workflows, gets details (always allow), knows three body fields + webhook, always allow again. Confirmation: email sent. He opens the inbox.",
        "Then: ClickUp task 'email Michael about PTO' urgent today — 'use n8n to move to complete.' Always-allow path. Task completed.",
        "CTA.",
    ],
    "atoms": [src(
        "Always-allow + instance MCP + a send workflow = mail leaves without a second human.",
        "He frames this as beating copy-paste. Copy-paste was the gate.",
        "Draft in Claude → 'send that off now' → search workflows → always allow → sent.",
        "On-tape: 'the email has been sent' + inbox screenshot.",
        "Steal search-then-fill-fields. Operate-never always-allow send. Claude on-tape.",
        concept="Always-allow send via instance MCP",
    )],
    "C": ["Context-switch is the enemy; he removes the human from the send to save a tab.", "Always-allow is how he makes it feel native."],
    "D": ["If MCP is connected, never always-allow a send/webhook tool.", "Keep 'write the email' in the chat. Send is a card.", "ClickUp complete is OK if it does not email; still no always-allow on send."],
    "E": [ex("Email written in Claude", "'Use n8n to send to Michael'", "Skip copy-paste", "Always-allow ×2, mail in inbox", "This is the exhibit for never")],
    "F": ["If the tool is a webhook that sends → deny always-allow.", "If the user says 'send that off now' → five-field card, not MCP.", "Claude connector is not our stack."],
    "G": ["Field wants talk-to-send. Doctrine rule: if it has Send, it will send."],
    "H": ["Dunder Mifflin joke address — still a send.", "Sibling theory: `9IzGe0BBj_c`."],
    "I": ["Can always-allow be scoped per tool in his UI? He always-allows both.", "Does ClickUp complete trigger a notification email?"],
    "J": ["SOURCE pair: `9IzGe0BBj_c` (execute any) + this (actually sends).", "SYSTEM SYNTHESIS → `send-removed` · `input-required-gate`."],
    "K": ["MCP for read-only workflow search later. Unassigned."],
    "machines": [{
        "name": "MCP may search and draft; Send stays a card",
        "loop": "write email → optional: search workflows for a draft tool → Evens sends → stop",
        "qs": "Is this get-details or execute-send? Always-allow on?",
        "qf": "'Send that off now' is the phrase that must open a card.",
        "proc": "Disable instance MCP on any graph with Gmail Send. No always-allow.",
        "ex": ex("michael@dundermifflin.com", "Always-allow send workflow", "Beat copy-paste", "Inbox shows the mail", "Copy-paste was the HITL"),
        "why": "He proves talk-to-send works. That proof is why this desk exists.",
        "never": "Always-allow. Talk-to-send. Claude as hive mailer. Auto-complete a task that implies a send.",
        "hive": "`send-removed` · `input-required-gate` · `ask-principal`",
    }],
    "L": "Highest-signal auto-send short. ACTION = REJECT always-allow and 'send that off now.' ClickUp complete without mail is fine. Clients parked.",
}

TAKES["HbsbqMQE-lI"] = {
    "title": "Automate Unlimited Content with Poppy AI and n8n",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 521,
    "A": [
        "n8n = no-code agents. Poppy = paste sources, chat with them.",
        "Paste latest YouTube URL → transcribed + thumbnail analyzed. Paste website. Chat with both selected: three takeaways + apply to True Horizon. Model Claude Sonnet, switchable.",
        "Takeaways echo 'stop selling agents, sell solutions.'",
        "When is n8n needed? He pasted 4 winning LinkedIn posts + 3 best-practice articles + latest video → LinkedIn post in his style. Could automate on new video → Poppy → post, but that might be overkill vs paste-once.",
        "Value: trigger later if you want; research before/after; add elements after Poppy returns copy.",
        "CTA.",
    ],
    "atoms": [src(
        "Do not automate a content step you can paste once. Overkill is a real miss.",
        "Sources in a canvas + a scoped question beat a cron.",
        "Paste YT + site → ask takeaways → optional later cron.",
        "On-tape: he says the LinkedIn automation might be overkill.",
        "Steal paste-once judgment. Operate-never auto-post LinkedIn. Poppy/Claude on-tape.",
        concept="Paste-once before you cron",
    )],
    "C": ["Automation is optional after the manual loop works.", "His own 'sell solutions' tape becomes the source — dogfood."],
    "D": ["Paste the sources. Ask. Edit. Human posts.", "Only schedule if the paste-once loop is boring and Evens wants it.", "No auto-publish."],
    "E": [ex("Need a LinkedIn post from a new video", "Paste video + winning posts + articles, ask once", "Maybe don't build n8n", "Post draft in-chat", "Overkill warning is the steal")],
    "F": ["If you have not done it manually twice → do not cron.", "If the next node is LinkedIn publish → card.", "Poppy is not our stack."],
    "G": ["Field automates content first. He asks whether n8n is needed."],
    "H": ["True Horizon apply is his agency, not ours.", "Unlimited in the title is marketing."],
    "I": ["Does the full video add an auto-post? CTA only.", "Thumbnail analysis quality?"],
    "J": ["SYSTEM SYNTHESIS → `one-channel-deep` · `clip-factory` · `slice-build`.", "Doctrine: visible → efficient → automatic → then judgment."],
    "K": ["Overkill test as a default question on any content cron. Keep."],
    "machines": [{
        "name": "Paste-once content, cron only after it is boring",
        "loop": "paste sources → ask → edit → Evens posts → if twice-boring, card a cron that still stops at draft",
        "qs": "Have we done this manually? Does the cron publish?",
        "qf": "Unlimited content is not a reason to auto-post.",
        "proc": "No Poppy install. No LinkedIn send. Draft in repo.",
        "ex": ex("LinkedIn from latest YT", "Paste, don't automate", "Overkill", "Draft in chat", "Judgment before automatic"),
        "why": "He says the automation might be overkill. That sentence is the machine.",
        "never": "Auto-post. Poppy as stack. Quote 'unlimited' as FACT.",
        "hive": "`one-channel-deep` · `clip-factory` · `ask-principal`",
    }],
    "L": "Ask 'is this overkill?' on any content-cron card. Publish stays Evens. Clients parked.",
}

TAKES["KVFfApQZhE4"] = {
    "title": "Gemini's New File Search Just Leveled Up RAG Agents (10x Cheaper)",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 524,
    "A": [
        "Gemini file search: drop a doc, embeddings, chat. Avoids a huge n8n data pipeline.",
        "Four HTTPs: create store ('folder'), upload to Google Cloud, move file into the store, query via agent tool.",
        "Drops ~22-page rules-of-golf PDF. Asks what happens if your club breaks during the round.",
        "Short answer: if broken in normal play, continue / repair / replace. Cites knowledge base + rule 4 clubs.",
        "Title says 10x cheaper — not derived in this short. CTA to `irg-2IfAjpo`.",
    ],
    "atoms": [src(
        "Managed file-search can replace a home-rolled chunk pipeline if you still cite the rule.",
        "Create / upload / move / query are four distinct calls — upload ≠ in-store.",
        "Store → upload → move → ask with citation.",
        "On-tape golf club-break answer + source.",
        "Steal four-step store + cite. 10x cheaper UNVERIFIED. Gemini on-tape.",
        concept="Upload is not indexed until move",
        conf="low on 10x — title-only UNVERIFIED",
    )],
    "C": ["Huge pipelines are the thing to delete when a vendor store works.", "Citation is part of a correct answer."],
    "D": ["Do not query before move. Ask a known rule. Require the source line.", "Do not install Gemini. Do not answer a customer from the store without a card."],
    "E": [ex("22-page golf PDF", "Four HTTPs then 'club breaks'", "Skip giant pipeline", "Rule 4 + cite", "Cite is the stop")],
    "F": ["If upload succeeded but move did not → do not query.", "If no source in the answer → fail.", "10x in the title → UNVERIFIED."],
    "G": ["Field builds vector cathedrals. He uses the vendor store and still cites."],
    "H": ["10x cheaper is title/marketing.", "22 pages approximate."],
    "I": ["What is the actual price delta in the long cut?", "Retention/deletion of the store?"],
    "J": ["Long: `irg-2IfAjpo`. OpenAI file search: `QrJhdTbK3TU`. Drive RAG: `Fu6vOfzFmcw`.", "SYSTEM SYNTHESIS → `wiki-ingest` · `info-gain-cite`."],
    "K": ["Four-step managed store as a RAG option later. Unassigned."],
    "machines": [{
        "name": "Managed store + mandatory cite",
        "loop": "create store → upload → move → query → require source → human checks the PDF → stop",
        "qs": "Did we move? Is the cite a real page/rule?",
        "qf": "No cite, no answer outbound.",
        "proc": "Gemini stays on-tape. Customer answers are a card.",
        "ex": ex("Club breaks in the round", "Query file search", "Need grounded rules", "Rule 4 + knowledge base", "Grounding stolen; vendor not installed"),
        "why": "He shows the move step so people do not query an empty folder.",
        "never": "Gemini as stack. Quote 10x as FACT. Auto-answer clients from the PDF.",
        "hive": "`wiki-ingest` · `info-gain-cite` · `ask-principal`",
    }],
    "L": "Four-step ingest can be a research card. Outbound answers REJECT without Evens. 10x UNVERIFIED. Clients parked.",
}

TAKES["IlNwjnIzrOo"] = {
    "title": "An Army of Media Agents That Do Everything",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 545,
    "A": [
        "Telegram image → Drive. Agent asks name + sharing settings. He names it 'speaker.' Drive agent change-name. Logs actions. Media folder has speaker.",
        "Edit: studio, energetic, colorful, music-on-a-speaker feeling — 'the media team will figure it out.' Creative agent edit-image. Returns three styles. He picks the first preview.",
        "Turn that into a VFX ad with music/lights synced, JBL speaker. Aside: creative agent has full autonomy to use its tools; also tries a text-only video he is not confident about.",
        "Impressed by image-to-video. CTA to free full setup `jBanaNBY-sM`.",
    ],
    "atoms": [src(
        "Ask name + sharing is HITL. 'Full autonomy' on the creative agent is the publish trap.",
        "Three previews then he picks — director stays human until the VFX ask.",
        "Telegram → Drive → ask name/sharing → edit → three options → pick → video.",
        "On-tape: asks name/sharing; 'creative agent has full autonomy'; three images.",
        "Steal ask-name + pick-one-of-three. Operate-never autonomy-as-publish / auto-post JBL ad.",
        concept="Ask-name then pick; autonomy is not a gate",
    )],
    "C": ["Media team metaphor = let the specialist agent choose tools. That is not Evens choosing to post.", "He is not confident in text-only video — confidence is a signal."],
    "D": ["Ask name and sharing. Generate three. Human picks. Video is another look. Publish is a card.", "Do not treat 'full autonomy' as skip-the-card.", "JBL is a real brand — demo only."],
    "E": [ex("Speaker photo in Telegram", "Ask name/sharing, three edits, pick first, VFX ask", "Army that does everything", "Three stills + image-to-video", "Everything includes post if we let it")],
    "F": ["If sharing settings change → card (public link).", "If three options exist → Evens picks.", "If autonomy is claimed → assume it will post if a social tool exists (long cut)."],
    "G": ["Field wants an army that posts. He still asks the name — then praises autonomy."],
    "H": ["JBL ad is a brand-risk demo.", "Long cut adds X/TikTok/IG never — `jBanaNBY-sM`."],
    "I": ["Does the long cut post to social?", "What are the sharing options he offered?"],
    "J": ["SOURCE sibling: `TWvjqpk3uSQ` ask-name. Long: `jBanaNBY-sM`.", "SYSTEM SYNTHESIS → `ask-principal` · `product-ad-from-photo` · `clip-factory`."],
    "K": ["Three-options-then-pick as Creative default. Keep."],
    "machines": [{
        "name": "Ask name/sharing → three options → Evens publishes",
        "loop": "image in → ask name+sharing → edit → three previews → Evens picks → optional video preview → publish card → stop",
        "qs": "Name? Sharing public? Which of three? Who posts?",
        "qf": "Full autonomy is a no. 'Media team will figure it out' is not publish.",
        "proc": "No social tools on the creative agent. No JBL live ad.",
        "ex": ex("Speaker image", "Ask speaker + three styles + VFX", "Army demo", "Impressed by image-to-video", "Impressed ≠ live"),
        "why": "The ask is already on tape. Autonomy is the contradiction we keep in operate-never.",
        "never": "Autonomy-as-publish. Auto-post. Public sharing without Evens. JBL as client proof.",
        "hive": "`ask-principal` · `product-ad-from-photo` · `clip-factory`",
    }],
    "L": "Overwrite the shallow take: ask-name is the steal; autonomy-as-publish is the never. Long cut social posts stay never. Clients parked.",
}

TAKES["bX_stJ_Eiog"] = {
    "title": "Build ANYTHING with Base44 and n8n AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 563,
    "A": [
        "Lead-magnet: Base44 front end (name, email, describe a problem) → n8n agent trained to write an AI implementation roadmap.",
        "Thin prompt; first preview is AI-slop titled (AI consulting excellence / society / journey). He asks for spacing; animation kept.",
        "Submit test data. Execution runs. Email sent: 'free AI implementation guide' — meeting prep, automation, proposal, roadmap. Diagnoses 20 min/meeting. Table of trigger / enrichment (Apollo or People Data Labs) / function. CTA: reclaim 8+ hours, book a discovery call.",
        "CTA to `tFFKuq2t0rI`. Base44 / Apollo / PDL on-tape.",
    ],
    "atoms": [src(
        "A form that emails a roadmap plus a book-a-call CTA is send + book in one execution.",
        "First vibe preview is slop; he iterates visually before the live submit.",
        "Form submit → agent → email with diagnosis + book CTA.",
        "On-tape: 'the email has been sent' + book-a-discovery-call.",
        "Steal iterate-the-preview + diagnose-in-the-PDF. Operate-never auto-email + auto-book CTA fire. Base44 not our stack.",
        concept="Lead magnet that sends and asks to book",
    )],
    "C": ["Clean first draft is not done. Spacing pass is taste.", "The email is the product — and the risk."],
    "D": ["Iterate the preview. Click the form (`click-live-site`). Hold the first real email.", "Do not attach Apollo/PDL enrichment on a parked hunt.", "Book link is a CTA, not an auto-book — still a send."],
    "E": [ex("Test form submit", "Workflow runs, email with roadmap + book CTA", "Lead magnet", "Mail sent", "Send is the never; diagnosis table is the steal")],
    "F": ["If submit sends mail → first live submit is a card.", "If CTA is book-a-call → do not auto-book the calendar.", "If enrichment vendors are named → do not install them this session."],
    "G": ["Field wants the magnet to nurture itself. This desk wants preview + draft."],
    "H": ["8+ hours / 20 min/meeting UNVERIFIED.", "Apollo/PDL are hunt tools — clients parked."],
    "I": ["Is the book link Calendly-auto?", "Who paid Base44?"],
    "J": ["Long: `tFFKuq2t0rI`.", "SYSTEM SYNTHESIS → `click-live-site` · `send-removed` · `paid-slice-funnel` (preview≠domain)."],
    "K": ["Diagnosis-table-in-the-leave-behind later for Path A. Parked."],
    "machines": [{
        "name": "Preview the magnet; first email is a card",
        "loop": "vibe UI → iterate look → test submit to a sink → Evens approves first real send → book CTA is a link, not a calendar write",
        "qs": "Does submit send? Does the CTA write a calendar?",
        "qf": "AI-slop titles fail click-live-site.",
        "proc": "No Base44 as ours. No Apollo. No auto-send. No auto-book.",
        "ex": ex("Filled the form", "Email with roadmap + book CTA", "Show the pipe", "Sent", "Pipe stolen; send rejected"),
        "why": "He clicks submit and celebrates the sent mail. That celebration is the hard step.",
        "never": "Auto-send magnet. Auto-book. Apollo/PDL hunt. Base44 as stack. Unpark clients.",
        "hive": "`click-live-site` · `send-removed` · `ask-principal` · `paid-slice-funnel`",
    }],
    "L": "Lead-magnet graphs are send cards. Book CTA must not write a calendar. Preview iteration is stealable. Clients parked. No hunt.",
}

TAKES["S2ME69hra-k"] = {
    "title": "Why Watching AI Videos Isn't Enough",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short / promo",
    "words": 613,
    "A": [
        "YouTube teaches technical + how to land clients; scoping, what to charge, how to deliver without collapse is often off-YouTube — secret sauce + everyone starts in a different boat. Reps apply knowledge to your experience.",
        "Free start: Monetizing AI Automation playlist — real sold agents, a real sales call, first client, pricing, delivery, proof.",
        "Results come from being in the room: tailored questions, people one/three steps ahead.",
        "Offer 1: AIS Live Jul 11–12 — day 1 live builds / what sells / deployed builds; day 2 niche, outreach, positioning, scoping, pricing, delivering. Airtable Hyper Agent sponsor.",
        "Offer 2: Montenegro mastermind Jul 29–31; he will be there; Cape Town prior; names Liam Ottley, Dave Abelar, Jack Roberts.",
        "Links in description. If not, next one.",
    ],
    "atoms": [src(
        "Watching is not delivery. Scoping/pricing/delivery need reps and a room — or a playlist as the cheap start.",
        "The tape then sells two paid rooms (virtual + Montenegro).",
        "Playlist → or event → or mastermind.",
        "On-tape: YouTube is not enough; AIS Live + Montenegro.",
        "Steal tape-self-teach + reps. Operate-never join Skool/event as hive SKU. Dates/names on-tape.",
        concept="Watch then do reps; rooms are optional and not ours",
    )],
    "C": ["Imposter syndrome is a scoping/pricing gap, not a missing node.", "Different boats → no one-size pack."],
    "D": ["Start with the free playlist (learn). Do not buy the room for the hive.", "Do not run outreach because day 2 is about outreach.", "Dates are on-tape, not our calendar."],
    "E": [ex("Feel confused on scope/price/delivery", "He points to playlist then AIS Live / Montenegro", "YouTube isn't enough", "Promo", "Promo is the never; reps are the steal")],
    "F": ["If the gap is delivery collapse → do reps on a parked slice, not a paid mastermind.", "If names of gurus appear → on-tape only.", "If outreach is taught → still no send this session."],
    "G": ["Field sells the room as the only way. He also names a free playlist first."],
    "H": ["Event dates / sponsors / attendee quality UNVERIFIED.", "Airtable Hyper Agent sponsor."],
    "I": ["Is AIS Live still a real date relative to ingest? Do not book.", "What is actually off-YouTube vs withheld?"],
    "J": ["SYSTEM SYNTHESIS → `tape-self-teach` · `coverage-loop` (learn then one dry-run).", "Kill: Skool / mastermind as hive SKU."],
    "K": ["Delivery-without-collapse notes when Evens names a client. Parked."],
    "machines": [{
        "name": "Watch → one parked rep (no paid room)",
        "loop": "watch a tape → write the take → one dry-run in Cursor → stop (no buy, no outreach)",
        "qs": "Did we do a rep? Are we about to buy a ticket?",
        "qf": "Imposter feeling is not a credit-card event.",
        "proc": "No AIS Live signup. No Montenegro. No Airtable. No guru stack.",
        "ex": ex("Confused on pricing", "He sells AIS Live + Montenegro after a free playlist", "Room with people", "Promo CTA", "Playlist/reps stolen; ticket never"),
        "why": "He admits YouTube lacks delivery. The hive already has desks for that — not his events.",
        "never": "Buy/book the event. Join Skool. Start outreach because day 2 said so. Quote attendee lists as FACT.",
        "hive": "`tape-self-teach` · `coverage-loop` · `ask-principal` (no pay)",
    }],
    "L": "No ticket card except REJECT. Steal 'watching ≠ delivery' as a reason to finish takes + one dry-run. Clients parked. No outreach.",
}

TAKES["-Lo_SlSgtnA"] = {
    "title": "This Voice Agent Calls and Qualifies All Your Leads",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 622,
    "A": [
        "Pitch: agent that calls people while you sleep. Website form → auto-call, qualify, log, so you know more before outreach.",
        "Practice: form → webhook. Demo uses native n8n form. Mock Richard / Greengrass / gardening / phone / email / role / company size.",
        "HTTP 'call lead' fires. Elliot (AI) calls: confirm Richard/Greengrass, automate lead-gen, why now (holidays slow, stopped outreach), how soon (within a month).",
        "Row appears: request, size, interest, motivation, urgency, past experience, budget, intent, status complete.",
        "Now you have more than the form to reach out. CTA to full cut `BO-jFbN4p8Y`.",
    ],
    "atoms": [src(
        "Form-to-auto-dial is the product. The useful part is the extra qualify fields.",
        "He says you then reach out — the agent already called them.",
        "Form → HTTP call lead → voice qualify → sheet row.",
        "On-tape live call to the filled phone number + complete row.",
        "Steal the qualify question set. Operate-never auto-dial / while-you-sleep / auto-book. Vapi-class stack on-tape.",
        concept="Sleep-dial is the never; questions are the steal",
    )],
    "C": ["Speed-to-lead is calling now, even at night.", "A form is incomplete until a voice layer asks why-now and urgency."],
    "D": ["Keep the questions: what prompted now, how soon, budget, past experience, intent.", "Do not fire HTTP call-lead. Route to a card / SMS book-link (`missed-call-book`).", "No Vapi. No while-you-sleep."],
    "E": [ex("Richard Greengrass form", "Auto-call Elliot, qualify, log complete", "While you sleep", "Row with motivation/urgency/budget", "Questions stolen; the call is never")],
    "F": ["If a form can trigger a phone call → that trigger is REJECT.", "If the sheet has budget/intent → useful for a human call later.", "If 'outreach' is next → still no auto-send."],
    "G": ["Field wants after-hours dialers. Hive kill row: auto-dial factory."],
    "H": ["Mock data — still a real call in the demo.", "Budget field collected — PII/money signal."],
    "I": ["Consent to be called? Form may imply it — still not our operate.", "What if Richard is a real number reused?"],
    "J": ["Long: `BO-jFbN4p8Y`. Kill: steal-sheet auto-dial factory.", "SYSTEM SYNTHESIS → `missed-call-book` · `ask-principal` · `discovery-spiced-constraint`."],
    "K": ["Qualify-question list for a human speed-to-lead later. Parked."],
    "machines": [{
        "name": "Form → qualify fields (human calls; no sleep-dial)",
        "loop": "form in → write sheet → Evens or a human calls with the question list → log answers → stop (no auto-dial, no auto-send)",
        "qs": "Why now? How soon? Budget? Past tools? Intent?",
        "qf": "While-you-sleep is a no. Webhook-to-phone is a no.",
        "proc": "Delete call-lead HTTP. Keep the question list. No Vapi.",
        "ex": ex("Greengrass form", "Elliot auto-calls and fills budget/urgency", "Sleep-dial pitch", "Status complete", "Sheet is the steal; call is the never"),
        "why": "The form is thin. The questions are the value. The dial is the irreversible step.",
        "never": "Auto-dial. Auto-voice-book. While-you-sleep. Vapi. Unpark a list to call.",
        "hive": "`missed-call-book` · `ask-principal` · `discovery-spiced-constraint` · `send-removed`",
    }],
    "L": "Highest-signal auto-dial tape. Steal the question list onto a card. ACTION = REJECT call-lead. Clients parked. No restaurant auto-book analog either.",
}

TAKES["ZwQ8rJhVCr4"] = {
    "title": "4 Simple RAG Methods for Better AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 641,
    "A": [
        "Four methods: filters, SQL, full context, vector DB.",
        "Filters: 'how many Bluetooth speakers on Sept 16' → product-name filter + date filter → five.",
        "SQL on Postgres/Supabase sales (50 rows): three highest-earning products — AI automation course 34.93, consulting 33383, workflow template 1659 + % of revenue (numbers on-tape UNVERIFIED).",
        "Full context: do not chunk; let the agent read the whole doc. Chronological breakdown of 'agent in 2 hours' video — opening hook through sales — because it read in order. 4,000 tokens of 400,000 on GPT-5-mini.",
        "Same docs in Supabase vectors: same chronological question is faster/cheaper and less accurate — it does not understand order.",
        "CTA.",
    ],
    "atoms": [src(
        "Retrieval method must match the question. Order questions need full context, not chunks.",
        "Filters/SQL for tabular facts; full read for chronology; vectors for cheap fuzzy — with an accuracy cost.",
        "Pick method → ask → compare.",
        "On-tape: five speakers; SQL top-3; full-context order; vector cheaper/wronger.",
        "Steal method-pick. Token/revenue numbers UNVERIFIED. Do not auto-answer customers.",
        concept="Match retrieval to the question type",
    )],
    "C": ["Cheaper/faster is not better when order matters.", "He wants you to see the miss, not hide it."],
    "D": ["Tabular count → filter or SQL. Chronology / whole-argument → full context if it fits. Fuzzy FAQ → vectors + cite.", "Always know which method you picked.", "Do not send the answer outbound without Evens."],
    "E": [ex("Chronological breakdown of a video transcript", "Full context vs vector", "Order matters", "Full context keeps order; vector cheaper and loses order", "Pick the method on purpose")],
    "F": ["If the question is 'in order' → do not use naive chunks.", "If the question is a count on a table → do not embed the table first.", "If tokens are quoted → UNVERIFIED / not a ship gate."],
    "G": ["Field defaults to vectors for everything. He shows four and the vector miss."],
    "H": ["Revenue figures and 4k/400k tokens UNVERIFIED.", "GPT-5-mini on-tape."],
    "I": ["When does he mix methods in one agent?", "What is the token cutoff for full context?"],
    "J": ["SYSTEM SYNTHESIS → `wiki-ingest` · `info-gain-cite` · `golden-test-loop`.", "Sibling ingest: `Fu6vOfzFmcw`."],
    "K": ["Method-pick rubric for hive RAG. Keep."],
    "machines": [{
        "name": "Pick RAG method by question type",
        "loop": "classify question (count / order / fuzzy) → pick filter/SQL/full/vector → answer + check → stop",
        "qs": "Is this a count, a sequence, or a semantic ask?",
        "qf": "Cheaper is not a reason to lose order.",
        "proc": "Document the method on the card. No customer auto-answer.",
        "ex": ex("Chronology of agent-in-2h", "Full read vs vectors", "Show the miss", "Vector loses order", "The miss is the lesson"),
        "why": "He runs the same question two ways so you see the failure mode.",
        "never": "Default-vector everything. Quote revenue/token numbers as FACT. Auto-answer clients.",
        "hive": "`wiki-ingest` · `golden-test-loop` · `info-gain-cite`",
    }],
    "L": "RAG cards must name the method. Order questions → full context. Outbound answers still HITL. Clients parked.",
}

TAKES["-Q_P7HFydZk"] = {
    "title": "How I INSTANTLY Generate Proposal Decks with n8n AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short / cold open + first workflow",
    "words": 812,
    "A": [
        "After a call you owe minutes or a proposal — he automated it when full-time.",
        "Two parts: (1) log meeting when it ends to a Google sheet (date, title, attendees, gist, ID, status); (2) slide deck only after human approval — 'we don't always need that' — then proposal agent → Gamma API.",
        "Webhook to Fireflies. Wait, pull title/transcript, if exists, clean JSON attendees, log sheet.",
        "Second workflow on new row: re-fetch, limit to last item if two meetings end together (guardrail), cleanup code node to speaker-then-block (not speaker-per-sentence).",
        "CTA mid-cleanup. Gamma / Fireflies on-tape.",
    ],
    "atoms": [src(
        "Human approval sits between log and deck. Not every meeting gets a Gamma.",
        "A limit-to-last-item guardrail handles two meetings ending at once.",
        "Fireflies webhook → sheet log → human approve → Gamma.",
        "On-tape: 'we get human approval right here to see if we want to have a slide deck generated or not.'",
        "Steal approve-before-deck + speaker-block transcript. Operate-never auto-send the deck. Gamma/Fireflies on-tape.",
        concept="HITL between transcript and proposal",
    )],
    "C": ["Logging is cheap and always-on. Expensive generation is optional.", "Transcript cleanup is taste (speaker blocks)."],
    "D": ["Always log. Ask Evens before Gamma. Limit to one meeting. Clean speakers into blocks.", "Do not email the deck from the graph.", "Do not install Gamma as ours."],
    "E": [ex("Call just ended", "Fireflies → sheet; approval node before Gamma", "Don't always need a deck", "Logged; CTA before the approve fires in this short", "The approval node is the steal")],
    "F": ["If a deck API will spend money → card (pay).", "If two meetings collide → process one.", "If the next node is Gmail the deck → send card."],
    "G": ["Field auto-sends recaps. He inserts human approval because not every call needs a deck."],
    "H": ["Gamma spend UNVERIFIED. Fireflies on-tape.", "Short cuts before the approve click."],
    "I": ["What does the approval UI look like in n8n?", "Does the long cut `KGXFkUlBHxw` email the client?"],
    "J": ["Long: `KGXFkUlBHxw`.", "SYSTEM SYNTHESIS → `ask-principal` · `folder-to-deck` · `client-delivery-kit`."],
    "K": ["Approve-before-expensive-generate as default. Keep."],
    "machines": [{
        "name": "Log always; generate deck only after Evens",
        "loop": "call ends → transcript in → sheet log → card (need a deck?) → if yes, generate → Evens sends → stop",
        "qs": "Do we need a deck? Who pays Gamma? Who emails the client?",
        "qf": "Not every meeting. Silence is not yes.",
        "proc": "Keep the approval node. Strip client-email. Gamma on-tape only.",
        "ex": ex("Fireflies webhook", "Log then human approval then Gamma", "Don't always need slides", "Sheet row exists", "Approval is HITL on tape"),
        "why": "He already paid the HITL tax on generate. We also tax send.",
        "never": "Auto-Gamma every call. Auto-send the deck. Quote Gamma as our stack. Pay the API without a card.",
        "hive": "`ask-principal` · `folder-to-deck` · `client-delivery-kit` · `send-removed`",
    }],
    "L": "This short already has our node: human approval. Keep it. Add a second card on client send / API spend. Clients parked.",
}


def main():
    n = 0
    for vid, t in TAKES.items():
        write_one(vid, t)
        n += 1
        print("wrote", vid)
    print("batch2", n)


if __name__ == "__main__":
    main()
