#!/usr/bin/env python3
"""Second-tier HITL thicken: send/book/deploy tapes the upgrader mislabeled."""
from _hitl_dvl_writer import write_one

def src(claim, why, mech, ev, act, **kw):
    return {"concept": kw.pop("concept"), "claim": claim, "why": why, "mech": mech, "ev": ev, "act": act, **kw}

def ex(sit, act, why, out, les, name="On-tape run"):
    return {"name": name, "sit": sit, "act": act, "why": why, "out": out, "les": les}

def pack(title, speaker, kind, words, A, atoms, machines, L, **kw):
    return {
        "title": title, "speaker": speaker, "kind": kind, "words": words, "A": A,
        "atoms": atoms,
        "C": kw.get("C", [
            "Finished-looking demo is the risk.",
            "On-tape vendors stay on-tape. Cursor + Grok.",
            "Operate ≠ learn: steal the loop, hold the write.",
        ]),
        "D": kw.get("D", [
            "Name the world action. Keep draft/log/approve. Strip Send/book/publish/deploy.",
            "Silence is not yes. Clients parked. Tape $ UNVERIFIED.",
        ]),
        "E": kw.get("E", [ex("On-tape hard step", "He demos the write", "Looks finished", "World action fires or is offered", "Steal the check; do not operate the write")]),
        "F": kw.get("F", [
            "If Send/book/publish/deploy exists → card.",
            "If tape $ → UNVERIFIED. If vendor = stack → on-tape only.",
        ]),
        "G": kw.get("G", ["Field ships the demo. This desk holds the hard step and still steals the machine."]),
        "H": kw.get("H", ["Caption ingest. Timestamps UNKNOWN. Tape $ UNVERIFIED."]),
        "I": kw.get("I", ["What is the exact stop if the demo had succeeded silently?"]),
        "J": kw.get("J", ["SYSTEM SYNTHESIS → `ask-principal` · `send-removed` · `confirm-then-actuate` · `input-required-gate`."]),
        "K": kw.get("K", ["Unknown future value of the draft/log/approve pattern. Parked."]),
        "machines": machines,
        "never_extra": kw.get("never_extra", []),
        "L": L,
    }

TAKES = {}

TAKES["bxGE_LXPyAU"] = pack(
    "I built an AI Agent in 2 hours (and got paid $2600)",
    "Nate Herk | AI Automation", "paid onboarding agent rebuild", 7729,
    [
        "Built in 2 hours, paid $2,600 UNVERIFIED (not the $1,200 story). Wireframe shown to the client first. Payment-processor webhook when a student paid → welcome email → Slack internal → CRM row.",
        "Flow 2: daily 2:00 p.m. cron checks paid-but-no-account rows and shoots a reminder email, then marks followed-up. Flow 3: human escalation. Flow 4: account made → AI writes a friendly welcome, shoots it, CRM + team notify 'student A onboarded, they've paid.'",
        "Postman mock: first/last/email/phone. Gmail send-a-message with dragged email. Slack send-a-message. He says more AI = more refine/test time; this one was simple enough to sell fast.",
    ],
    [src("Welcome + daily reminder are live Gmail sends on a paid webhook. Human-escalation exists as a third flow.",
         "$2,600 is a hook. The SKU is onboarding comms. Send is the world action.",
         "Paid webhook → CRM + Slack Evens → Evens sends welcome/reminder → stop",
         "On-tape: send a message operation; daily blast to however many rows (4/7/10).",
         "Steal wireframe + paid-trigger + Slack notify + escalation. Strip Gmail send and the 2 p.m. blast.",
         concept="Paid-onboard notify, Evens sends")],
    [{"name": "Paid webhook → Slack Evens (no blast)",
      "loop": "payment in → CRM row → Slack Evens → Evens sends welcome/reminder → stop",
      "qs": "Did they pay? Account made? Who sends?",
      "qf": "Daily reminder blast is a no. Quote $2,600 as FACT is a no.",
      "proc": "Keep webhook + CRM + Slack + escalation card. Strip Gmail send.",
      "ex": ex("Student paid", "Webhook → welcome Gmail + Slack", "Client bought onboarding", "Email shoots", "Notify is the steal; the shoot is never"),
      "why": "A paid trigger is a real machine. Auto-emailing students is still send.",
      "never": "Auto-welcome / 2 p.m. reminder blast. Quote $2,600 as FACT. Unpark a school list.",
      "hive": "`send-removed` · `ask-principal` · `inbox-to-task-routing` · `confirm-then-actuate`"}],
    "ACTION = Slack Evens on paid; REJECT welcome/reminder send. $2,600 UNVERIFIED. Clients parked.",
    never_extra=["Auto-welcome / daily reminder blast. Quote $2,600 as FACT."],
    J=["SYSTEM SYNTHESIS → `send-removed` · `ask-principal`. Sibling: `HNKlFTd1maM` (sold without send)."],
)

TAKES["zyvdl__Ywfk"] = pack(
    "Claude Code + Clay Makes Lead Generation Actually Easy",
    "Nate Herk | AI Automation", "Clay + Claude outreach", 4701,
    [
        "One prompt: find leads, enrich, write subject+body, put into a campaign. Clay on the back. Cold outreach fails on: right business, real contact, non-spammy copy.",
        "Claude → Clay: 50 leads like my avatar → scrape → enrich emails/phones → Claude writes personalized outreach → CSV → upload to Clay → buy domains, warm them, start the campaign from there. 'Easiest lead gen and outreach I've seen.'",
        "He says enrichment ≠ a client. Still: start-the-campaign is send. Claude + Clay stay on-tape. Clients parked. No new icp.",
    ],
    [src("Clay can buy domains, warm them, and start the campaign from the CSV Claude wrote.",
         "Research+draft+CSV is send-removed. Start-campaign is the trap. Hunt from a tape is never.",
         "Avatar in → enrich → draft CSV → Evens reviews → Evens or client sends → stop",
         "On-tape: 'we can just start the campaign right from there.'",
         "Steal enrich+draft CSV. Never Clay send, never unpark, never Claude.",
         concept="Enrich-and-draft CSV, no campaign start")],
    [{"name": "Enrich + draft CSV (no Clay send)",
      "loop": "avatar → Clay enrich → draft subject/body CSV → Evens reviews → stop",
      "qs": "Does Clay start the campaign? Are we hunting?",
      "qf": "Start-campaign is a no. New icp is a no. Claude/Clay as stack is a no.",
      "proc": "Keep enrich+copy. Strip send/warm/buy-domain operate. Clients parked.",
      "ex": ex("50 leads like X", "Claude writes copy, Clay can start campaign", "Easiest outreach", "CSV ready", "CSV is the steal; start is never"),
      "why": "He already said enrichment is not a client. Starting the campaign is send.",
      "never": "Clay auto-campaign. Buy/warm domains we operate. Unpark. Quote any close as FACT.",
      "hive": "`send-removed` · `warm-draft-hitl` · `playbook-before-send` · `ask-principal`"}],
    "ACTION = draft CSV; REJECT Clay start-campaign. No hunt. Clients parked.",
    never_extra=["Clay start-campaign / domain-warm. New icp. Unpark."],
)

TAKES["5p5cV0yVDvQ"] = pack(
    "Unlock the Full Power of Your n8n Agents (new instance MCP)",
    "Nate Herk | AI Automation", "instance MCP long cut", 3426,
    [
        "Native ChatGPT/Claude connectors don't actually let you send emails; his n8n Gmail workflow does — webhook in, Gmail node out.",
        "Demo: like the draft, 'use n8n to send that email to michael@dundermifflin.com,' 'we'll send that off now.' Also: connect instance MCP to Vappy later; blurb → automated AI roadmap.",
        "This is the talk-to-send trap. Sibling shorts already named always-allow MCP.",
    ],
    [src("Instance MCP + a Gmail workflow turns chat into send. Native connectors he says cannot send; his can.",
         "Talk-to-send is always-allow. Draft-like then send-off is the demo.",
         "Chat in → draft → Evens sends → stop",
         "On-tape: send to michael@dundermifflin.com; we'll send that off now.",
         "Steal MCP-as-tool-list. Never execute-send. Never Vapi.",
         concept="Talk-to-send is always-allow")],
    [{"name": "MCP lists tools; Evens sends",
      "loop": "chat → named Gmail draft tool → Evens → stop",
      "qs": "Can the MCP hit Send? Always-allow on?",
      "qf": "Send-that-off-now is a no. Vapi later is a no.",
      "proc": "Keep draft tool. Strip send. No always-allow.",
      "ex": ex("Like the draft", "use n8n to send to Michael", "Prove MCP does what ChatGPT cannot", "Send off now", "That proof is the never"),
      "why": "He sold MCP as the missing Send. That is why this desk exists.",
      "never": "Always-allow MCP send. Vapi hookup. Unpark Dundermifflin.",
      "hive": "`send-removed` · `input-required-gate` · `ask-principal`"}],
    "Long-cut of talk-to-send. ACTION = draft only; REJECT MCP execute-send. Clients parked.",
    never_extra=["Always-allow instance MCP send. Vapi via MCP."],
    J=["Siblings: `mPflFTQUCGk` · `9IzGe0BBj_c`. SYSTEM SYNTHESIS → `send-removed` · `input-required-gate`."],
)

TAKES["X80ljdCPM_U"] = pack(
    "Build ANYTHING with Claude Sonnet 4.5 and n8n AI Agents",
    "Nate Herk | AI Automation", "Sonnet + n8n tool demos", 4440,
    [
        "One-tool agent: send an email to nateample.com asking what's up. Contact DB → Michael Scott 20 minutes late. Research dogs vs cats + send email + create a calendar event for lunch. Voice-agent research → Michael.",
        "Build-anything includes send + book in the same breath.",
    ],
    [src("Demos chain research → send email → create calendar event.",
         "Anything includes the hard steps. Strip both writes.",
         "Research → draft + proposed slot → Evens sends/books → stop",
         "On-tape: send an email … create a calendar event for lunch.",
         "Steal research+contact lookup. Never send/create-event.",
         concept="Research then card, not send+book")],
    [{"name": "Research + lookup (Evens writes)",
      "loop": "ask → research/lookup → draft/slot → Evens → stop",
      "qs": "Send or create-event on the canvas?",
      "qf": "Build-anything is a no.",
      "proc": "Keep lookup. Strip Send and create-event.",
      "ex": ex("Dogs vs cats + lunch", "Send email + create event", "Show tools", "Both writes offered", "Two never in one demo"),
      "why": "A contact DB is useful. The writes are the trap.",
      "never": "Auto-send. Auto-create-event. Claude as stack.",
      "hive": "`send-removed` · `ask-principal` · `confirm-then-actuate`"}],
    "ACTION = lookup/draft; REJECT send+calendar. Clients parked.",
    never_extra=["Send + create-event in one graph."],
)

TAKES["Vb1SwBAn9cQ"] = pack(
    "Build ANYTHING with Gemini 3 Pro and n8n AI Agents",
    "Nate Herk | AI Automation", "Gemini 3 + n8n", 5836,
    [
        "Gemini 3 'new era' UNVERIFIED. Fireflies transcript → internal brief. Tool calling needs a thought-signature field or n8n breaks. He sends: email nateample.com asking if he wants lunch this weekend.",
    ],
    [src("The anything-demo is a Gmail send about lunch.",
         "Brief-from-transcript is the steal. Send is the trap.",
         "Transcript → brief → Evens sends if ever → stop",
         "On-tape: send an email to nateample.com … lunch this weekend.",
         "Steal the brief. Never the send. Gemini on-tape.",
         concept="Transcript brief, no lunch-send")],
    [{"name": "Transcript → brief (Evens sends)",
      "loop": "call transcript → internal brief → Evens → stop",
      "qs": "Is Gmail on the canvas?",
      "qf": "Lunch-send is a no. Gemini as stack is a no.",
      "proc": "Keep Fireflies→brief. Strip Send.",
      "ex": ex("Prove tool calling", "Send lunch email", "Thought signature aside", "Mail offered", "The proof write is never"),
      "why": "Internal brief is useful. The demo write is send.",
      "never": "Auto-send. Gemini as stack.",
      "hive": "`send-removed` · `ask-principal` · `inbox-to-task-routing`"}],
    "ACTION = internal brief; REJECT lunch-send. Clients parked.",
)

TAKES["TDHFkKSTJ30"] = pack(
    "n8n's Agent Builder Somehow Made Building Agents Easier",
    "Nate Herk | AI Automation", "n8n agent builder", 4694,
    [
        "ChatGPT-like builder. Prompt: webhook form (company, budget, project) → hot/warm/cold via research → Gmail/Slack alert. Also newsletter writer → HTML → send to a recipient he fills in.",
        "He says Gmail/calendar sub-agents should have all tools, not just send-message / create-event. That sentence is the always-allow.",
    ],
    [src("Builder happy-path is Gmail/Slack alert and newsletter send. He wants sub-agents to have all write tools.",
         "All-tools on Gmail/calendar is talk-to-send. Form→research→alert can stay a Slack card.",
         "Form in → research → Slack Evens → Evens sends → stop",
         "On-tape: newsletter → HTML → send to a recipient; give Gmail all tools.",
         "Steal form+research+Slack. Never all-tools send. Never newsletter send.",
         concept="Builder alert is a card, not all-tools send")],
    [{"name": "Form → research → Slack Evens",
      "loop": "webhook form → research hot/warm/cold → Slack Evens → stop",
      "qs": "Gmail all-tools? Newsletter send?",
      "qf": "All-tools sub-agent is a no.",
      "proc": "Keep classify+Slack. Strip Gmail/calendar writes.",
      "ex": ex("Newsletter writer", "HTML then send to recipient", "Show the builder", "He fills the recipient", "Recipient field is send"),
      "why": "A builder that defaults to send will be copied as send.",
      "never": "All-tools Gmail/calendar. Newsletter auto-send.",
      "hive": "`send-removed` · `ask-principal` · `input-required-gate`"}],
    "ACTION = Slack the form research; REJECT all-tools send. Clients parked.",
    never_extra=["Gmail/calendar all-tools. Newsletter send from the builder."],
)

TAKES["lcNN3X9gXls"] = pack(
    "3 Hidden Data Table Hacks for Smarter AI Agents",
    "Nate Herk | AI Automation", "native tables + calendar demo", 3791,
    [
        "Native data tables so agents skip Sheets/Airtable API. Error workflow → logger. Demo: call contact agent for Michael Scott then calendar agent to create that event. Think tool; research prompt stored in the table.",
    ],
    [src("The third hack demo creates a calendar event for Michael Scott.",
         "Tables as memory are the steal. Create-event is book.",
         "Lookup contact → propose slot → Evens books → stop",
         "On-tape: calendar agent to create that event.",
         "Steal table-as-memory + error logger. Never create-event.",
         concept="Table memory, Evens books")],
    [{"name": "Table lookup (Evens books)",
      "loop": "ask → table/contact lookup → proposed event → Evens → stop",
      "qs": "Does the calendar agent create-event?",
      "qf": "Create-that-event is a no.",
      "proc": "Keep tables + error log. Strip create-event.",
      "ex": ex("Michael Scott", "Contact then calendar create", "Show the hack", "Event create offered", "Lookup is steal; create is never"),
      "why": "A local table is a good brain. The demo write is book.",
      "never": "Auto-create-event.",
      "hive": "`ask-principal` · `confirm-then-actuate` · `private-book-install`"}],
    "ACTION = lookup in the table; REJECT create-event. Clients parked.",
)

TAKES["vFepZE_wrfg"] = pack(
    "How to Build $10,000 Agentic Workflows (Claude Code + n8n)",
    "Nate Herk | AI Automation", "newsletter as $10k exhibit", 6850,
    [
        "Agentic market $ figures UNVERIFIED. Live build: newsletter — Perplexity research, Claude write, Nano Banana infographics, HTML, send via Gmail, archive to Sheets. He chooses Gmail over Beehiiv. Subject-line approval then send.",
        "$10,000 in the title. Subject-line approval is the HITL crumb before send.",
    ],
    [src("Subject-line approval then Gmail send. $10k is a hook.",
         "Approval node is the steal. Send is still send. Claude on-tape.",
         "Research → HTML → subject card → Evens sends → stop",
         "On-tape: subject-line approval then send via Gmail.",
         "Steal the subject card + research chain. Never auto-send. $10k UNVERIFIED.",
         concept="Subject-line card, then Evens sends")],
    [{"name": "Research → HTML → subject card (Evens sends)",
      "loop": "research → write → HTML → Evens approves subject → Evens sends → stop",
      "qs": "Is approval only the subject? Does Gmail send after yes?",
      "qf": "Subject-yes is not list-send. $10k as FACT is a no.",
      "proc": "Keep research+card. Strip Gmail send. No Claude.",
      "ex": ex("$10k workflow", "Newsletter to Gmail after subject approval", "Looks like a product", "Send via Gmail", "The card is real; the send is never"),
      "why": "He put an approval in. He still sends. We keep the card and drop the node.",
      "never": "Auto-send after subject-yes. Quote $10k/$7B as FACT. Claude as stack.",
      "hive": "`send-removed` · `ask-principal` · `input-required-gate` · `warm-draft-hitl`"}],
    "ACTION = subject card + draft; REJECT Gmail send. $10k UNVERIFIED. Clients parked.",
    never_extra=["Gmail send after subject-yes. Quote $10k as FACT."],
    J=["Sibling: `pxzo2lXhWJE`. SYSTEM SYNTHESIS → `send-removed` · `input-required-gate`."],
)

TAKES["tFFKuq2t0rI"] = pack(
    "Build ANYTHING with Base44 and n8n AI Agents (beginner)",
    "Nate Herk | AI Automation", "Base44 lead-magnet + book", 6160,
    [
        "Base 44 = talk-to-a-software-engineer web apps; n8n on the back. Lead magnet: name/email/problem → AI implementation roadmap emailed; close 'if you want more, book in a call' + discovery-call link. Tiny input → directly to their inbox + free value to convince them to book. If someone submits 1,000 requests, you pay.",
    ],
    [src("The magnet emails a roadmap and asks them to book a call. Inbox + book are both hard steps.",
         "Form→roadmap draft is the steal. Auto-email + book-link-as-close is the trap. Base44 on-tape.",
         "Form in → generate roadmap → Evens sends → Evens books if they ask → stop",
         "On-tape: directly to their inbox; book in a call.",
         "Steal the magnet form + roadmap. Never auto-email or auto-book.",
         concept="Roadmap draft, Evens sends and books")],
    [{"name": "Magnet → roadmap draft (Evens sends/books)",
      "loop": "name/email/problem → roadmap draft → Evens sends → book stays a card → stop",
      "qs": "Does it email them? Does it drop a book link?",
      "qf": "Directly-to-inbox is a no. Book-in-a-call closer is a no. Base44 is a no.",
      "proc": "Keep the form fields. Strip Gmail and calendar. 1,000-request cost UNVERIFIED.",
      "ex": ex("Lead magnet", "Roadmap emailed + book a call", "Free value to close", "Inbox + link", "Draft the roadmap; Evens sends"),
      "why": "A tiny form is a good front. The operated back emails and books.",
      "never": "Auto-email roadmap. Auto-book. Base44 as stack. Quote 1,000-request cost as FACT.",
      "hive": "`send-removed` · `ask-principal` · `private-book-install` · `outcome-offer-funnel`"}],
    "ACTION = draft the roadmap; REJECT inbox-send and book-link operate. Clients parked.",
    never_extra=["Auto-email magnet. Auto-book. Base44 as stack."],
)

TAKES["AYsg5gAMWyo"] = pack(
    "I Built the Ultimate UGC Content System with AI Agents",
    "Nate Herk | AI Automation", "UGC VO3/Sora/Banana", 6230,
    [
        "Sheet: product photo, ICP, features, setting; pick V3.1 / Banana+V3.1 / Sora 2. Agents prompt-optimize. Sora rejects a realistic-human source image. He says you could auto-post with a branch, but he probably would not auto-post VO3/Sora because the first frames are the still.",
        "Spoken no-auto-post is the steal. The branch still exists.",
    ],
    [src("He names an auto-post branch and then says he probably would not, because the first frames look like the still.",
         "Cut + human pick is the steal. Auto-post is still on the canvas. ICP column is not a hive icp.",
         "Photo+features → generate → human pick → Evens publishes → stop",
         "On-tape: 'you could … have it auto post as well … but I probably wouldn't.'",
         "Steal the sheet + model pick + his own no-auto-post. Never the branch. No new icp.",
         concept="UGC cut, Evens posts")],
    [{"name": "Sheet → cut → Evens publishes",
      "loop": "photo+features → generate → human pick → Evens posts → stop",
      "qs": "Is auto-post on the canvas? Did we invent an icp?",
      "qf": "Auto-post is a no even if first-frames improve. New icp is a no.",
      "proc": "Keep sheet + generate. Strip post. Park ICP column as demo data.",
      "ex": ex("Auto-post branch", "He says probably not because first frames", "Quality excuse", "Branch still there", "We refuse the branch, not just the frames"),
      "why": "He already flinched at auto-post. We keep the flinch as policy.",
      "never": "Auto-post UGC. New icp from the sheet. Sora/VO as stack.",
      "hive": "`product-ad-from-photo` · `clip-factory` · `ask-principal` · `one-channel-deep`"}],
    "ACTION = generate cuts; REJECT auto-post. His probably-not is our never. Clients parked.",
    never_extra=["Auto-post UGC. New icp from the demo sheet."],
    J=["Sibling: `Vm8QOo9MiC4` · `jBanaNBY-sM`. SYSTEM SYNTHESIS → `clip-factory` · `product-ad-from-photo`."],
)

TAKES["Vm8QOo9MiC4"] = pack(
    "Create ANYTHING with Sora 2 + n8n AI Agents (Full Guide)",
    "Nate Herk | AI Automation", "Sora 2 course", 6830,
    [
        "Sora 2 via n8n — 10× output, no watermarks, 6× cheaper than OpenAI direct UNVERIFIED. Starbucks-style audio+video. UGC ads convert on TikTok shop; agents pump scripts + prompts; new person every time, look very real.",
        "Create-anything + TikTok-shop is publish-adjacent. Generate ≠ post.",
    ],
    [src("UGC that looks real and converts on TikTok shop is the pitch. The machine we steal is generate-then-pick.",
         "Anything includes post. Tape $ UNVERIFIED. Sora on-tape.",
         "Brief → generate → human pick → Evens publishes → stop",
         "On-tape: UGC ads convert on TikTok shop; agents pump scripts.",
         "Steal generate+pick. Never auto-post. No Sora stack.",
         concept="Sora cuts, Evens publishes")],
    [{"name": "Generate UGC, Evens publishes",
      "loop": "brief → Sora/n8n generate → pick → Evens posts → stop",
      "qs": "Does any node post to TikTok shop?",
      "qf": "Create-anything-post is a no. Quote 10×/6× as FACT is a no.",
      "proc": "Keep generate. Strip post. Sora on-tape.",
      "ex": ex("TikTok shop UGC", "Agents pump scripts+prompts", "Looks real", "Convert pitch", "Look-real is not permission to post"),
      "why": "Volume of cuts is useful. Shop-post is publish.",
      "never": "Auto-post TikTok shop. Sora as stack. Quote 10×/6× as FACT.",
      "hive": "`clip-factory` · `product-ad-from-photo` · `ask-principal`"}],
    "ACTION = generate cuts; REJECT shop-post. Clients parked.",
    never_extra=["Auto-post TikTok shop. Quote 10×/6× as FACT. Sora as stack."],
)

TAKES["-cdexJWN8YA"] = pack(
    "Building Realistic Voice Agents Has Never Been Easier",
    "Nate Herk | AI Automation", "website voice widget + tools", 7804,
    [
        "Start-call on a site: Nate's AI trained on YouTube. Widget, or Twilio number that can call people or pick up. Tools: API, n8n, Python, Zapier, vector/NotebookLM. Persona = system prompt. Claude Code plan mode to build by talking instead of clicking a dashboard.",
        "Today = embed. He still names outbound call-people as a path. ElevenLabs on-tape.",
    ],
    [src("A website widget that can also be paired to Twilio to call people. Tools can hit n8n/Zapier.",
         "Talk-to-a-knowledge-base is the steal. Call-people + tool-write is the trap.",
         "Widget in → answer from docs → log → Evens if they want a call/book → stop",
         "On-tape: pair with a phone number … call people from that number.",
         "Steal widget+persona+plan-mode. Never Twilio outbound. Never ElevenLabs/Claude stack.",
         concept="Widget Q&A, Evens dials")],
    [{"name": "Site widget Q&A (Evens dials)",
      "loop": "visitor talks → knowledge answer → log → Evens dials/books if needed → stop",
      "qs": "Twilio outbound? Can tools send/book?",
      "qf": "Call-people is a no. ElevenLabs/Claude as stack is a no.",
      "proc": "Keep persona + transcript KB. Strip phone-out and write-tools.",
      "ex": ex("Start call on the site", "Talks from YouTube knowledge", "Embed demo", "Also names Twilio call-people", "Embed Q&A is steal; outbound is never"),
      "why": "A talking FAQ is useful. A number that calls people is dial.",
      "never": "Twilio/Vapi/ElevenLabs outbound. Tool-call send/book. Claude as builder-stack.",
      "hive": "`ask-principal` · `demo-walk-script` · `confirm-then-actuate`"}],
    "ACTION = widget Q&A log; REJECT call-people. Clients parked.",
    never_extra=["Twilio/ElevenLabs outbound. Voice tool-write."],
)

TAKES["Qt3zMBH-FNg"] = pack(
    "Gemini 3.1 Flash Live Just Changed Voice Agents Forever",
    "Nate Herk | AI Automation", "Gemini live voice", 4270,
    [
        "Speech-to-speech, interrupt feels human. Function calling / 'hands': calendar, emails, support tickets. Google AI Studio coach persona. Claude Code to embed tool calls. Skool scroll demo (Vishal Claude limits).",
        "Talking leads to things actually happening — vibe-code by voice. OS-by-voice future.",
    ],
    [src("Live voice + function calling is calendar/email hands. Talking leads to things happening.",
         "Interrupt-UX is not a gate. Hands are send/book.",
         "Talk → maybe look up → Evens on calendar/email → stop",
         "On-tape: you might want it to do things in your calendar or look at the emails.",
         "Steal interrupt/persona. Never Gemini hands on calendar/email. No Claude embed.",
         concept="Live voice look-up, Evens writes")],
    [{"name": "Live voice look-up (Evens writes)",
      "loop": "talk → read-only answer → Evens on calendar/email → stop",
      "qs": "Are functions on? Calendar or Gmail?",
      "qf": "Hands that happen are a no. Gemini/Claude as stack is a no.",
      "proc": "Keep persona + interrupt demo as UX notes. Strip function writes.",
      "ex": ex("Give it hands", "Calendar or emails", "Studio functions", "Docs say define functions", "Hands = book/send"),
      "why": "A faster mouth is not a faster write we operate.",
      "never": "Gemini function-call calendar/email. Claude embed. Quote 19% bench as FACT.",
      "hive": "`ask-principal` · `confirm-then-actuate` · `send-removed`"}],
    "ACTION = voice look-up; REJECT calendar/email hands. Clients parked.",
    never_extra=["Gemini live function-call send/book."],
)

TAKES["xJ5oz63mIec"] = pack(
    "How to Deploy Your Claude Automations (3 Methods)",
    "Nate Herk | AI Automation", "deploy-while-you-sleep", 5337,
    [
        "Three ways to deploy so they run while you sleep. WAT: what actually gets deployed. Method 1: Claude cron create/list/delete + /loop; session-scoped; clear-chat can kill; some crons survive. Natural-language schedule.",
        "While-you-sleep deploy is the title. Claude stays on-tape. Unattended world-action is never.",
    ],
    [src("Deploy so they run while you sleep. Crons inside Claude Code.",
         "Named schedule + kill-switch is the steal. Sleep-deploy of send/book is the trap.",
         "Name the job → test watched → schedule only no-send → Evens on writes → stop",
         "On-tape: deploy those agents so that they run while you sleep; cron create.",
         "Steal named cron + delete. Never sleep-send. No Claude deploy.",
         concept="Watched cron, no sleep-write")],
    [{"name": "Named cron + kill (no sleep-write)",
      "loop": "name job → Run watched → schedule no-send only → cron delete if needed → stop",
      "qs": "Does the cron send/book/publish? Laptop-closed?",
      "qf": "While-you-sleep write is a no. Claude deploy is a no.",
      "proc": "Steal cron list/delete hygiene. Do not deploy Claude. No world action in the cron.",
      "ex": ex("Three deploy methods", "Cron /loop while you sleep", "WAT frame", "Session-scoped vs surviving", "Survive-across-sleep is the risk"),
      "why": "A killable named job is useful. Sleep is when this desk must already have stripped the write.",
      "never": "Deploy-while-you-sleep with send/book/publish. Claude as runtime. Quote any uptime as FACT.",
      "hive": "`coverage-loop` · `ask-principal` · `input-required-gate`"}],
    "ACTION = named no-send cron; REJECT sleep-deploy of writes. Clients parked.",
    never_extra=["While-you-sleep deploy of send/book/publish. Claude as runtime."],
    J=["Siblings: `ehg4fhydTgs` · `UGIZnh6HNLc`. SYSTEM SYNTHESIS → `coverage-loop` · `ask-principal`."],
)

TAKES["UGIZnh6HNLc"] = pack(
    "The EASIEST Way to Host Your Claude Code Agents",
    "Nate Herk | AI Automation", "Trigger.dev host", 5267,
    [
        "Trigger.dev ~1.5 hours in: YouTube-highlight job, ClickUp research agent that comments. Push Claude project → GitHub → Trigger.dev production. Keys in .env or it will not work. Hand each lead to a hosted agent.",
        "Host = unattended. Comment-on-ClickUp is already a write. Claude/Trigger.dev on-tape.",
    ],
    [src("Hosted Claude that comments in ClickUp and can be handed leads.",
         "Git-push hygiene is the steal. Production host that writes is deploy+send.",
         "Repo → review → Evens comments/sends → stop",
         "On-tape: ClickUp agent that comments; production; hand each lead.",
         "Steal .env-not-in-git + review-before-prod. Never Trigger.dev/Claude host. Never lead-hand.",
         concept="Review-before-host, no comment-write")],
    [{"name": "Review-before-host (no comment-write)",
      "loop": "build locally → Evens reviews → no unattended write in prod → stop",
      "qs": "Does prod comment/email/call? Keys in git?",
      "qf": "Easiest-host is a no. Hand-each-lead is a no.",
      "proc": "Keep .env hygiene. Do not host Claude. Do not comment-as-the-agent.",
      "ex": ex("ClickUp research agent", "Comments and converses in prod", "1.5 hours to host", "Lead-hand demo", "Hosted comment is a write"),
      "why": "Easy host is unattended write. This desk does not deploy that.",
      "never": "Trigger.dev/Claude production writes. Hand leads to a hosted sender. Keys in chat.",
      "hive": "`ask-principal` · `coverage-loop` · `input-required-gate`"}],
    "ACTION = local review; REJECT hosted comment/lead-hand. Clients parked.",
    never_extra=["Trigger.dev/Claude hosted writes. Hand leads to prod."],
)

TAKES["iTY8Q449YNQ"] = pack(
    "I asked Claude Code to make me as much money as possible",
    "Nate Herk | AI Automation", "money-aim + scheduled posting", 7392,
    [
        "Four upgrades so Claude makes money not waste. Devil's advocate before it builds or approves a plan. Narrow paying niche; moat = provable voice matching + direct scheduled posting. Before code: pick one niche, DM or email 20–30, see if they pay.",
        "Capacity story: they shot emails to people who wanted to work with them. Council of personas. Claude on-tape. 20–30 DM is hunt. Scheduled posting is publish.",
    ],
    [src("The money-aim names scheduled posting as a moat and DM/email 20–30 as the 48-hour test.",
         "Devil's-advocate-before-approve is the steal. Hunt + auto-post are the trap. No new icp.",
         "Idea → devil's advocate → Evens approves plan → Evens DMs/posts if ever → stop",
         "On-tape: direct scheduled posting; DM or email 20 to 30 of them.",
         "Steal pushback-before-plan. Never scheduled post. Never 20–30 outreach. No Claude.",
         concept="Devil's advocate, then Evens (no hunt)")],
    [{"name": "Pushback-before-plan (no hunt, no scheduled post)",
      "loop": "idea → devil's advocate → Evens approves → no DM/post unless Evens → stop",
      "qs": "Did it approve its own plan? Does it schedule posts? Are we DMing 20?",
      "qf": "Scheduled posting moat is a no. 20–30 DM is a no. New icp is a no.",
      "proc": "Keep challenge-before-build. Strip post/send. Clients parked.",
      "ex": ex("Make me money", "Moat = scheduled posting; test = DM 20–30", "Money read", "48h test named", "The test is hunt; we do not run it"),
      "why": "Stress-test is useful. The operated test is outreach and auto-post.",
      "never": "Scheduled posting. DM/email 20–30. New icp. Claude as stack. Quote 3× money as FACT.",
      "hive": "`ask-principal` · `discovery-spiced-constraint` · `one-channel-deep`"}],
    "ACTION = devil's advocate then Evens; REJECT scheduled post and 20–30 DM. Clients parked.",
    never_extra=["Scheduled posting. DM/email 20–30 hunt. Quote 3× money as FACT."],
    J=["SYSTEM SYNTHESIS → `ask-principal` · `discovery-spiced-constraint`. Do not unpark."],
)

TAKES["AO5aW01DKHo"] = pack(
    "Agentic Workflows Just Changed AI Automation Forever",
    "Nate Herk | AI Automation", "agentic vs node + guardrail talk", 5774,
    [
        "Old n8n = you own every node; agentic = outcome in English. Live lead-gen: scrape, Sheet, analysis. Guardrails he types: never send customer phone numbers to any third party; stop if you ever exceed $5 of usage. Fireflies → ClickUp → Gmail summary. Publish scripts to Modal so they run without the laptop.",
        "Never-send-phones is a prompt. Gmail summary is send. Modal is deploy-while-away.",
    ],
    [src("He types 'never send phones' as a guardrail, then ships Fireflies→Gmail summary and Modal so it runs without the laptop.",
         "Prompt-never is not a lock (see RzLV8sfFdMM). Gmail summary is send. Modal is unattended.",
         "Scrape → sheet → Evens on any Gmail/Modal write → stop",
         "On-tape: never send customer phone numbers; Gmail summary; Modal without you.",
         "Steal the written never + $ cap as ideas. Never treat them as gates. No Modal/Claude.",
         concept="Prompt-never is not the send gate")],
    [{"name": "Sheet + analysis (Evens sends; no Modal)",
      "loop": "scrape → sheet → analysis → Evens on Gmail → stop",
      "qs": "Gmail summary? Modal? Only a never-prompt?",
      "qf": "Prompt-never as lock is a no. Laptop-off Gmail is a no.",
      "proc": "Keep sheet+analysis. Strip Gmail and Modal. $5 cap UNVERIFIED.",
      "ex": ex("Guardrail: never send phones", "Also Gmail summary + Modal", "Looks safe", "Unattended path exists", "Typed never ≠ Evens"),
      "why": "He wrote our never as a string. He still sent. We keep Evens.",
      "never": "Gmail summary auto. Modal unattended. Prompt-never as the only lock. Quote $5 cap as FACT.",
      "hive": "`send-removed` · `ask-principal` · `input-required-gate`"}],
    "ACTION = sheet analysis; REJECT Gmail/Modal. Prompt-never is not Evens. Clients parked.",
    never_extra=["Gmail summary auto. Modal unattended. Prompt-never as the lock."],
    J=["Sibling: `RzLV8sfFdMM` (assume-it-will-touch). SYSTEM SYNTHESIS → `send-removed`."],
)

TAKES["3GAxd90fEE4"] = pack(
    "How I’d Teach a 10 Year Old to Build Agentic Workflows",
    "Nate Herk | AI Automation", "agentic 10-year-old frame", 8148,
    [
        "Agentic workflows fix themselves and can be 10× faster UNVERIFIED. Traditional = recipe; agentic = say the outcome. Close: agents that improve themselves while you sleep; builders → architects.",
        "Sleep-improve + outcome-not-nodes is the pitch. Outcome still cannot include send/book we operate.",
    ],
    [src("Teach outcome-not-nodes, then close on improve-while-you-sleep.",
         "Outcome-offer is the steal. Sleep-autonomy on a world action is the trap.",
         "Say the outcome → draft → Evens on write → stop",
         "On-tape: improve themselves while you sleep.",
         "Steal outcome language. Never sleep-write. 10× UNVERIFIED.",
         concept="Outcome draft, no sleep-write")],
    [{"name": "Outcome → draft (no sleep-write)",
      "loop": "name outcome → build draft → Evens on send/book → stop",
      "qs": "Does sleep-improve include send?",
      "qf": "While-you-sleep is a no. 10× as FACT is a no.",
      "proc": "Keep outcome-not-nodes. Strip unattended writes.",
      "ex": ex("Teach a 10-year-old", "Say the outcome", "Then: improve while you sleep", "Architect pitch", "Outcome ≠ unattended send"),
      "why": "Simple outcome language is good teaching. Sleep is the never.",
      "never": "Improve-while-you-sleep with send/book/publish. Quote 10× as FACT.",
      "hive": "`outcome-offer-funnel` · `ask-principal` · `coverage-loop`"}],
    "ACTION = outcome draft; REJECT sleep-improve writes. Clients parked.",
    never_extra=["While-you-sleep self-improve on a world action. Quote 10× as FACT."],
)

TAKES["YHk45NEpspE"] = pack(
    "This is The Most Powerful Tool to Give to Claude Code",
    "Nate Herk | AI Automation", "Printing Press CLI + Skool", 3697,
    [
        "Claude: go to my Skool and grab posts — no API — CLI finds nine wins, picks three strongest. Printing Press: factory + library of CLIs. More token-efficient than MCP. He can only post a certain amount of comments per day through the API. Publish CLIs back to the library.",
        "Read Skool is observe. Post comments is publish. Claude/Skool on-tape.",
    ],
    [src("CLI that reads Skool wins and can post comments (rate-limited).",
         "Read+rank is the steal. Post-comment is publish. Do not join Skool.",
         "Ask → CLI read → rank three → Evens posts if ever → stop",
         "On-tape: grab posts; I can only post a certain amount of comments per day.",
         "Steal CLI-read + rank. Never auto-comment. No Claude/Skool.",
         concept="CLI read+rank, Evens posts")],
    [{"name": "CLI read + rank (Evens posts)",
      "loop": "ask → CLI fetch → rank → Evens comments/publishes → stop",
      "qs": "Does the CLI post comments?",
      "qf": "Auto-comment is a no. Skool/Claude as stack is a no.",
      "proc": "Keep read+rank. Strip post. Do not install Printing Press as hive stack.",
      "ex": ex("Grab Skool wins", "Nine posts, three strongest", "Also: daily comment cap", "Publish-back to library", "Rank is steal; comment is never"),
      "why": "A read-only CLI is a tool. A comment API is publish.",
      "never": "Auto-comment Skool. Claude as stack. Publish CLI as a hive SKU.",
      "hive": "`ask-principal` · `one-channel-deep` · `clip-factory`"}],
    "ACTION = read+rank; REJECT auto-comment. Clients parked.",
    never_extra=["Auto-comment Skool. Claude/Printing Press as stack."],
)

if __name__ == "__main__":
    for vid, t in TAKES.items():
        p = write_one(vid, t)
        print("wrote", vid, p.stat().st_size)
    print("batch8", len(TAKES))
