#!/usr/bin/env python3
"""Batch 1: short Nate tapes already fully read."""
from _hitl_dvl_writer import write_one

def src(claim, why, mech, ev, act, **kw):
    return {"concept": kw.pop("concept"), "claim": claim, "why": why, "mech": mech, "ev": ev, "act": act, **kw}

def ex(sit, act, why, out, les, name="On-tape run"):
    return {"name": name, "sit": sit, "act": act, "why": why, "out": out, "les": les}

TAKES = {}

TAKES["NWbh5ZoEHkA"] = {
    "title": "Agentic Arena: Dr Pure Eval was pure evil...",
    "speaker": "Agentic Arena / Nate (on-tape)",
    "kind": "short / arena clip",
    "words": 67,
    "A": [
        "Host: 'Fake it till you make it' then a run scores three.",
        "Second run: something special — the agent used a calculator tool.",
        "Aside: why add the tool? Speaker: LLMs aren't great at math; if math is needed, use the tool.",
        "Music sting. Clip ends.",
    ],
    "atoms": [src(
        "LLMs fail math; give them a calculator tool instead of trusting the model.",
        "He added the tool because he needed math and did not trust the model to do it.",
        "Agent run → tool call (calculator) → scored three.",
        "On-tape: 'LLMs aren't great at math' + 'it made use of the calculator tool.'",
        "Steal tool-for-weakness. Do not treat a score of three as FACT.",
        concept="Tool for what the model cannot do",
    )],
    "C": [
        "Competence is demonstrated, not claimed ('fake it till you make it' is the host line; the proof is the tool call).",
        "Tools exist because the model is weak in a known domain, not because more autonomy is better.",
    ],
    "D": [
        "If the job is arithmetic, attach a calculator (or equivalent) before trusting the output.",
        "Watch the second run for the tool call — first run score is not the lesson.",
    ],
    "E": [ex("Arena agent needed math", "Add calculator tool", "Models fail arithmetic", "Second run uses the tool and scores three", "A checkable tool is the gate, not a vibe score")],
    "F": ["If the task is math → force a tool, do not accept freeform numbers.", "If a demo score is shown → treat as UNVERIFIED theater."],
    "G": ["Field assumes bigger models fix math. He assumes they do not — add a tool."],
    "H": ["Survivorship: one clip, one tool. Score 'three' is arena theater, not a hive metric.", "Timestamp UNKNOWN."],
    "I": ["What happens when the calculator is wrong? Tape does not say.", "Is 'fake it till you make it' his doctrine or the host's joke?"],
    "J": ["SYSTEM SYNTHESIS → `golden-test-loop`: untrusted worker + cheap check.", "SYSTEM SYNTHESIS → HITL: a score is not Evens."],
    "K": ["Arena clips as a catalog of 'when to force a tool' later, unassigned."],
    "machines": [{
        "name": "Force a tool where the model is known-weak",
        "loop": "task type (math) → attach tool → run → check tool was called → stop",
        "qs": "Is this arithmetic / lookup / send? If send, stop.",
        "qf": "Qualify the task class before the run.",
        "proc": "Do not accept a number the model invented. Require the calculator (or refuse).",
        "ex": ex("Second arena run", "Calculator attached", "LLMs fail math", "Tool used, score three", "Tool call is the checkable stop"),
        "why": "He states the weakness and shows the tool. Autonomy without the tool is the failure mode.",
        "never": "Auto-score as FACT. Auto-send because a tool exists.",
        "hive": "`golden-test-loop` · `ask-principal` if the number moves money",
    }],
    "L": "This desk steals 'known-weak → force a tool' as a card reason. A demo score is not APPROVE. If a later workflow uses a calculator to price or quote, the quote still sits on ACTION / WHY / AGENT / RISK / REVERSIBILITY. Clients parked.",
}

TAKES["NO97pqqc10A"] = {
    "title": "Agentic Arena: AI Trivia Bot & Robot Smackdowns!",
    "speaker": "Agentic Arena / Nate (on-tape)",
    "kind": "short / arena clip",
    "words": 99,
    "A": [
        "Nate uses a co-pilot power-up so ChatGPT generates a system prompt for his AI agent.",
        "Someone says 'we using five' / 'pretty smart' / 'sometimes it has some issues.'",
        "Host cheers a robot that will be hit if players do not have a perfect score.",
        "They may have designed one question that is very hard.",
    ],
    "atoms": [src(
        "A generated system prompt is a starting artifact, not a finished agent.",
        "He likes the generated prompt but notes it 'sometimes has some issues.'",
        "Co-pilot / ChatGPT writes the prompt → human still plays the arena.",
        "On-tape: ChatGPT generates the system prompt; 'pretty smart' + issues.",
        "Steal prompt-as-draft. ChatGPT stays on-tape.",
        concept="Generated prompt is a draft",
    )],
    "C": ["Generated text can be 'pretty smart' and still wrong. Issues are expected.", "Perfect score is a game rule that punishes the robot — theater, not ops."],
    "D": ["Generate a prompt → read it → expect issues → do not ship the first draft.", "Hard questions are designed; do not treat a fail as model death."],
    "E": [ex("Need a trivia-agent prompt fast", "Ask ChatGPT via co-pilot power-up", "Faster than writing from zero", "Prompt exists; 'sometimes issues'", "Draft ≠ live agent")],
    "F": ["If a vendor writes the system prompt → treat as draft, not policy.", "If a game punishes a robot for imperfect score → do not import that stop into hive ops."],
    "G": ["Field treats prompt-gen as the product. He treats it as a power-up with issues."],
    "H": ["ChatGPT / co-pilot are on-tape vendors.", "Perfect-score robot is entertainment."],
    "I": ["Which issues? Tape does not list them.", "What is 'using five'?"],
    "J": ["SYSTEM SYNTHESIS → `session-bootstrap`: dump then refine.", "SYSTEM SYNTHESIS → `ask-principal`: generated prompt is not approve."],
    "K": ["Arena power-ups as a catalog of 'draft vs live' later."],
    "machines": [{
        "name": "Vendor-written prompt stays a draft",
        "loop": "need prompt → generate → read for issues → human edits → stop (do not activate)",
        "qs": "Did a human read the prompt? Are tools send/book in it?",
        "qf": "If the prompt can send or book, it is a card.",
        "proc": "Never paste a generated prompt into a live voice/email agent without Evens.",
        "ex": ex("Arena needs a system prompt", "ChatGPT writes it", "Speed", "Smart + issues", "Issues mean HITL edit"),
        "why": "He says it has issues. Issues on a live book/send path are irreversible.",
        "never": "ChatGPT as our stack. Auto-activate a generated booking prompt.",
        "hive": "`session-bootstrap` · `ask-principal`",
    }],
    "L": "Hold generated system prompts as drafts. If the prompt includes book/send/call, format the five-field card. Do not import arena 'perfect score or the robot gets hit' as a hive stop. Clients parked.",
}

TAKES["5IM27lbCwjM"] = {
    "title": "How I Sold My First AI Agent From Content",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 136,
    "A": [
        "How he sold: client found him on YouTube because he built something similar for fun.",
        "Client emailed. Couple of calls. Scoped. He said he could do it. Client said yes.",
        "He was not positioning as a freelancer or saying he did paid work.",
        "Email was in the video description. Posting builds because he was excited to learn.",
        "Putting himself out there → inbound → first deals.",
    ],
    "atoms": [src(
        "First paid agent came from publishing a similar build, not from outbound.",
        "The client already wanted 'something similar' — the video was the proof.",
        "YouTube build → email in description → inbound email → calls → scope → yes.",
        "On-tape sequence: found on YouTube → emailed → calls → scoped → yes.",
        "Steal inbound-from-published-build. Do not start a hunt.",
        concept="Inbound from a public similar build",
    )],
    "C": ["Learning in public is the funnel; paid work is a side effect, not the pose.", "He did not lead with 'I am for hire.'"],
    "D": ["Publish the build. Put a reachable email in the description. Wait for inbound.", "On inbound: hop on calls, scope, say you can do it, wait for yes.", "Do not claim freelancer identity as the offer."],
    "E": [ex("Had built something similar for fun", "Left email in description", "Excited to learn, not hunting", "Client emailed, calls, scoped, yes", "Proof artifact beats a hire pose")],
    "F": ["If no similar public build exists → do not fake a sales page this week.", "If inbound arrives → scope on calls; do not auto-send a proposal.", "Clients stay parked this session — this is learn, not hunt."],
    "G": ["Field assumes you must position as a freelancer. He sold without that pose."],
    "H": ["Survivorship: one first deal story. Other viewers emailed and got nothing — not on tape.", "No $ on this short."],
    "I": ["What did he scope? Tape does not say.", "How many emails before the yes?"],
    "J": ["SYSTEM SYNTHESIS → `one-channel-deep` (YouTube as the one surface).", "SYSTEM SYNTHESIS → `playbook-before-send` (no send this session).", "SYSTEM SYNTHESIS → Path A later if Evens names a client — not now."],
    "K": ["Inbound-from-build as a Path C surface later. Unassigned."],
    "machines": [{
        "name": "Publish the similar build; wait for inbound",
        "loop": "build in public → email in description → inbound → calls → scope → human yes → stop",
        "qs": "Is there a public similar artifact? Did they email us? Did Evens say yes to scope?",
        "qf": "Qualify on calls. Do not spray a list.",
        "proc": "No outbound sequence. No auto-proposal. Card before any send.",
        "ex": ex("Client wanted something similar", "Emailed from YouTube", "Build was the proof", "Calls + scope + yes", "Inbound is the machine; hunt is not"),
        "why": "He was not for-hire and still closed because the artifact existed.",
        "never": "Unpark Normand. Auto-send because a tape sold. New icp_id.",
        "hive": "`one-channel-deep` · `ask-principal` · `playbook-before-send`",
    }],
    "L": "Steal the inbound machine. Do not operate a hunt. If a similar hive build is ever public, email-in-description is enough — first reply is a draft on a card. Clients parked.",
}

TAKES["Q8aqkHi5qY4"] = {
    "title": "I won the first ever AI agent game show",
    "speaker": "Nate Herk / Agentic Arena hosts",
    "kind": "short",
    "words": 141,
    "A": [
        "Nate named winner of first Agentic Arena. Host offers cash.",
        "Nate: donate it. Cousin had type 1 as a girl; he was diagnosed ~8 months ago.",
        "Community and success have helped; cool people; cool stuff like this.",
        "Host: n8n will match 10 grand to charity; doubling the prize.",
    ],
    "atoms": [src(
        "He routes prize money to type-1 charity and names a personal diagnosis.",
        "The win is social proof; the money move is donation + match theater.",
        "Win → ask what to do with money → donate → sponsor match announced.",
        "On-tape: donate; type 1; 'match 10 grand' from n8n.",
        "Do not quote $10k match as FACT. Do not build a charity SKU.",
        concept="Prize as donation, not a price analog",
        conf="low on $ — UNVERIFIED sponsor line",
    )],
    "C": ["Personal health story is allowed on tape. Hive does not turn it into an offer.", "Community is the value he names, not the cash."],
    "D": ["If a prize appears → do not book it as revenue.", "If a sponsor match is announced → label UNVERIFIED."],
    "E": [ex("Won the arena", "Asked what to do with money", "Type 1 personal + cousin", "Donate + announced match", "$ on tape is not ours")],
    "F": ["If tape names dollars → UNVERIFIED, not FACT.", "If a personal medical story appears → do not productize it."],
    "G": ["Field would treat a win + cash as offer proof. He treats it as donate."],
    "H": ["$10k match and 'doubling' are host claims. UNVERIFIED.", "Diagnosis timeline UNVERIFIED."],
    "I": ["Did the match happen? Tape is the announcement only."],
    "J": ["SYSTEM SYNTHESIS → steal-sheet kill row: YouTube $ is not proof.", "No new ICP."],
    "K": ["Arena-as-distribution later. Unassigned. Not a hunt."],
    "machines": [{
        "name": "Prize money is not a hive price",
        "loop": "public win → someone offers cash → human names the use → stop (no SKU)",
        "qs": "Is this our money? No.",
        "qf": "Do not frame donation as ROI for a client.",
        "proc": "Log $ as UNVERIFIED. Do not write a charity offer.",
        "ex": ex("Winner asked about the cash", "Donate to type 1", "Personal + cousin", "Match announced", "Announcement ≠ FACT"),
        "why": "The only money move on tape is donate + sponsor theater.",
        "never": "Quote 10 grand as FACT. Use the win to unpark a client.",
        "hive": "`ask-principal` if any real money moves; none this session",
    }],
    "L": "No money card. No charity SKU. The win is not permission to send. Clients parked.",
}

TAKES["D-OOsl8C4Ns"] = {
    "title": "AI Sales Agent Transforms Sales with Clear ROI",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 147,
    "A": [
        "ROI in black and white made selling easier — investment not expense.",
        "Landed a second agent after starting True Horizon AI with Milan and Tyler.",
        "Sales agent: handle inquiries, generate quotes, automatically enter CRM.",
        "Talks to customer and orders team; accurate quote; logs name, email, phone, location, conversation summary.",
    ],
    "atoms": [src(
        "A sales agent that quotes and writes CRM is sold as measurable ROI, not as 'an agent.'",
        "Black-and-white return made the second sale easier than a tool pitch.",
        "Inquiry → quote → CRM fields (name/email/phone/location/summary) + orders-team handoff.",
        "On-tape feature list. No live send shown on this short.",
        "Steal quote-draft + CRM log. Auto-send quote is operate-never.",
        concept="Quote + CRM as the sold object",
    )],
    "C": ["Buyers buy investment-with-return, not expense.", "Partners + internal systems came before the product story."],
    "D": ["Frame as measurable return before naming the agent.", "Log PII fields into CRM only after a human says the quote can exist as a draft.", "Talk to orders team — do not let the model invent fulfillment."],
    "E": [ex("Needed a second sold agent", "Sales agent: inquire / quote / CRM", "ROI story from the first sale", "Landed with partners", "The machine is draft-quote + log, not auto-send")],
    "F": ["If the workflow can generate a quote → it is a money artifact → card.", "If it writes phone/email/location → PII → no dump, no auto-send.", "If it 'talks to the customer' → send-removed until Evens."],
    "G": ["Field ships auto-quote-to-inbox. He lists auto-CRM; this desk still gates the send."],
    "H": ["'Automatically' on tape is the trap. Short does not show the send.", "Partner names are on-tape, not a hive vendor."],
    "I": ["Did the quote email the customer or only log? Short is ambiguous.", "What is 'accurate' — human check or model claim?"],
    "J": ["SYSTEM SYNTHESIS → `send-removed` + `invoice-email-automation` (draft only).", "SYSTEM SYNTHESIS → `outcome-offer-funnel` (investment not expense)."],
    "K": ["Sales-agent shape for a named Path A later. Parked."],
    "machines": [{
        "name": "Draft-quote + CRM log (send stays HITL)",
        "loop": "inquiry in → draft quote + field log → human checks accuracy + orders team → Evens sends → stop",
        "qs": "Is the quote accurate? Did orders confirm? Who sends?",
        "qf": "If they want auto-send quotes, refuse. Offer draft + card.",
        "proc": "Strip Send. Keep CRM write behind confirm if it emails.",
        "ex": ex("Customer inquiry", "Generate quote + log PII fields", "ROI story sells the system", "Second agent landed (on-tape)", "Landed ≠ we auto-send"),
        "why": "The sold object is measurable quote/CRM, not a chatbot. Send is the irreversible step he does not prove on this short.",
        "never": "Auto-send quotes. Auto-talk to customers. Treat True Horizon as our SKU.",
        "hive": "`send-removed` · `ask-principal` · `outcome-offer-funnel`",
    }],
    "L": "If a quote/CRM machine is ever built for us, ACTION is 'queue draft quote,' not 'send quote.' PII fields stay off Slack dumps. Clients parked. Tape ROI is UNVERIFIED.",
}

TAKES["ySl-SyboPa4"] = {
    "title": "Sold an AI Agent! My Random Pricing & HUGE ROI Explained",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 188,
    "A": [
        "Charged $1,650 — number was pretty random. Prior sale $1,200 was the baseline; this one 'a bit more.'",
        "Beginner; not thinking about ROI then.",
        "ROI story after the fact: client spent 2–3 hours/week on personalized messages + research.",
        "Time at $50/hour → ~$400/month → payback ~4 months → year ~$5,000 saved + opportunity cost.",
    ],
    "atoms": [src(
        "Beginner price was anchored to a prior sale, then retrofitted into an ROI story.",
        "He did not price from ROI at the time; he narrates ROI so the number looks like a no-brainer.",
        "Hours saved × $50/hr → monthly → payback months → annual.",
        "On-tape arithmetic. All $ UNVERIFIED.",
        "Steal the ROI frame. Do not copy $1650 / $50/hr as ours.",
        concept="Anchor-then-ROI-story",
        conf="low on numbers — UNVERIFIED",
    )],
    "C": ["A random beginner price can still be sold if the buyer feels a bargain vs time.", "He is willing to say the number was random — honesty as proof."],
    "D": ["If you already have a prior price, step up slightly.", "After the fact, compute hours × hourly × months to tell the no-brainer story.", "Do not lead with the workflow."],
    "E": [ex("Second build, more than the $1200 one", "Tried $1650", "Beginner anchor", "Sold; later ROI math", "Frame is stealable; dollars are not")],
    "F": ["If tape $ appears → UNVERIFIED.", "If pricing a real hive job → Evens sets the number on a card.", "If ROI uses $50/hr → do not import as FACT."],
    "G": ["Field pretends prices are scientific. He admits random, then teaches the retrofit."],
    "H": ["$1650 / $1200 / $50 / $400 / $5,000 all UNVERIFIED.", "Opportunity cost is rhetoric."],
    "I": ["What did the agent actually do? This short is price-only.", "Did the client confirm the 2–3 hours?"],
    "J": ["SYSTEM SYNTHESIS → `outcome-offer-funnel` + YF0XPMXLHOA diagnosis questions.", "SYSTEM SYNTHESIS → `paid-slice-funnel` (Evens prices, not the tape)."],
    "K": ["ROI-retrofit language for a named Path A later. Parked."],
    "machines": [{
        "name": "Hours-to-money frame (price stays HITL)",
        "loop": "name weekly hours → pick an hourly (theirs, not tape $50) → annualize → price as a fraction → Evens sets the invoice",
        "qs": "Where are the hours? Whose hourly? Who sends the price?",
        "qf": "If they want a 'random' number from YouTube, refuse.",
        "proc": "Draft the frame. Card the price. No auto-invoice.",
        "ex": ex("Beginner priced $1650 off $1200", "Later computed 2–3h × $50", "Make it a no-brainer", "Year ~$5k story", "Story ≠ our rate card"),
        "why": "Buyers buy payback, not node graphs. The irreversible step is the invoice/send.",
        "never": "Quote $1650 / $50/hr as FACT. Auto-send a priced proposal.",
        "hive": "`outcome-offer-funnel` · `ask-principal` · `paid-slice-funnel`",
    }],
    "L": "Steal the hours×rate frame. Never operate tape dollars. Any real price is a card: ACTION = set price / send invoice. Clients parked.",
}

TAKES["wk8KV280fbg"] = {
    "title": "Are AI Agents commoditized?",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 197,
    "A": [
        "AI-centric selling does not work. Agents/workflows as products are crowded/commoditized.",
        "People sell template libraries claiming $5,000/month resell while charging $200 for the bundle — race to the bottom.",
        "LinkedIn outreach bot: flashiest bot as 'LinkedIn outreach agent' nobody cares; as 'qualified leads without ads' they want it.",
        "Stop selling AI tools; sell outcomes. Spotlight pain. Frame time / money / focus.",
        "Next section tease: sell AI solutions — tool tied to a business pain.",
    ],
    "atoms": [src(
        "The unit of sale is the outcome (time/money/focus), not the agent or template pack.",
        "Template libraries race to the bottom because the pitch is the tool.",
        "Same LinkedIn bot, two frames: agent vs qualified leads without ads.",
        "On-tape contrast. $5k/$200 UNVERIFIED.",
        "Steal outcome-offer. Do not sell template packs. Do not auto-send LinkedIn.",
        concept="Outcome not agent",
    )],
    "C": ["Commodity is the default if you name the tool.", "Pain + time/money/focus is the only frame he trusts."],
    "D": ["Ask what pain. Name time/money/focus. Do not demo the graph first.", "If the object is a LinkedIn bot, refuse the agent-name pitch.", "Do not buy or resell $200 template bundles as a hive SKU."],
    "E": [ex("Flashy LinkedIn outreach bot", "Pitch as qualified leads without ads", "Agent-name is commodity", "People want the outcome frame", "Same nodes, different offer")],
    "F": ["If the pitch names the vendor/tool → rewrite to pain.", "If someone wants auto-outreach → operate-never (send-removed).", "If a pack claims $5k/month resell → UNVERIFIED + kill."],
    "G": ["Field sells agent libraries. He says that market is already dead."],
    "H": ["$5,000/month and $200 bundle are examples, UNVERIFIED.", "LinkedIn bots that send are still never."],
    "I": ["What is the 'next section' solution list? This short stops at the frame."],
    "J": ["SYSTEM SYNTHESIS → `outcome-offer-funnel` (direct).", "SYSTEM SYNTHESIS → steal-sheet kill: generic 'I do AI' / template mills.", "Longer cut: `w9-gfaV5vlM`."],
    "K": ["Outcome vocabulary for Path A when Evens names a client. Parked."],
    "machines": [{
        "name": "Sell the pain-tied outcome, not the agent",
        "loop": "name pain → frame time/money/focus → name the system as the solution → price later on a card → do not send the bot",
        "qs": "What pain? Hours or cash? Does the system send?",
        "qf": "If they want a LinkedIn send-bot, refuse. Offer research+draft.",
        "proc": "Rewrite any 'agent' pitch to outcome. Strip Send.",
        "ex": ex("LinkedIn bot as product", "Reframe: qualified leads without ads", "Commodity vs outcome", "Wanted (on-tape claim)", "Frame stolen; send not operated"),
        "why": "He shows the same artifact dying or living based on the frame.",
        "never": "Auto-send LinkedIn. Resell template packs. Quote $5k/$200 as FACT.",
        "hive": "`outcome-offer-funnel` · `send-removed` · `warm-draft-hitl`",
    }],
    "L": "This is doctrine for cards: ACTION names the outcome, not 'ship an agent.' LinkedIn send stays REJECT. Clients parked.",
}

TAKES["ECfusvK5tEU"] = {
    "title": "4 AI Agents Made $23,000 , You Can Sell AI Too!",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short / cold open",
    "words": 201,
    "A": [
        "Four agents, $23,000 total, four businesses; not complex; he started months after starting out.",
        "Will walk each agent, charge, sales process, how to sell the first; most expensive at the end.",
        "First agent: personalized outreach — drop in a contact list; system researches person+company; writes outreach + follow-up.",
        "SOURCE: 'This agent didn't actually send the messages or run the campaigns.' It filled a database with ready-to-go research-backed messages to plug into email or DM later.",
    ],
    "atoms": [src(
        "The first sold 'outreach agent' explicitly does not send.",
        "Value is research + draft into a database the human plugs into a sequence later.",
        "List in → research → draft message + follow-up → stop at the database.",
        "Direct quote: didn't send or run campaigns.",
        "This is the hive send-removed machine on tape.",
        concept="Outreach that stops at the draft database",
    )],
    "C": ["Beginner-simple can sell. Send is not required for the SKU.", "$23k is a hook — he still starts with the non-sending agent."],
    "D": ["Build research + draft + store. Human plugs into their sender.", "Do not add the send node to 'finish' the product.", "Sales process and prices are promised for the long cut — do not invent them here."],
    "E": [ex("Client has a contact list", "Research each + draft outreach/follow-up", "Send is the dangerous part", "Database of ready messages; he sends later", "The product is the draft pile")],
    "F": ["If it is called an outreach agent → check whether Send exists. If yes, strip it.", "If tape $23,000 → UNVERIFIED.", "If a client asks to 'just send them' → card / REJECT auto."],
    "G": ["Field assumes outreach agents send. His first sold one does not."],
    "H": ["$23,000 UNVERIFIED. Four businesses UNVERIFIED.", "This short is the cold open; details of agents 2–4 not here."],
    "I": ["What did agents 2–4 do? See `HNKlFTd1maM` long cut.", "Who plugged the messages — client or Nate?"],
    "J": ["SOURCE sibling: `HNKlFTd1maM` (four agents $23k walkthrough).", "SYSTEM SYNTHESIS → `send-removed` · `warm-draft-hitl`."],
    "K": ["Draft-database SKU for a named Path A later. Parked."],
    "machines": [{
        "name": "Research-and-draft outreach (no send)",
        "loop": "list in → research person/company → draft + follow-up → write database → human reviews → Evens or client sends → stop",
        "qs": "Does any node have Send? Who reviews the pile?",
        "qf": "If they want campaigns run for them, refuse auto-send. Offer the database.",
        "proc": "Strip Send. Dual-gate warm outreach if Evens ever unparks.",
        "ex": ex("Client drops a list", "Research + draft only", "Send is the campaign", "Filled database", "He said it did not send — keep that"),
        "why": "He sold it without send. Send is the irreversible step this desk exists to hold.",
        "never": "Auto-send / auto-DM / auto-sequence. Quote $23k as FACT. Unpark a list.",
        "hive": "`send-removed` · `warm-draft-hitl` · `playbook-before-send` · `ask-principal`",
    }],
    "L": "This short is the exhibit for send-removed. ACTION on any outreach card is 'fill the draft database,' never 'run the campaign.' $23k stays UNVERIFIED. Clients parked.",
}

TAKES["YF0XPMXLHOA"] = {
    "title": "Price your AI agents so it is a no-brainer for the client",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 222,
    "A": [
        "Team spends 5 hours/week onboarding. Offer: automate 80%. Value: 200+ hours/year × $50/hr = $10,000/year. Price: charge $3k now — fraction of value.",
        "Home-reno analogy: nobody cares about the hammer; they care +$50k value in half the time.",
        "On calls he does not lead with the workflow. He leads with questions: where are you losing the most time? What do you wish could run itself?",
        "Diagnosis points to the solution; solution ties to measurable business (cut off).",
    ],
    "atoms": [src(
        "Price is a fraction of a diagnosed annual dollar value, not a node count.",
        "Diagnosis questions come before the workflow demo.",
        "Hours × hourly × 52 → annual → price ~30% of that (3k of 10k in the example).",
        "On-tape script. All $ UNVERIFIED. 80% automate UNVERIFIED.",
        "Steal the questions + fraction frame. Evens sets the real number.",
        concept="Diagnose then price as a fraction",
        conf="low on arithmetic — UNVERIFIED",
    )],
    "C": ["The hammer (workflow) is what amateurs lead with.", "Questions are the sales system."],
    "D": [
        "Ask: where are you losing the most time?",
        "Ask: what processes do you wish could run themselves?",
        "Compute annual hours × their hourly (not tape $50).",
        "Name a price that is a fraction. Do not send the quote until Evens.",
    ],
    "E": [ex("Onboarding 5h/week story", "80% automate → 200h → $10k → charge $3k", "Price as fraction of value", "No-brainer frame", "Script is stealable; numbers are not")],
    "F": ["If you have not asked the two questions → do not price.", "If you have not seen the workflow → good; do not lead with it.", "If $50/hr or $3k/$10k appear → UNVERIFIED."],
    "G": ["Field leads with the n8n screenshot. He leads with diagnosis."],
    "H": ["5h / 80% / $50 / $10k / $3k / $50k reno all UNVERIFIED examples.", "Short cuts off mid-sentence."],
    "I": ["What is the rest of 'measurable business'? Long cut not this file.", "Does he ever send the quote from the workflow?"],
    "J": ["SYSTEM SYNTHESIS → `discovery-spiced-constraint` · `outcome-offer-funnel` · `demo-walk-script`.", "Pairs with `ySl-SyboPa4` retrofit ROI."],
    "K": ["Call-question card for a named Path A. Parked."],
    "machines": [{
        "name": "Diagnosis questions → fraction-of-value price (HITL invoice)",
        "loop": "two questions → hours → annualize → fraction price → Evens approves invoice → stop",
        "qs": "Where is time lost? What should run itself? Whose hourly?",
        "qf": "If they want a workflow tour first, redirect to the questions.",
        "proc": "Write the frame. Do not auto-send the $3k analog.",
        "ex": ex("5h/week onboarding example", "80% / $10k / charge $3k", "Fraction of value", "No-brainer (on-tape)", "Do not operate tape $"),
        "why": "He says diagnosis always points to the solution. The send is still the hard step.",
        "never": "Quote $3k/$10k/$50 as FACT. Auto-send the priced deck. Lead with our graph.",
        "hive": "`discovery-spiced-constraint` · `outcome-offer-funnel` · `ask-principal`",
    }],
    "L": "Put the two questions on any future Path A card. Price ACTION is Evens. Do not send a no-brainer quote because the short did the math. Clients parked.",
}

TAKES["uC5tDwGhyVA"] = {
    "title": "Create ANYTHING with Sora 2 + n8n AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 263,
    "A": [
        "How to create anything with Sora 2 + n8n. Example: image → video.",
        "Image URL: AI-generated fake curl-cream product.",
        "Prompt: realistic UGC, young woman, curly hair, in car, selfie, what she loves about the product.",
        "Runs workflow; plays result: she praises bounce/curl/lightweight; product comes near camera; font/logo match source.",
        "Compares original still vs product-in-video 'pretty much the exact same.'",
    ],
    "atoms": [src(
        "Image-to-video UGC is a still + a spoken prompt + a human look at the take.",
        "The check is visual: logo/font/product match, not 'the agent published.'",
        "Still URL + UGC prompt → Sora-class render → watch the clip.",
        "On-tape fake product. Sora 2 on-tape.",
        "Steal product-ad-from-photo. Evens publishes. Sora is not our stack.",
        concept="Still-to-UGC-video then human pick",
    )],
    "C": ["Likeness to the still is the quality bar.", "Fake product is fine for a demo; live ads are not automatic."],
    "D": ["Provide the still. Write the UGC prompt. Render. Watch. Pick. Do not post from the node."],
    "E": [ex("Fake curl cream still", "UGC car-selfie prompt + run", "Image-to-video unlocks potential (his words)", "Clip matches logo/font; product to camera", "Look is the stop; publish is Evens")],
    "F": ["If the clip will be an ad → publish card.", "If the product is fake → do not use as client proof.", "Sora stays on-tape."],
    "G": ["Field would auto-post UGC. He stops at 'that's insane' / look."],
    "H": ["Sora 2 / n8n are on-tape vendors.", "No $ on this short."],
    "I": ["Did he post the ad? Tape does not show publish.", "Audio rights?"],
    "J": ["SYSTEM SYNTHESIS → `product-ad-from-photo` · `clip-factory` · `motion-pipeline`.", "Longer cut: `Vm8QOo9MiC4`."],
    "K": ["UGC-from-still for Creative Studio later. Unassigned."],
    "machines": [{
        "name": "Still + UGC prompt → preview → Evens publishes",
        "loop": "still in → prompt → render → human watch (logo/font/product) → pick → publish card → stop",
        "qs": "Does the still match? Is this a real SKU? Who posts?",
        "qf": "If they want auto-post to TikTok/IG, refuse.",
        "proc": "Creative Studio cuts. Publishing Engine does not fire.",
        "ex": ex("Curl cream still", "Run Sora-class UGC", "Unlock image-to-video", "Matched still", "Match ≠ live ad"),
        "why": "He judges by looking. Looking is not posting.",
        "never": "Auto-publish. Sora as our stack. Fake product as Path A proof.",
        "hive": "`product-ad-from-photo` · `clip-factory` · `ask-principal`",
    }],
    "L": "Queue the render. ACTION = publish or reject the take. No social post from a node. Clients parked.",
}

TAKES["UT_Ek_tmeVA"] = {
    "title": "I Built a Nano Banana AI Agent in n8n with no code",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 302,
    "A": [
        "Nano Banana Photoshop agent. Edit-image demo: photoreal ad of granola held in front of the Eiffel Tower.",
        "Agent finds file ID in memory or raw files; searches raw files; calls edit image.",
        "Drive folder 'AI image generation' → granola ad Eiffel. Bag matches; held at tower.",
        "Words mostly right except top line ('ingredients you can see and pronounce' garbled).",
        "Two causes: raw file is low quality (he cannot read it); model will get better; current prompt is minimal.",
        "CTA to full breakdown.",
    ],
    "atoms": [src(
        "Bad source + thin prompt produce a pretty ad with wrong text. Human still has to read the type.",
        "He names both failure modes instead of blaming the model only.",
        "Find file → edit image → write Drive → human inspects type.",
        "On-tape granola/Eiffel; he points at the broken headline.",
        "Steal inspect-the-type. Do not publish the first pretty frame.",
        concept="Pretty ad still needs a type check",
    )],
    "C": ["Photoreal is not done. Legible product copy is the stop.", "He expects models to improve; he still ships a human look now."],
    "D": ["Resolve file ID (memory or search raw).", "Call edit. Open the Drive file. Read every word on the pack.", "If source is low-res, fix the source before another generate."],
    "E": [ex("Granola + Eiffel request", "Search raw files + edit image", "Need a photoreal ad", "Good scene; broken ingredients line", "Look at the type or you ship a lie")],
    "F": ["If product text exists → human reads it before publish.", "If source is unreadable → do not expect the model to invent the legal line.", "Nano Banana / Gemini image stays on-tape."],
    "G": ["Field posts the first pretty frame. He shows the miss."],
    "H": ["Visual-only quality is INFERENCE from his narration.", "Timestamp UNKNOWN."],
    "I": ["What is the full prompt in the long cut?", "Who owns granola brand rights? Demo only."],
    "J": ["SYSTEM SYNTHESIS → `product-ad-from-photo` · `click-live-site` analog (look at the artifact).", "Sibling: `TWvjqpk3uSQ` ask-the-name."],
    "K": ["Type-check as a Creative stop. Unassigned."],
    "machines": [{
        "name": "Generate then read the type",
        "loop": "find file → edit → open Drive → read every word → fix source or prompt → Evens publishes",
        "qs": "Can a human read the source? Is the headline legal/true?",
        "qf": "Pretty is not a pass.",
        "proc": "Reject publish if type is wrong. Do not auto-post.",
        "ex": ex("Granola Eiffel ad", "Edit image", "Photoreal request", "Scene good, type broken", "Type check is the gate"),
        "why": "He pointed at the miss. Autonomy would have posted the miss.",
        "never": "Auto-publish. Treat Nano Banana as our stack.",
        "hive": "`product-ad-from-photo` · `ask-principal` · `click-live-site` (look at the file)",
    }],
    "L": "Any image/ad card includes RISK = wrong on-pack type. ACTION = open the file, not publish. Clients parked.",
}

TAKES["9mqsVK6Iqoc"] = {
    "title": "Build Your First Inbox Agent in 30 Minutes",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 327,
    "A": [
        "Inbox agent starts with Gmail trigger. UI prompts On message received because the canvas is empty.",
        "Wireframe next: text classifier on subject+body into four categories.",
        "Execute step errors — no AI connected. Connect AI, rerun, works.",
        "Customer-support example routes to customer support; finance/billing/high-priority/promotion empty.",
        "CTA to full breakdown.",
    ],
    "atoms": [src(
        "Wireframe the branches before the model. The first execute fails until a brain is attached.",
        "Classifier is a router, not a replier.",
        "Gmail received → text classifier → one of four paths.",
        "On-tape error then correct branch.",
        "Steal inbox-to-task routing. Auto-reply is operate-never.",
        concept="Classify first; do not reply first",
    )],
    "C": ["The builder UI knowing you need a trigger is convenience, not a gate.", "An error is a missing dependency, not a dead workflow."],
    "D": ["Add Gmail on-received. Add text classifier with four named buckets.", "Connect the model before execute. Confirm the branch with a pinned example.", "Do not attach Send on the support branch."],
    "E": [ex("Customer-support sample email", "Execute classifier", "First run no model → error; second run routes support", "One item on support, zero on others", "Router proven; reply not built")],
    "F": ["If Gmail trigger exists → Send is a risk. Strip it.", "If classifier has no model → do not trust empty output.", "Four buckets must be named before live mail."],
    "G": ["Field jumps to auto-reply. He stops at routing."],
    "H": ["26 Gmail actions mentioned — do not enable them all.", "Long cut is `HN0oWxbF2bM`."],
    "I": ["What happens on each branch in the full course?", "Does he ever auto-reply?"],
    "J": ["SYSTEM SYNTHESIS → `inbox-to-task-routing` · `send-removed`.", "Long: `HN0oWxbF2bM`."],
    "K": ["Inbox router for icp `us` later. Parked."],
    "machines": [{
        "name": "Gmail in → classify → task path (no reply)",
        "loop": "message received → classify subject/body → named bucket → create task/draft → Evens if outbound → stop",
        "qs": "Which bucket? Is Send attached? Who replies?",
        "qf": "Support vs promo vs billing vs urgent. Promo never auto-sends.",
        "proc": "Wireframe first. Connect model. Pin a golden email. No Send.",
        "ex": ex("Support email fixture", "Classifier after Gmail trigger", "Need a path", "Landed on support", "Path ≠ reply"),
        "why": "He shows the error and the correct branch. He does not send.",
        "never": "Auto-reply. Always-on Gmail Send. Treat 30 minutes as a live install.",
        "hive": "`inbox-to-task-routing` · `send-removed` · `golden-test-loop`",
    }],
    "L": "Inbox cards are route-and-draft. ACTION = classify to a task, not send the reply. Clients parked.",
}

TAKES["8IUWeF3B-hk"] = {
    "title": "STOP Guessing! Evaluating Your Agents is Easy",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 332,
    "A": [
        "If you sell workflows you must evaluate. Evaluation = validate a hypothesis with objective proof.",
        "Usual loop: unhappy → 'if I do X it gets better' → change → subjective better/worse.",
        "n8n eval: dataset of six examples with expected category + expected priority → through the model → write answers back to the sheet → scores in evaluations tab.",
        "Run test: tokens, prompts, duration averages + priority/category correctness. All six processed; some right, some wrong.",
    ],
    "atoms": [src(
        "A labeled set beats a vibe check. Selling without eval is guessing.",
        "Hypothesis → change → measured correctness on held examples.",
        "Six rows with expected category/priority → run → write-back → score.",
        "On-tape: six items, some wrong. He shows the misses.",
        "Steal golden-test-loop. Do not treat token averages as FACT.",
        concept="Labeled eval before you sell the workflow",
    )],
    "C": ["Subjective 'looks better' is what he is replacing.", "Misses in the six are expected and useful."],
    "D": ["Write expected labels first. Run the set. Read which rows failed. Change one hypothesis. Re-run.", "Do not ship because the happy path worked once."],
    "E": [ex("Need to prove a tagger", "Six labeled rows through the model", "Objective proof to sell", "Average scores + per-row right/wrong", "A miss on the sheet is the lesson")],
    "F": ["If you cannot name expected output → you are not evaluating.", "If you only have one happy email → not a set.", "Token/latency averages are telemetry, not a ship gate."],
    "G": ["Field ships on a single demo execute. He says that is guessing."],
    "H": ["Six is a tiny set. Correctness % UNVERIFIED as a product claim.", "n8n evaluations UI is on-tape."],
    "I": ["What is a passing score for him? Tape does not say.", "Does he block deploy on fail?"],
    "J": ["SYSTEM SYNTHESIS → `golden-test-loop` (direct).", "Pairs with `NWbh5ZoEHkA` tool-for-weakness."],
    "K": ["Eval harness for any inbox/RAG router we keep. Unassigned."],
    "machines": [{
        "name": "Hypothesis + labeled set + write-back",
        "loop": "write expected labels → run set → inspect misses → one change → re-run → stop (do not send)",
        "qs": "What is the hypothesis? How many labeled rows? Which failed?",
        "qf": "If they want to sell without a set, refuse.",
        "proc": "Keep the sheet. Do not overwrite expected labels with model output blindly — he writes AI answers to compare.",
        "ex": ex("Six category/priority rows", "Run evaluations", "Replace subjective taste", "Some wrong", "Wrong rows are the product"),
        "why": "He defines eval as objective proof. Proof is the sheet, not a vibe.",
        "never": "Ship because one execute looked good. Quote token averages as FACT. Auto-send the tagged mail.",
        "hive": "`golden-test-loop` · `ask-principal` before any sold deploy",
    }],
    "L": "Any workflow that would be sold or would send needs a labeled set on the card. ACTION = run eval, not deploy. Clients parked.",
}

TAKES["NQhsLVmuItA"] = {
    "title": "n8n's NEW Guardrail Node is a Gamechanger for AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 339,
    "A": [
        "Two guardrail actions: check text for violations (uses AI) vs sanitize text (no AI — encrypt/desensitize before the LLM).",
        "Keyword block demo: three items; one pass (omelette order); two fail (update the system setting; enter your password).",
        "Blocked keywords: password, system.",
        "He says if it passes you can send your email or update CRM; if it fails, Slack yourself, throw an error, stop the workflow.",
        "CTA to full cut.",
    ],
    "atoms": [src(
        "Sanitize-before-model is the cheap guardrail; keyword fail must stop the world action.",
        "He names send-email as the pass path — that is the operate-never payload, not the steal.",
        "Text in → check or sanitize → pass/fail branches.",
        "On-tape three fixtures; omelette passes; password/system fail.",
        "Steal fail-stops-the-workflow. Do not steal pass→send.",
        concept="Guardrail fail is a stop, not a suggestion",
    )],
    "C": ["Non-AI sanitize is preferred when you can desensitize without a model.", "You fully control pass vs fail behavior — control ≠ auto-send."],
    "D": ["Sanitize PII before the LLM when possible.", "Keyword/block list for password/system-class strings.", "Fail → Slack Evens or error. Pass → still a card if the next node is Send."],
    "E": [ex("Three test strings", "Keyword check password/system", "Show pass vs fail", "Omelette pass; two fails", "Fail branch is the machine; pass→email is the trap")],
    "F": ["If text contains password/system-class tokens → fail/stop.", "If sanitize can strip PII without AI → do that first.", "If pass path includes Send → strip Send anyway."],
    "G": ["Field treats guardrails as permission to auto-send. He shows them as branch control — this desk still holds Send."],
    "H": ["Keyword lists are brittle (false fail on 'system'). He does not discuss that.", "Long cut: `oWdJMJp2HgM`."],
    "I": ["Does sanitize reversible-encrypt or irreversible-redact?", "Who maintains the keyword list?"],
    "J": ["SYSTEM SYNTHESIS → `send-removed` · `input-required-gate`.", "SYSTEM SYNTHESIS → classifier-is-not-Evens (AI violation check)."],
    "K": ["Sanitize-before-model for any inbox/RAG. Unassigned."],
    "machines": [{
        "name": "Sanitize / fail-stop (pass is not send)",
        "loop": "text in → sanitize if PII → keyword/AI check → fail: Slack + error → pass: draft only → Evens if outbound",
        "qs": "Did we sanitize? Which keywords? Is Send on the pass branch?",
        "qf": "A guardrail is not Evens. A pass is not APPROVE.",
        "proc": "Keep fail = stop. Rewrite his pass example from 'send email' to 'queue draft.'",
        "ex": ex("password / system fixtures", "Check text", "Block secrets", "Two fail, one pass", "Fail stop stolen; pass-send rejected"),
        "why": "He proves fail can halt. He also names send-on-pass — that payload stays never.",
        "never": "Auto-send because the guardrail passed. Treat AI violation-check as Evens.",
        "hive": "`send-removed` · `input-required-gate` · `ask-principal`",
    }],
    "L": "Guardrail nodes are allowed as stops. They are not a second approver. Pass + Send on the same canvas is REJECT. Clients parked.",
}

TAKES["9IzGe0BBj_c"] = {
    "title": "n8n's New Instance Level MCP: What It Is and How It Works",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 361,
    "A": [
        "Instance-level MCP vs older per-workflow MCP server triggers.",
        "Old: you assign tools/workflows; a client (Claude/Cursor) calls those.",
        "New: client can search the entire instance, read schemas, execute any workflow.",
        "Metaphor: ChatGPT is the agent; every workflow is a tool it can see and call.",
        "CTA to full cut. Names ChatGPT, Claude, Lovable, Cursor as clients.",
    ],
    "atoms": [src(
        "Instance MCP turns every workflow into a callable tool, including ones that send.",
        "The jump is from allow-listed tools to whole-instance execute.",
        "Client searches instance → understands schema → executes any workflow.",
        "On-tape: 'execute any of them.'",
        "Steal search-then-call for allow-listed tools only. Whole-instance execute is never.",
        concept="Whole-instance execute is a blast radius",
    )],
    "C": ["He thinks of MCP as 'just an AI agent' — convenient and dangerous.", "Convenience ('use them whenever they want') is the pitch."],
    "D": ["If MCP is on, list which workflows have Send/book/deploy.", "Do not always-allow execute-any.", "Cursor talking to n8n is on-tape; we do not install Claude/Lovable."],
    "E": [ex("Many existing workflows", "Instance MCP so Claude/Lovable can fire them", "Avoid rebuilding tools", "Client can execute any", "Any includes the send workflow")],
    "F": ["If a client can execute any workflow → treat as production keys.", "If always-allow is offered → REJECT.", "If the only need is one tool → old per-workflow MCP, not instance."],
    "G": ["Field wants one brain over the whole instance. This desk wants allow-lists."],
    "H": ["Cursor is named as a client — we already use Cursor; we still do not always-allow send.", "Long: `5p5cV0yVDvQ` / `mPflFTQUCGk`."],
    "I": ["Can you scope instance MCP to a folder? Short does not say."],
    "J": ["SOURCE sibling: `mPflFTQUCGk` actually sends mail via MCP.", "SYSTEM SYNTHESIS → `send-removed` · `input-required-gate`."],
    "K": ["Allow-listed MCP for read-only hive tools later. Unassigned."],
    "machines": [{
        "name": "Allow-listed tool MCP (not execute-any)",
        "loop": "name the one workflow → expose only that → client calls → if it can send, card → stop",
        "qs": "Which workflows have Send/book? Is instance-wide on?",
        "qf": "Whenever-they-want is a no.",
        "proc": "Prefer per-workflow servers. Instance MCP stays off for send/book.",
        "ex": ex("Whole n8n instance", "Instance MCP to Claude/Lovable", "Use existing workflows", "Execute any", "Any is the never"),
        "why": "He says the client knows when to call each one. A model deciding 'when' on send is not Evens.",
        "never": "Instance-wide execute. Always-allow. Claude/Lovable as our stack. Auto-send via MCP.",
        "hive": "`send-removed` · `input-required-gate` · `ask-principal`",
    }],
    "L": "Instance MCP that can see a send workflow is a live wire. ACTION = keep it off or allow-list read-only. The `mPflFTQUCGk` send demo is the exhibit. Clients parked.",
}

TAKES["tNOk29fs_aY"] = {
    "title": "I Built this Agent in 2 Hours and Made $1,200",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short / cold open",
    "words": 367,
    "A": [
        "Built in 2 hours; someone paid $1,200; not complex; would take 30 minutes now; you could build it.",
        "Will walk what it does, why they paid, what it means if you start from zero.",
        "SOURCE: it is not an AI agent — it is a workflow/system; 'agent' was a buzzword.",
        "Every day, three morning runs: idea-generator AI for topics that appeal to the client's audience, company brand/tone, nurture/convert the LinkedIn avatar.",
        "Simple graph: aggregate, split, HTTP, create content. He was full-time, building for fun.",
        "CTA implied to long cut `bxGE_LXPyAU` / `8C6iCpJ9HPo`.",
    ],
    "atoms": [src(
        "A sold 'agent' can be a scheduled content workflow. Honesty: it is not an agent.",
        "Three morning idea runs + brand voice is the product, not a chat loop.",
        "Cron ×3 → idea generator → branded content for LinkedIn nurture.",
        "On-tape: 'not an AI agent at all' + $1200 / 2h / 30m now.",
        "Steal scheduled idea pile. Auto-publish LinkedIn is never. $ UNVERIFIED.",
        concept="Scheduled content workflow sold as an agent",
        conf="low on $ and times — UNVERIFIED",
    )],
    "C": ["Buzzwords sell; he later tells the truth.", "Fun + full-time job is how he learned, not a 24/7 agency pose."],
    "D": ["Name it a workflow if it is a workflow.", "Schedule idea generation. Human posts.", "Do not quote 2 hours / $1200 as our rate."],
    "E": [ex("LinkedIn nurture need", "3× morning idea generator + brand prompt", "Simple, sellable", "$1200 on-tape", "Money UNVERIFIED; schedule≠publish")],
    "F": ["If it only creates content → publish is a card.", "If they call it an agent → correct the noun on the card.", "If $1200 appears → UNVERIFIED."],
    "G": ["Field calls everything an agent. He walks it back."],
    "H": ["$1200 / 2h / 30m UNVERIFIED.", "LinkedIn conversion claims UNVERIFIED."],
    "I": ["Did the system post or only generate? Short says create content.", "See long cuts for the graph."],
    "J": ["Long: `bxGE_LXPyAU` $2600 / `8C6iCpJ9HPo` $1200.", "SYSTEM SYNTHESIS → `clip-factory` · `one-channel-deep`."],
    "K": ["Morning idea pile for icp `us` later. Parked."],
    "machines": [{
        "name": "Scheduled idea pile (human posts)",
        "loop": "cron → generate branded ideas → store → Evens/client posts → stop",
        "qs": "Does any node publish? Whose brand voice?",
        "qf": "If they want auto-post, refuse.",
        "proc": "Generate only. Publishing Engine waits.",
        "ex": ex("LinkedIn avatar nurture", "3× morning generator", "Simple system", "Sold $1200 (on-tape)", "Sold ≠ we auto-post"),
        "why": "He sold a schedule + generator. Posting is the hard step.",
        "never": "Auto-publish. Quote $1200/2h as FACT. Call a cron an autonomous agent in a client send.",
        "hive": "`clip-factory` · `one-channel-deep` · `ask-principal`",
    }],
    "L": "Correct the noun on cards: workflow not agent. ACTION = queue ideas, not post. $1200 UNVERIFIED. Clients parked.",
}

TAKES["Fu6vOfzFmcw"] = {
    "title": "How to Keep Your RAG Agent's ACCURATE",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 397,
    "A": [
        "Simple RAG: new doc in a Drive folder → vector DB.",
        "Drive trigger: changes in a specific folder, watch file created. Fetch test event.",
        "Download file by ID from the trigger. Supabase vector store. Run → five items appear.",
        "Quick agent, no system prompt, one tool: 'what is our shipping policy?'",
        "Answers: processed 1–2 days; standard 3–7 days; he says it is correct.",
        "CTA to full video.",
    ],
    "atoms": [src(
        "Folder-drop ingest plus one golden question is the accuracy check, not a bigger graph.",
        "He validates by asking a known fact from the just-ingested FAQ.",
        "Drive create → download by ID → upsert vectors → ask shipping policy.",
        "On-tape: five chunks; shipping answer he calls correct.",
        "Steal folder-to-vectors + golden question. Supabase/Drive stay how, not our SKU.",
        concept="Ingest then ask a known fact",
    )],
    "C": ["A promptless agent plus one tool can be enough to validate ingest.", "Accuracy is 'does it match the doc I just dropped.'"],
    "D": ["Watch one folder. Download by trigger ID. Upsert. Ask a fact you can verify by opening the doc.", "Do not skip the golden question."],
    "E": [ex("Policy/FAQ dropped in Drive", "Trigger → download → Supabase", "Need RAG without a huge pipeline", "Five vectors; shipping answer matches", "One known question is the stop")],
    "F": ["If ingest ran but no golden question → not done.", "If the answer cites nothing → do not trust (this short does not show citations).", "If the folder can take secrets → wrong folder."],
    "G": ["Field builds giant RAG graphs first. He builds ingest + one ask."],
    "H": ["'Correct' is his eye, not a labeled set (contrast `8IUWeF3B-hk`).", "Supabase on-tape."],
    "I": ["Chunking settings? Not on this short.", "What if two policies conflict?"],
    "J": ["SYSTEM SYNTHESIS → `wiki-ingest` · `golden-test-loop`.", "Siblings: `ZwQ8rJhVCr4` four RAG methods; `QojPKL96Dx4` / `kOKavHnlPik`."],
    "K": ["Drive-folder ingest for hive wiki later. Unassigned."],
    "machines": [{
        "name": "Folder ingest + one golden question",
        "loop": "drop doc → trigger → vectorize → ask a known fact → human compares to source → stop",
        "qs": "Which folder? What is the known fact? Did the answer match the file?",
        "qf": "No secrets in the watch folder.",
        "proc": "Do not expose the agent to send. Validation is read-only.",
        "ex": ex("Shipping FAQ", "Drive → Supabase → ask policy", "Prove ingest", "He says correct", "His eye is not Evens on a client FAQ"),
        "why": "He proves the pipe with one question. That is the checkable stop.",
        "never": "Auto-answer customers from the new index. Treat Supabase as required stack.",
        "hive": "`wiki-ingest` · `golden-test-loop` · `ask-principal` if answers go outbound",
    }],
    "L": "RAG cards stop at 'golden question matches the file.' Customer-facing answers are a send/book risk — REJECT auto. Clients parked.",
}

TAKES["0Ujdys4LqNs"] = {
    "title": "I Built a Multi-Agent Newsletter System Live",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 398,
    "A": [
        "After trigger: research with Tavily. Query is a stable niche: 'AI adoption for small businesses.'",
        "Returns three URLs + summaries. Then an AI agent for titles/topics.",
        "Adds OpenRouter GPT-5-mini. System message: expert newsletter planner; three articles from the past week; creative title + main topics.",
        "Runs; fields come back; he pins the data so he does not rerun if something goes wrong.",
        "CTA to full breakdown (`pxzo2lXhWJE`).",
    ],
    "atoms": [src(
        "Pin successful research so a later fail does not re-bill the search.",
        "Research (stable query) and planning (title/topics) are separate agents.",
        "Trigger → Tavily (fixed niche) → planner agent → pin.",
        "On-tape pin. OpenRouter / GPT-5-mini / Tavily on-tape.",
        "Steal pin-the-good-intermediate. Do not auto-send the newsletter.",
        concept="Pin the research before the writer",
    )],
    "C": ["Reruns are waste. Pin is operational hygiene.", "The niche query stays the same every run — consistency over novelty."],
    "D": ["Fix the research query. Take three sources. Separate planner prompt. Pin. Then writer (not on this short).", "Do not Gmail-send from this canvas."],
    "E": [ex("Need newsletter topics", "Tavily three URLs then planner agent", "Don't rerun research on fail", "Pinned fields", "Pin is the checkable stop for this slice")],
    "F": ["If research succeeded → pin before touching the writer.", "If the next node is Gmail → card.", "Vendor models stay on-tape."],
    "G": ["Field reruns the whole graph. He pins."],
    "H": ["GPT-5-mini / OpenRouter / Tavily on-tape.", "No send shown here."],
    "I": ["Does the long cut send? Check `pxzo2lXhWJE` / `rXpHzWXjHrw`.", "Who approves the title?"],
    "J": ["Long: `pxzo2lXhWJE`. Text-to-workflow send risk: `rXpHzWXjHrw`.", "SYSTEM SYNTHESIS → `session-bootstrap` (slice) · `slice-build`."],
    "K": ["Pinned research for a hive briefing later. Unassigned."],
    "machines": [{
        "name": "Research → plan → pin (send later, HITL)",
        "loop": "stable query → three sources → planner → pin → human picks title → writer draft → Evens sends",
        "qs": "Are the three URLs real? Is Gmail on the graph?",
        "qf": "A pinned plan is not a sent letter.",
        "proc": "Stop after pin on this slice. No send node.",
        "ex": ex("SMB AI-adoption niche", "Tavily + planner + pin", "Avoid rerun cost", "Fields pinned", "Pin ≠ publish"),
        "why": "He pins so a fail does not redo research. That is the cheap stop.",
        "never": "Auto-send the newsletter. Treat OpenRouter/Tavily as required stack.",
        "hive": "`slice-build` · `ask-principal` · `send-removed`",
    }],
    "L": "Newsletter graphs die at pin/draft. ACTION = approve title, not send. Clients parked.",
}

TAKES["EiHVBPyvTiE"] = {
    "title": "Build ANYTHING with Gemini 3 Pro and n8n AI Agents",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 420,
    "A": [
        "Gemini 3 Pro release blog: 'new era' / most intelligent / any idea. Available in Google AI Studio; gallery of builds.",
        "How to connect in n8n: Gemini node (analyze audio/document/upload) → create credential → API key from AI Studio + billing.",
        "Shows a key-shaped secret and says copy it into n8n.",
        "Or attach Google Gemini chat model to an AI agent — same credential.",
        "CTA to full cut `Vb1SwBAn9cQ`.",
    ],
    "atoms": [src(
        "Connecting Gemini is a billed API key pasted into n8n. Same key serves node and chat-model.",
        "He walks billing + paste. That is a secret-handling procedure.",
        "AI Studio → create key + billing → paste into n8n credential → reuse on agent.",
        "On-tape: he displays a key-like value.",
        "Steal one-credential-reuse. Operate-never: paste keys in chat; Gemini as our stack.",
        concept="One billed key, two attachment points",
    )],
    "C": ["Vendor 'build anything' is marketing; the real step is billing + credential.", "Reuse the credential — do not mint a second key casually."],
    "D": ["If we ever needed a Google key (we do not, this session): create in the vendor console, store in a secret manager, never in chat/transcript.", "Do not install Gemini as hive brain."],
    "E": [ex("Need Gemini in n8n", "Node credential or chat-model, same key", "One billing setup", "Connected (on-tape)", "Key-in-UI is a leak risk")],
    "F": ["If a key is visible on a tape → rotate if it were ours (it is his demo).", "If billing is required → money card.", "Gemini stays on-tape."],
    "G": ["Field treats 'get API key' as trivial. This desk treats it as secrets + money."],
    "H": ["Gemini 3 Pro claims UNVERIFIED.", "Visual key must be assumed demo/redacted — still a bad pattern."],
    "I": ["Did he redact the key? Unknown.", "What experiments are in the long cut?"],
    "J": ["Long: `Vb1SwBAn9cQ`.", "SYSTEM SYNTHESIS → secrets are Tier-3 (this desk). `send-removed` analog for keys."],
    "K": ["Credential hygiene notes. Unassigned."],
    "machines": [{
        "name": "Vendor key is a secret + a money event",
        "loop": "need a vendor → Evens approves spend → key in secret store (not chat) → attach one credential → stop",
        "qs": "Is this our stack? Who pays? Where does the key live?",
        "qf": "If the tape says Gemini/Claude/Codex, it is on-tape only.",
        "proc": "REJECT installing Gemini. If a key must exist, never paste in chat (see Hermes tape later).",
        "ex": ex("Connect Gemini", "AI Studio key + billing into n8n", "One credential", "Node and agent share it", "Reuse is fine; paste-on-tape is not"),
        "why": "Billing + key is pay + secrets — both Tier-3.",
        "never": "Install Gemini. Paste keys in chat. Auto-create billing.",
        "hive": "`ask-principal` (pay/secrets) · Cursor + Grok only",
    }],
    "L": "API-key + billing is a money/secrets card. ACTION = REJECT Gemini install this session. Clients parked.",
}

TAKES["TWvjqpk3uSQ"] = {
    "title": "I Built a Photoshop AI Agent That Uses Google's New NanoBanana",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 425,
    "A": [
        "Telegram photo in → upload Drive → agent asks what to name the file (would have been today's date).",
        "He replies 'call it Nate' → change-name tool → Media folder shows Nate.",
        "Second photo: granola bag → asks name again → 'granola' → rename.",
        "Then: combine Nate + granola into photoreal man holding granola hiking on a mountain.",
        "Combine-image / Nano Banana. Drive link: kind granola spelling correct; his face; mountain.",
        "CTA to full cut.",
    ],
    "atoms": [src(
        "The agent asks the human for the filename before it writes Drive. That is HITL on tape.",
        "Default would have been the date — he overrides with a name.",
        "Telegram image → Drive → ask name → rename → later combine on request.",
        "On-tape: 'what would you like me to name that photo?' twice.",
        "Steal ask-the-name. Combine/publish still Evens.",
        concept="Ask the name before the write",
    )],
    "C": ["Eager upload is OK; silent rename is not.", "Two assets, two asks — he does not batch-skip the question."],
    "D": ["Ingest the file. Ask the name. Wait. Rename. Ask what is next. Combine only on an explicit message.", "Human opens the Drive link and looks."],
    "E": [ex("Telegram selfie + granola", "Ask name twice, then combine on mountain", "Don't keep date-stamped junk", "Named files + combined ad", "Ask is the machine; autonomy is not")],
    "F": ["If a file will be written → ask the name (or Evens).", "If combine is requested → still a look-at-the-link stop.", "If the next step is post-to-social → card."],
    "G": ["Field would auto-name and auto-combine. He asks."],
    "H": ["Nano Banana / Telegram / Drive on-tape.", "Spelling 'correct' is his eye."],
    "I": ["Sharing settings? Sister short `IlNwjnIzrOo` asks sharing too.", "Does Telegram ever post out?"],
    "J": ["SOURCE sibling: `IlNwjnIzrOo` (ask name + sharing; autonomy trap).", "SYSTEM SYNTHESIS → `ask-principal` · `product-ad-from-photo`."],
    "K": ["Ask-the-name as default on any Drive write. Keep."],
    "machines": [{
        "name": "Ask the name, then write Drive",
        "loop": "image in → stage in Drive → ask name → wait → rename → ask next → edit/combine → human opens link → publish card if any",
        "qs": "What is the name? Sharing? Does this post?",
        "qf": "Silence is not a name.",
        "proc": "No default-date publish. No social node.",
        "ex": ex("Telegram photo", "Ask 'call it Nate'", "Avoid date filename", "Renamed + later combined", "The ask is HITL"),
        "why": "He already waits. That is confirm-then-actuate on a filename.",
        "never": "Auto-name + auto-post. Creative autonomy as publish (see long media army).",
        "hive": "`ask-principal` · `confirm-then-actuate` · `product-ad-from-photo`",
    }],
    "L": "Filename asks are a legal analog of the five-field card — cheap, reversible. Keep them. Combine/publish still Evens. Clients parked.",
}

TAKES["G9Ho8n4lD6I"] = {
    "title": "Build Your First Voice AI Agent with Vapi and n8n",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short",
    "words": 434,
    "A": [
        "Create blank Vapi assistant named booking agent for Hercules Detailing. Callers book via the site number.",
        "Needs calendar look + create event. Vapi tools: Google Calendar create event + check availability.",
        "ChatGPT writes the system prompt (name Nate, booking assistant, when to use each tool).",
        "Test call: full interior+exterior today → checks availability 4–6pm → user picks 5pm → asks email → books + confirmation email to nate@acample.com.",
        "CTA to full cut. Vapi / ChatGPT / Calendar on-tape.",
    ],
    "atoms": [src(
        "The demo books the slot and sends a confirmation email inside the voice turn.",
        "Prompt includes when-to-use-tools; ChatGPT drafted it.",
        "Call → check availability → offer slots → collect email → create event + email.",
        "On-tape: 'You're all set. I've booked… A confirmation email has been sent.'",
        "Steal check-availability + read-back. Operate-never auto-book / auto-email.",
        concept="Voice book in one turn is the never",
        ep="SOURCE",
    )],
    "C": ["A booking assistant that can create events will create them.", "Generated prompt + live calendar is enough for him to demo a close."],
    "D": ["If voice is ever used: check availability only. Read back. Card. Evens books.", "Do not attach create-event or confirmation-email to the assistant.", "Vapi is not our stack."],
    "E": [ex("Hercules Detailing test call", "Check 4–6, pick 5, email, book+send", "Show a working booker", "Booked + email sent on-tape", "That close is the operate-never payload")],
    "F": ["If the tool list includes create event → REMOVE before any hive run.", "If confirmation email exists → send-removed.", "If ChatGPT wrote the prompt → draft only (see `NO97pqqc10A`)."],
    "G": ["Field wants voice that closes. Hive doctrine: missed-call-book + ask-principal, no auto-voice-book."],
    "H": ["Vapi / ChatGPT / Google Calendar on-tape.", "acample.com is a demo email.", "Long: `zWLZ3bVVwD8` / `BO-jFbN4p8Y` / `y-cq_Qo4zVo`."],
    "I": ["Did it write a real calendar? Demo claims yes.", "What if 5pm was a hallucination?"],
    "J": ["SYSTEM SYNTHESIS → `missed-call-book` · `private-book-install` · `ask-principal`.", "Kill row: auto-book without callback.", "Siblings: `glM8godEcic` (auto-book 8am), `-Lo_SlSgtnA` (auto-dial)."],
    "K": ["Availability-check-only voice later if Evens asks. Unassigned."],
    "machines": [{
        "name": "Voice qualify + offer slots (book stays HITL)",
        "loop": "call in → identify need → check availability (read-only) → read back slots → take preference + email as draft → Evens creates event → stop",
        "qs": "What service? Which day? Email for the card, not for auto-confirm.",
        "qf": "If they want the agent to 'just book it,' refuse create-event.",
        "proc": "Tools: check availability only. No create event. No confirmation email. Vapi stays on-tape.",
        "ex": ex("Full detail today", "Agent offers 4–6, user picks 5, agent books+emails", "Demo a closer", "You're all set + email sent", "Steal the slot-offer; reject the close"),
        "why": "The useful machine is check + offer. The irreversible machine is create-event + email.",
        "never": "Auto-book. Auto-voice-book. Confirmation email. Vapi as stack. ChatGPT-written live prompt.",
        "hive": "`ask-principal` · `missed-call-book` · `private-book-install` · `send-removed`",
    }],
    "L": "This is a canonical auto-book tape. Steal slot-offer language. ACTION on any voice card = REJECT create-event. Format RISK = booked a real 5pm. Clients parked. No Vapi.",
}

TAKES["-6yUeJ3rkvg"] = {
    "title": "OpenAI's Agent Builder vs. n8n: What You Need to Know",
    "speaker": "Nate Herk | AI Automation",
    "kind": "short / cold open",
    "words": 436,
    "A": [
        "Headline bait: OpenAI killed n8n? He says no. Agent Kit vs n8n; different audiences.",
        "Agent Kit: teams/consumers inside OpenAI; quick internal workflows / conversational agents — not custom robust automations.",
        "n8n: built for developers, more technical, can do anything.",
        "Compare: ease of use, triggers, agent tools, model support, UI chat components, deployment and control.",
        "Ease of use: drag from start, name agent, instructions, chat history, model, reasoning, tools, output text/JSON/widget. Less intimidating; palette on the left.",
        "CTA to full cut.",
    ],
    "atoms": [src(
        "Two builders can both be 'agent' products and not be competitors if audiences differ.",
        "He refuses the killed-n8n narrative before the category table.",
        "State the audience → then score categories.",
        "On-tape: 'my answer is no' + different audiences.",
        "Steal competitive-teardown structure. Do not install Agent Kit.",
        concept="Audience-first teardown",
    )],
    "C": ["Narrative online is usually wrong. Compare surfaces, not tweets.", "Ease-of-use winning does not mean it should replace the powerful tool."],
    "D": ["List categories before demos. State audience. Do not switch stack because a kit looks less scary.", "Widget/JSON output is a feature to note, not to ship."],
    "E": [ex("Internet says OpenAI killed n8n", "He says no; different audiences; starts ease-of-use", "Stop the narrative", "Kit looks less intimidating", "Less scary ≠ our stack")],
    "F": ["If a vendor ships an agent builder → teardown, do not migrate.", "If ease-of-use wins a category → still not a reason to auto-deploy.", "OpenAI / n8n stay on-tape."],
    "G": ["Field panics at Agent Kit. He says OpenAI is not even trying to be n8n."],
    "H": ["Full category winners are not on this short.", "n8n-as-ours is still not an install of n8n-cloud."],
    "I": ["Who wins deployment/control in the long cut?", "Does Agent Kit have a send tool?"],
    "J": ["SYSTEM SYNTHESIS → `competitive-teardown`.", "Stack rule: Cursor + Grok, not Agent Kit."],
    "K": ["Teardown table as a Researcher format. Unassigned."],
    "machines": [{
        "name": "Audience-first builder teardown",
        "loop": "viral 'X killed Y' → list categories → name audiences → demo ease → stop (no migrate)",
        "qs": "Who is it for? Does it send/deploy?",
        "qf": "Less intimidating is not a migrate signal.",
        "proc": "Write the table. Do not create an OpenAI Agent Kit account for the hive.",
        "ex": ex("Agent Kit launch narrative", "No + different audiences + ease demo", "Kill the panic", "Kit looks simpler", "Simple is not ship"),
        "why": "He separates narrative from fit. Fit still is not our stack change.",
        "never": "Install Agent Kit / ChatGPT as hive OS. Auto-deploy a kit widget.",
        "hive": "`competitive-teardown` · Cursor + Grok only",
    }],
    "L": "Teardown is allowed. Migration is a deploy card — REJECT. Agent Kit stays on-tape. Clients parked.",
}


def main():
    n = 0
    for vid, t in TAKES.items():
        write_one(vid, t)
        n += 1
        print("wrote", vid)
    print("batch1", n)


if __name__ == "__main__":
    main()

